### PR TITLE
Fix dead assignment detected by clang CI

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ghost** [comment]
I enable auto-merge **rebase**

**Comment by ghost** [comment]
the openbsd test is a flaky test:

* https://github.com/rizinorg/rizin/commit/17fa72e4ecb22c4abcb16654515f451f569b5e2b => fail
* https://github.com/rizinorg/rizin/commit/b68ee6eb911640ad73a9c32d2cfe55e4b8a0ed3f => valid

**Comment by ret2libc** [comment]
> the openbsd test is a flaky test:
> 
>     * [17fa72e](https://github.com/rizinorg/rizin/commit/17fa72e4ecb22c4abcb16654515f451f569b5e2b) => fail
> 
>     * [b68ee6e](https://github.com/rizinorg/rizin/commit/b68ee6eb911640ad73a9c32d2cfe55e4b8a0ed3f) => valid

Yeah we are aware :( I tried a bunch of time to reproduce it locally but I couldn't. We should attach to the openbsd machine when it happens.

**Comment by ret2libc** [comment]
Resolve conflicts please

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
