### PR TITLE
Fix `rz_str_ndup()`-related OOB read by using `rz_str_ndup_buflen()`

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes this [`rz_str_ndup()`-related OOB read](https://github.com/rizinorg/rizin/runs/5828574225?check_suite_focus=true#step:19:26) by using `rz_str_ndup_buflen()`, since unlike [POSIX `strndup()`](https://pubs.opengroup.org/onlinepubs/9699919799/functions/strdup.html), it guarantees that the pointer returned is to a buffer of size `len + 1`.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
can you reopen this PR with a branch containing the word `fuzz` ?

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — CHANGES_REQUESTED** [review]
I think this is the wrong place to fix. IMHO the problem is in `rz_str_filter`, which should always ensure that `str[i]` is not `\x00`. The `len` in `rz_str_filter` is a `max_length` imho. (if you change that function please add doxygen doc).

**Comment by kazarmy** [comment]
> can you reopen this PR with a branch containing the word `fuzz` ?

sure, see #2504

**Comment by kazarmy** [comment]
> the problem is in `rz_str_filter`, which should always ensure that `str[i]` is not `\x00`.

Not all strings are null-terminated, e.g. [Pascal strings](https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed).

**Comment by ret2libc** [comment]
> > the problem is in `rz_str_filter`, which should always ensure that `str[i]` is not `\x00`.
> 
> Not all strings are null-terminated, e.g. [Pascal strings](https://en.wikipedia.org/wiki/String_(computer_science)#Length-prefixed).

I think `rz_str_*` functions should deal with the C strings, aren't they? They are used to manipulate C strings (as used by rizin itself), rather than the "string concept" used in the binaries. Am I wrong?

**Comment by kazarmy** [comment]
A look at `rz_str_filter()` indicates that it's being used to convert non-printable characters to dots, presumably for printing. Thus, it appears likely that it's being used on strings-of-the-binary rather than internal rizin strings. Perhaps it shouldn't be in `rz_str_*` but where should it be?

**Pull request closed without merging**
