### PR TITLE
Support for assembling slti instructions.

### PR DESCRIPTION
**Pull request by matteius**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

I extended my local version of cutter to be able to insert multiple MIPs instructions at once, then I realized it can dissasemble slti isntructions but not re-assemble them so I was getting errors inserting these.

**Test plan**

Just trying to help, but before this change this would fail:
```
(base) matteius@matteius-3-0:~/cutter/build$ ./Rizin-prefix/bin/rz-asm -a mips -b 32 'slti v0, a0, 9'
09008228
```

**Closing issues**
Not sure if this has been reported in any issues yet.

### CODE REVIEW

**Comment by wargio** [comment]
please add a test under the `tests/db/asm` dir

**Comment by matteius** [comment]
@wargio Are the asm tests there just testing that it can compute the assembly of an instruction using in this case `slti`?   Also I don't see a regular mips32 or mips test file, but I do see mips64 ...

**Comment by wargio** [comment]
you are right. that is indeed an issue. ok for me then.

**Comment by wargio** [comment]
https://github.com/rizinorg/rizin/issues/4509

**Review by wargio — APPROVED** [review]

**Pull request merged**
