### PR TITLE
Fix Linux native debugger compilation for ARM64

### LINKED ISSUE #3393: ninja build subcommand fail & variables skipped on arm64
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Debian arm 64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86/32, x86/64

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/3393

### CODE REVIEW

**Comment by wargio** [comment]
this one probably needs to be defined by meson. we should have some checks and based on the result of the compilation, then choose

**Comment by XVilka** [comment]
@wargio what can be defined by meson? This change should be meson-agnostic. Moreover, the whole file is a huge mess of `ifdef`s, untangling them is far beyond the scope of this PR.

**Comment by ret2libc** [comment]
I agree with @XVilka

**Comment by wargio** [comment]
what i meant is that with meson we can try and compile this as a small snippet and we can try to determine which is the actual type based on these tests, so we do not have to keep fixing this back and forward.

**Pull request merged**
