### PR TITLE
Rename some of the environment variables

### LINKED ISSUE #3808: Rename some of the environment variables
- [ ] `{ "RZ_RCONFIGHOME", confighome },` -> `RZ_CONFIGHOME`
- [ ] `{ "RZ_RDATAHOME", datahome },` -> `RZ_DATAHOME`
- [ ] `{ "RZ_RCACHEHOME", cachehome },` -> `RZ_CACHEHOME`
- [ ] `{ "RZ_LIBR_PLUGINS", plugins },` -> `RZ_LIB_PLUGINS`

Should fix sources and fortune messages

### PR DESCRIPTION
**Pull request by byteninjaa0**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
updated three files-
./doc/fortunes.tips
./librz/include/rz_lib.h
./librz/main/rizin.c

...

**Test plan**

...

**Closing issues**
closes #3808 

...

### CODE REVIEW

**Review by wargio — COMMENTED** [review]
i'm ok with this, but @ret2libc @XVilka might break stuff. probably is ok with 0.7?

**Comment by XVilka** [comment]
Yes, it's a breaking change but needs to be done anyway, I think.

**Comment by byteninjaa0** [comment]
but all the test have been passed successfully what will it break then

**Comment by wargio** [comment]
users setup. but i agree with XVilka. this needs to be done anyway

**Comment by ret2libc** [comment]
Yeah definitely for 0.7.0, it's quite a big change. We should also remember to highlight it in the release notes.

**Comment by byteninjaa0** [comment]
how to fix it then?

**Comment by wargio** [comment]
the fix is correct. if the others are ok, then we can merge.
(just approve) 3 votes and merge.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Review by kazarmy — APPROVED** [review]

**Pull request merged**
