### PR TITLE
Update libmspack to v1.11

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Comment by wargio** [comment]
something is very broken on appveyor
```
..\subprojects\xz-5.4.1\src\common\tuklib_integer.h(647,2): error: call to undeclared library function '_BitScanReverse' with type 'unsigned char (unsigned long *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        _BitScanReverse(&i, n);
        ^
..\subprojects\xz-5.4.1\src\common\tuklib_integer.h(647,2): note: include the header <intrin.h> or explicitly provide a declaration for '_BitScanReverse'
..\subprojects\xz-5.4.1\src\common\tuklib_integer.h(749,2): error: call to undeclared library function '_BitScanForward' with type 'unsigned char (unsigned long *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
        _BitScanForward(&i, n);
        ^
```

**Comment by XVilka** [comment]
@wargio it's not broken, they just updated Clang to 16.0.1

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
> @wargio it's not broken, they just updated Clang to 16.0.1

It should be broken on `dev` branch too, right?

**Comment by wargio** [comment]
> > @wargio it's not broken, they just updated Clang to 16.0.1
> 
> It should be broken on `dev` branch too, right?

yes

**Comment by XVilka** [comment]
@ret2libc I think they updated yesterday, so it didn't show in the latest `dev` commit.

**Comment by wargio** [comment]
should i merge this regardless if is red or not?

**Comment by XVilka** [comment]
Yes, redness could be fixed separately

**Pull request merged**
