### PR TITLE
Fix windows ood crash and remove obsolete windows debug files ##debug

### PR DESCRIPTION
**Pull request by yossizap**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

The old windows debug files that are no longer used(replaced by the refactored files in `windows\`) caused a collision with the definitions in `windows_debug.h` and `windows_heap.h` in [17926](https://github.com/radareorg/radare2/issues/17926) in addition to an issue with clang-cl's -fno-common. 
Commit [Fix clang-cl build](https://github.com/rizinorg/rizin/commit/fa992004a6653140d897a53024349dad769a1cd3) was supposed to fix it but by setting the w32 API global function pointers to static it made them unique for each file, meaning that `windows_maps.c:rz_w32_dbg_modules` received `w32_CreateToolhelp32Snapshot` as NULL because it was initialized in `windows_debug.c`. Since the build fix is no longer needed, I reverted all of the static global changes so they won't cause similar issues when used in different files.

**Test plan**

Open a binary with `-d` or run `ood`, see that Rizin doesn't crash.
~~Couldn't add a test because running windows binaries in rz-test is currently unsupported, will try to fix it in a different PR and add a test there.~~

### CODE REVIEW

**Comment by ret2libc** [comment]
> Couldn't add a test because running windows binaries in rz-test is currently unsupported, will try to fix it in a different PR and add a test there.

Works for me!

**Comment by yossizap** [comment]
You're right, there's a misleading error in "CreateProcess" that made things confusing with the lack of windows tests and an issue I had with my terminal emulator.

Added a simple test for multiple ood+doc for now that should cover this crash and previous regressions with ood/doc.

**Review by XVilka — APPROVED** [review]
Less code is always better! 👍

**Comment by ret2libc** [comment]
> You're right, there's a misleading error in "CreateProcess" that made things confusing with the lack of windows tests and an issue I had with my terminal emulator.
> 
> Added a simple test for multiple ood+doc for now that should cover this crash and previous regressions with ood/doc.

I don't see the test though

**Review by ret2libc — COMMENTED** [review]
Why was all the code in w32.c ever needed? What does it do? WHy it's not needed any more?

**Comment by yossizap** [comment]
> Why was all the code in w32.c ever needed? What does it do? WHy it's not needed any more?

Seems to be the pre-refactor implementation of our current windows debugger added in [14096](https://github.com/radareorg/radare2/pull/14096). It's not in use and it wasn't maintained since the rework.

**Review by ret2libc — APPROVED** [review]

**Comment by p371jah** [comment]
Shame on me...

**Pull request merged**
