### PR TITLE
Fix ls command parser

### PR DESCRIPTION
**Pull request by dvertx**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

ls -l -q and -e did not work for any given path. This fixes the problem

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Thanks! Though it's better to convert it to the rzshell instead and move out from `librz/util`:
- `librz/core/cmd_descs/cmd_shell.yaml`
- `librz/core/cmd/cmd_shell.c`
- https://rizin.re/posts/rzshell/
- https://github.com/rizinorg/rizin/blob/dev/doc/rzshell.md

**Comment by dvertx** [comment]
The patch is within RZ_API RZ_OWN char *rz_syscmd_ls(RZ_NONNULL const char *input) located in syscmd.c.
I see that rz_cmd_shell_ls_handler() in cmd_shell.c calls rz_syscmd_ls(arg). The only similiar API to rz_syscmd_ls(arg) is RZ_API RZ_OWN char *rz_syscmd_ls(RZ_NONNULL const char *input), the one in syscmd.c. Maybe I am mistaken?

**Comment by XVilka** [comment]
> The patch is within RZ_API RZ_OWN char *rz_syscmd_ls(RZ_NONNULL const char *input) located in syscmd.c. I see that rz_cmd_shell_ls_handler() in cmd_shell.c calls rz_syscmd_ls(arg). The only similiar API to rz_syscmd_ls(arg) is RZ_API RZ_OWN char *rz_syscmd_ls(RZ_NONNULL const char *input), the one in syscmd.c. Maybe I am mistaken?

You are right, looks like it was incomplete conversion to the rzshell back in time. Ideally what inside this function could be simplified by using `int argc, const char **argv` parameters. And it should not be in the RzUtil.

**Comment by dvertx** [comment]
So, is there any other thing to do in my part to help with the conversion?

**Comment by XVilka** [comment]
@dvertx yes, just see how other handlers are implemented in `librz/core/cmd/cmd_shell.c` and modify the code of the `ls` handler, by merging `rz_syscmd_ls` code directly into the handler (and moving necessary static functions along the way) and modify it to not do manual parsing but take supplied arguments from the `argv` array.

**Review by ret2libc — APPROVED** [review]
The changes are improving the situation though and fix a problem, so they can be merged as-is IMHO.

**Comment by XVilka** [comment]
Merged as is, thanks, but please send a new PR with the rzshell conversion, if possible.

**Pull request merged**
