### PR TITLE
Refactor and move `get_targets_map_base()` to elf_map.c 

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Move the get_targets_map_base function to librz/bin/format/elf/elf_map.c. This function doesn't reuse map_unpatched.

PS: this PR is based on https://github.com/rizinorg/rizin/pull/1728.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
Needs conflict resolution.

**Comment by ghost** [comment]
I will resolve this after https://github.com/rizinorg/rizin/pull/1728 merged.

**Comment by XVilka** [comment]
@08A please rebase on top of the latest `dev`.

**Review by XVilka — APPROVED** [review]
Looks good, lets wait for one more approval please

**Comment by thestr4ng3r** [comment]
What is the motivation for this change?

**Comment by ghost** [comment]
> What is the motivation for this change?

`maps_unpatched` is a costly function, the use of internal representation reduce memory usage. IMHO such function should be in the elf plugin and not in the interface.

**Review by thestr4ng3r — APPROVED** [review]

**Pull request merged**
