### PR TITLE
Add ignore paths for codeql analysis

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Codeql shouldn't analyse capstone, tree-sitter or sdb

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
How can you see whether this worked or not?

**Comment by ghost** [comment]
2021-02-03-195744_470x34_scrot

**Comment by ghost** [comment]
```
Specifying directories to scan

For the interpreted languages that CodeQL supports (Python and JavaScript/TypeScript),
you can restrict code scanning to files in specific directories by adding a paths array to the
configuration file. You can exclude the files in specific directories from analysis by adding a
paths-ignore array.
```

So it is not perfect

**Comment by ghost** [comment]
I checking solution to ignore C related alert

**Comment by ret2libc** [comment]
I meant: how can you see if it really ignored subprojects or not.

**Comment by ghost** [comment]
> I meant: how can you see if it really ignored subprojects or not.

There is no log for that.

**Review by ret2libc — APPROVED** [review]
can we merge @08A ?

**Comment by ghost** [comment]
> can we merge @08A ?

No

I was trying to ignore paths for all compiled language but it seems to be impossible for Rizin. So after the merge, I will discard all alerts related to suprojects.

Righ now the "Code scanning results" never failed, this is really dangerous because the developer should be notified about new alerts.

Can you search on the Rizin repository configuration (settings) , if there is a way to enable it? If you don't find anything. I will open an issue on https://github.com/github/codeql-action.

PS: "Mixed linter and checks" isn't required

**Comment by ghost** [comment]
2021-02-06-154459_824x72_scrot

Those tasks should failed if there is new alerts / warnings

**Comment by XVilka** [comment]
I made "Mixed linter and checkes" required for merge as suggested.

**Comment by ghost** [comment]
> I made "Mixed linter and checkes" required for merge as suggested.

thanks

**Comment by ret2libc** [comment]
> > can we merge @08A ?
> 
> No
> 
> I was trying to ignore paths for all compiled language but it seems to be impossible for Rizin. So after the merge, I will discard all alerts related to suprojects.
> 
> Righ now the "Code scanning results" never failed, this is really dangerous because the developer should be notified about new alerts.
> 
> Can you search on the Rizin repository configuration (settings) , if there is a way to enable it? If you don't find anything. I will open an issue on https://github.com/github/codeql-action.

I can't find anything in settings about this.

**Comment by ghost** [comment]
> > > can we merge @08A ?
> > 
> > 
> > No
> > I was trying to ignore paths for all compiled language but it seems to be impossible for Rizin. So after the merge, I will discard all alerts related to suprojects.
> > Righ now the "Code scanning results" never failed, this is really dangerous because the developer should be notified about new alerts.
> > Can you search on the Rizin repository configuration (settings) , if there is a way to enable it? If you don't find anything. I will open an issue on https://github.com/github/codeql-action.
> 
> I can't find anything in settings about this.

okay, I will open an issue.

**Comment by ghost** [comment]
I create the issue.

https://github.com/github/codeql-action/issues/389

**Comment by ghost** [comment]
I move everything related to "treating warnings as errors" => https://github.com/rizinorg/rizin/pull/557

**Review by ret2libc — APPROVED** [review]

**Comment by ghost** [comment]
I remove the use of `jq`. It is not perfect. We need to manually close everything related to subprojects.

**Comment by ghost** [comment]
All the sarif stuff will be used for the second PR

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
