### PR TITLE
ci: use Ubuntu 22.04 LTS for Travis

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Maybe it will help to solve the failing Travis CI PPC64LE?

**Test plan**

Travis CI is green

### CODE REVIEW

**Comment by XVilka** [comment]
Now the PPC64LE *did start* but fails with the cryptic error, just like other jobs (ARM64 and S390):
```
docker_mtu_and_registry_mirrors
0.07s$ travis_apt_get_update
Installing APT Packages
0.03s$ sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi binutils-x86-64-linux-gnu
apt-get.diagnostics
apt-get install failed
$ cat ${TRAVIS_HOME}/apt-get-update.log
sudo: unable to resolve host travis-job-rizinorg-rizin-622424348: Temporary failure in name resolution
E: Malformed entry 1 in list file /etc/apt/sources.list.d/mongodb-org-6.0.list (URI parse)
E: The list of sources could not be read.
The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install binutils-aarch64-linux-gnu binutils-arm-linux-gnueabi binutils-x86-64-linux-gnu" failed and exited with 100 during .
```
Build system information confirms it's the right distribution and platform:
```
Build language: generic
Build dist: jammy
Build id: 270754418
Job id: 622424348
Runtime kernel version: 5.4.0-52-generic
travis-build version: fc260482
Build image provisioning date and time
Thu Apr 27 07:49:59 UTC 2023
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy
Linux Version
5.4.0-121-generic
Git version
git version 2.34.1
bash version
GNU bash, version 5.1.16(1)-release (powerpc64le-unknown-linux-gnu)
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software; you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
GCC version
gcc (Ubuntu 11.3.0-1ubuntu1~22.04) 11.3.0
Copyright (C) 2021 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Docker version
Docker version 20.10.21, build 20.10.21-0ubuntu1~22.04.2
Client:
 Version:           20.10.21
 API version:       1.41
 Go version:        go1.18.1
 Git commit:        20.10.21-0ubuntu1~22.04.2
 Built:             Thu Mar  2 18:26:54 2023
 OS/Arch:           linux/ppc64le
 Context:           default
 Experimental:      true
LLVM version
Ubuntu clang version 14.0.0-1ubuntu1
Target: powerpc64le-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Pre-installed Ruby versions
ruby-3.1.2
Pre-installed Node.js versions
v10.24.1
v12.22.12
v14.21.3
v16.20.0
v18.16.0
v4.9.1
v6.17.1
v8.12.0
v8.17.0
mysql --version
mysql  Ver 8.0.32-0ubuntu0.22.04.2 for Linux on ppc64le ((Ubuntu))
Redis version
redis-server 6.0.16
ant -version
Apache Ant(TM) version 1.10.12 compiled on October 13 2021
mvn -version
Apache Maven 3.6.3
Maven home: /usr/share/maven
Java version: 11.0.18, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/temurin-11-jdk-ppc64el
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-121-generic", arch: "ppc64le", family: "unix"
phpenv versions
* 8.2 (set by /home/travis/.phpenv/version)
  8.2.0
0.08s0.04s1.55s0.30s0.10s0.05s0.08s0.00s0.05s0.00s0.05s0.01s0.75sOK
```
Reported this to support.

**Comment by kazarmy** [comment]
Try removing the `dist:` line entirely (https://travis-ci.community/t/could-not-resolve-host-github-com-randomly-on-xcode-builds-for-the-last-week/5735/4)

**Comment by XVilka** [comment]
Doesn't work. And now with fixed PPC64LE we can postpone the upgrade.

**Comment by kazarmy** [comment]
yeah, xenial is gcc 5.4.0 which is very old

**Pull request closed without merging**
