### PR TITLE
 Set the default capstone version to v5 instead of v4 

### PR DESCRIPTION
**Pull request by yossizap**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

v5 isn't going to be released officially anytime soon and there are new instructions like Intel's CET that aren't supported in v4. As long as the tests pass I don't see a reason not to do update.

**Test plan**

See that tests are green

### CODE REVIEW

**Comment by ret2libc** [comment]
BTW, some code uses `CSNEXT` because acr/make defines that, however I think it is wrong and we should just use `CS_API_MAJOR`/`CS_API_MINOR` as usual.

**Review by ITAYC0HEN — APPROVED** [review]

**Comment by wargio** [comment]
TBH, it looks like capstone v5 has some wrong output.

**Review by ret2libc — CHANGES_REQUESTED** [review]
As previously said (here on mattermost, don't remember) you probably have to change `analysis_riscv_cs.c`to not use `CSNEXT` but check the CS_API_* defines as done elsewhere.

**Comment by XVilka** [comment]
Could you please rebase this one? There are conflicts need to be resolved.

**Comment by XVilka** [comment]
We should also update the subproject wraps since now the project moved to https://github.com/capstone-engine/capstone

**Comment by XVilka** [comment]
@yossizap could you please rebase and solve the conflicts? Then we could see what is broken

**Comment by XVilka** [comment]
Closed in favor of https://github.com/rizinorg/rizin/pull/3301

**Pull request closed without merging**
