### PR TITLE
Release 0.2.0

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

```
git checkout stable
git merge -s ours dev
git checkout --detach dev
git reset --soft stable
git checkout stable
git commit --amend -C HEAD
```

**Test plan**

Everything is green and shiny.

### CODE REVIEW

**Comment by ret2libc** [comment]
```diff
diff --git a/shlr/packagefiles/tree-sitter-0.19.4/meson.build b/shlr/packagefiles/tree-sitter-0.19.4/meson.build
new file mode 100644
index 0000000000..47593313fc
--- /dev/null
+++ b/shlr/packagefiles/tree-sitter-0.19.4/meson.build
@@ -0,0 +1,29 @@
+project('tree-sitter', 'c')
+
+cc = meson.get_compiler('c')
+
+tree_sitter_cflags = ''
+if cc.has_argument('-std=gnu99')
+  tree_sitter_cflags = '-std=gnu99'
+elif cc.has_argument('-std=c99')
+  tree_sitter_cflags = '-std=c99'
+endif
+
+tree_sitter_path = 'tree-sitter'
+
+tree_sitter_files = ['lib/src/lib.c']
+
+tree_sitter_inc = [include_directories('lib/src'), include_directories('lib/include')]
+
+libtree_sitter = static_library('tree_sitter', tree_sitter_files,
+  include_directories: tree_sitter_inc,
+  implicit_include_directories: false,
+  c_args: tree_sitter_cflags,
+  install: not meson.is_subproject()
+)
+
+tree_sitter_dep = declare_dependency(
+  compile_args: tree_sitter_cflags,
+  link_with: libtree_sitter,
+  include_directories: tree_sitter_inc
+)

```

I think you accidentally added some file/dir wrongly. I suggest we always use `git diff origin/dev..origin/<new-branch>` when doing these big merges, to make sure nothing wrong happened.

**Comment by wargio** [comment]
we need to test this on various distros with shared libs already installed on the system

**Comment by ret2libc** [comment]
> we need to test this on various distros with shared libs already installed on the system

I would test at least Arch, because it ships many smaller libs like tree-sitter which are not available in other distros, and at most Ubuntu, but I wouldn't exaggerate on testing this, it's impossible to check all various configurations.

**Comment by XVilka** [comment]
@ret2libc it was added before this PR, see https://github.com/rizinorg/rizin/commit/d8eef9205a94cfaf4f1893fc597c90ecbb7be29c#diff-333f618d2320067ddc37b95b05c5138cfb0c0c592b47076d2cf5cf8a6946aea7

**Comment by XVilka** [comment]
>  but I wouldn't exaggerate on testing this, it's impossible to check all various configurations.

I agree, it's a 0.x release after all, also we always can do a 0.2.x hotfix versions later.

**Comment by ret2libc** [comment]
Are we aware that by doing this there may be duplicated commits in stable? See for example `Use full github.ref name`, `Fix typo: heads not head`, `Fix names in the release job`, and probably others... cc @thestr4ng3r @XVilka

**Comment by XVilka** [comment]
@ret2libc I don't think it's a problem.

**Comment by karliss** [comment]
There is one potential blocker from Cutter side related to sdb linking. Haven't fully debugged yet if it's a problem in the way rizin is built or on Cutter side.

**Comment by thestr4ng3r** [comment]
Yeah I would just ignore those commits. They are on a different branch anyway when you do `git log --graph` for example so that's correct.

**Pull request merged**
