### PR TITLE
[WIP] Add RzOption implementation ##util

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The RzOption implementation is a list of macro to defined and implement some custom type.

The best practice is to define the struct in a public header and implement the struct in a private header.

**Test plan**

I have added some simple check.

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
What are exactly the problem we are trying to solve with this?
Do you have specific examples of such problems?
Did you think about other solutions (e.g. returning a bool as error value and passing the return value as `*` argument)?

**Comment by ghost** [comment]
IMHO, this object could be useful to represent addresses that are not defined (better alternative than UT64_MAX). The use of boolean isn't a bad idea if localized to a specific problem. The use of a common struct could harmonized a lot of APIs (the value undefined would always be None).

**Comment by ret2libc** [comment]
@thestr4ng3r cc

**Comment by XVilka** [comment]
Closing since abandoned

**Pull request closed without merging**
