### PR TITLE
Fixes for Windows input when `e scr.vtmode=1` 

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

Manually tested

**Closing issues**

None

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
From the code point of view looks fine. It would be awesome if anyone would be able to test it on Windows.

**Comment by ret2libc** [comment]
@GustavoLCR what was the problem exactly?

**Comment by wargio** [comment]
can you explain me what is that value for? i never understood it from the code..

**Comment by GustavoLCR** [comment]
On Windows, support for VT escape sequences varies a lot.
Depending on the version, some terminals may be able to process VT sequences and generate VT input, some terminals may only be able to process VT and require to use the APIs to get mouse/special characters.

The `scr.vtmode` values mean:
`e scr.vtmode=0`: Go through the Console APIs for everything (Windows <=8)
`e scr.vtmode=1`: Output VT sequences, use the Console APIs for input (Windows >=10)
`e scr.vtmode=2`: Output VT sequences, receive VT sequences input (Windows Terminal, mintty, all other OSs)

d4700a6 Fixes when setting the console flags to raw, the `ENABLE_MOUSE_INPUT` flag mistakenly getting unset

a924c41 Fixes shifted keystroke being discarded from the input queue. For some reason the bug only happens under Windows Terminal and I'm not sure why there was even code for flushing the input buffer in the first place.

**Comment by wargio** [comment]
i think we really need to define this with an enum. this can be done later.

thank you for the explaination

**Review by wargio — APPROVED** [review]

**Pull request merged**
