### PR TITLE
Add note regarding rz_bin_reloc_free and bin_coff

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr just adds a small note regarding why reloc imports and symbols cannot be freed in `rz_bin_reloc_free()` with regard to bin_coff.

**Test plan**

The note makes sense. All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by p371jah** [comment]
Actually other bin plugins (e.g. `bin_le`, `bin_mach0`, `bin_pe`) do the same.

**Comment by kazarmy** [comment]
There seems to be a specific and relatively easy fix for `bin_pe`. For `bin_coff`, the fix apparently needs to be more general.

**Comment by p371jah** [comment]
> There seems to be a specific and relatively easy fix for `bin_pe`. For `bin_coff`, the fix apparently needs to be more general.

What do you mean under `fix`?

**Comment by kazarmy** [comment]
#4490 has the general ideas (the bin_pe fix is separate from the rest). The `"coff"` hardcode is obviously bad but fixing that requires some design thinking.

**Pull request merged**
