### PR TITLE
Remove length restrictions in analysis classes and various serializations

### LINKED ISSUE #1696: Analysis of binary with `aaa` resulting in segfault.
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Void Linux x86_64
| File format of the file you reverse (mandatory)      | PE
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.3.0-git @ linux-x86-64 commit: bbcd57d771ba08fecc2b422d8b4216a93f0eaaec, build: 2021-09-14__20:27:55

### Expected behavior

Binary is analyzed successfully so further inspection can be done.

### Actual behavior

Rizin reaches the step `Check for classes` and segfaults.

GDB Output:
```
[0x1047861b]> aaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[ ] Check for classes
Program received signal SIGSEGV, Segmentation fault.
__strchr_avx2 () at ../sysdeps/x86_64/multiarch/strchr-avx2.S:57
57      ../sysdeps/x86_64/multiarch/strchr-avx2.S: No such file or directory.
```

### Steps to reproduce the behavior

1. Open the binary ( `rizin client.dll` )
2. Run `aaa`

### Binary
[client.zip](https://github.com/rizinorg/rizin/files/7171879/client.zip)

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Long class names would exceed the `sdb_fmt()` limitation of 256 chars and then make `sdb_anext()` fail.
Solution is to just not use `sdb_fmt()` at all.
Also, sdb had some internal restrictions for keys and values, which have now been removed except when cdb is used.

**Test plan**

Run the tests.

**Closing issues**

Fix #1696

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
We should also [drop `sdb_fmt()` use then in many other places](https://github.com/rizinorg/rizin/issues/1168) as well.

**Comment by thestr4ng3r** [comment]
Due to additional length checks in sdb, this fixes the segfaults, but storing anything with a key longer than the limit silently fails.

**Review by wargio — APPROVED** [review]

**Comment by thestr4ng3r** [comment]
requires https://github.com/rizinorg/sdb/pull/35

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
Love the teeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeests! 👍

**Pull request merged**
