### PR TITLE
Cherry-picks for the 0.4.1 release

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Imported all important fixes **except** PE ones since we refactored the PE, and they should be cherry-picked manually, better in a separate PR.

**Test plan**

CI is green

### CODE REVIEW

**Comment by XVilka** [comment]
Need to fix also this:
```
FAILED: subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_name_locate.c.o 

gcc -Isubprojects/libzip-1.9.2/liblibzip.a.p -Isubprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2 -I../subprojects/libzip-1.9.2/lib -Isubprojects/zlib-1.2.12 -I../subprojects/zlib-1.2.12 -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -std=c99 -O2 -g -Werror=sizeof-pointer-memaccess -fvisibility=hidden -DRZ_ASSERT_STDOUT=1 -fPIC -MD -MQ subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_name_locate.c.o -MF subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_name_locate.c.o.d -o subprojects/libzip-1.9.2/liblibzip.a.p/lib_zip_name_locate.c.o -c ../subprojects/libzip-1.9.2/lib/zip_name_locate.c

../subprojects/libzip-1.9.2/lib/zip_name_locate.c: In function ‘_zip_name_locate’:

../subprojects/libzip-1.9.2/lib/zip_name_locate.c:76:41: error: ‘strcasecmp’ undeclared (first use in this function); did you mean ‘strncmp’?

   76 |         cmp = (flags & ZIP_FL_NOCASE) ? strcasecmp : strcmp;

      |                                         ^~~~~~~~~~

      |                                         strncmp

../subprojects/libzip-1.9.2/lib/zip_name_locate.c:76:41: note: each undeclared identifier is reported only once for each function it appears in
```
https://app.travis-ci.com/github/rizinorg/rizin/jobs/580766485#L980

Seems the same problem as in https://github.com/rizinorg/rizin/issues/2905

**Comment by ret2libc** [comment]
@XVilka i think you need 98acbb041a64f8c0dbe867aa8bca742e586498cd

**Comment by thestr4ng3r** [comment]
The following should be removed from here because they have behavorial changes: 8fb97d3 01eee16

**Comment by XVilka** [comment]
So many assert triggers...
```


[XX] db/formats/luac/luac53 LUAC: disasm crash
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'pd 10 >/dev/null
' bins/luac/big53.luac
-- stdout
--- expected
+++ actual
@@ -1,0 +1,1 @@
+WARNING: (../librz/bin/bobj.c:421):rz_bin_object_set_items: runtime check failed: (o->symbols->free)

-- stderr
WARNING: No calling convention defined for this file, analysis may be inaccurate.
../librz/asm/arch/luac/lua_arch.c:8:16: runtime error: left shift of 128 by 24 places cannot be represented in type 'int'
../librz/asm/arch/luac/lua_arch.c:8:16: runtime error: left shift of 128 by 24 places cannot be represented in type 'int'
```

**Comment by wargio** [comment]
to be added https://github.com/rizinorg/rizin/pull/2984

**Comment by wargio** [comment]
@XVilka you need to cherrypick this commit: https://github.com/rizinorg/rizin/commit/e5ad689fc9407ad6f3b53de80c7102c0b1f9d017

**Pull request merged**
