### PR TITLE
removing unnecessary warning

### LINKED ISSUE #3045: OS/2 PE: WARNING: Compressed page not handled: obj.1.page.0
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 36 64 bits
| File format of the file you reverse (mandatory)      | OS/2 PE
| Architecture/bits of the file (mandatory)            | x86/32
| `rizin -v` full output, **not truncated** (mandatory)  |  https://github.com/rizinorg/rizin/commit/4063f7d2def16691622eed7483e6493fb06c652b

### Expected behavior

No warnings

### Actual behavior
```
ℤ rizin ls.exe
WARNING: Compressed page not handled: obj.1.page.1WARNING: Compressed page not handled: obj.1.page.2WARNING: Compressed page not handled: obj.1.page.3WARNING: Compressed page not handled: obj.1.page.4WARNING: Compressed page not handled: obj.1.page.5WARNING: Compressed page not handled: obj.1.page.6WARNING: Compressed page not handled: obj.1.page.7WARNING: Compressed page not handled: obj.1.page.8WARNING: Compressed page not handled: obj.1.page.9WARNING: Compressed page not handled: obj.1.page.10WARNING: Compressed page not handled: obj.1.page.11WARNING: Compressed page not handled: obj.1.page.12WARNING: Compressed page not handled: obj.1.page.13WARNING: Compressed page not handled: obj.1.page.14WARNING: Compressed page not handled: obj.1.page.15WARNING: Compressed page not handled: obj.1.page.16WARNING: Compressed page not handled: obj.1.page.17WARNING: Compressed page not handled: obj.1.page.18WARNING: Compressed page not handled: obj.1.page.19WARNING: Compressed page not handled: obj.1.page.20WARNING: Compressed page not handled: obj.1.page.21WARNING: Compressed page not handled: obj.1.page.22WARNING: Compressed page not handled: obj.1.page.23WARNING: Compressed page not handled: obj.1.page.24WARNING: Compressed page not handled: obj.1.page.25WARNING: Compressed page not handled: obj.1.page.26WARNING: Compressed page not handled: obj.1.page.27WARNING: Compressed page not handled: obj.1.page.28WARNING: Compressed page not handled: obj.1.page.29WARNING: Compressed page not handled: obj.1.page.30WARNING: Compressed page not handled: obj.1.page.31WARNING: Compressed page not handled: obj.1.page.32WARNING: Compressed page not handled: obj.1.page.33WARNING: Compressed page not handled: obj.1.page.34WARNING: Compressed page not handled: obj.1.page.35WARNING: Compressed page not handled: obj.1.page.36WARNING: Compressed page not handled: obj.1.page.37WARNING: Compressed page not handled: obj.1.page.38WARNING: Compressed page not handled: obj.1.page.39WARNING: Compressed page not handled: obj.1.page.40WARNING: Compressed page not handled: obj.1.page.41WARNING: Compressed page not handled: obj.1.page.42WARNING: Compressed page not handled: obj.2.page.0WARNING: Compressed page not handled: obj.1.page.0WARNING: Compressed page not handled: obj.1.page.1WARNING: Compressed page not handled: obj.1.page.2WARNING: Compressed page not handled: obj.1.page.3WARNING: Compressed page not handled: obj.1.page.4WARNING: Compressed page not handled: obj.1.page.5WARNING: Compressed page not handled: obj.1.page.6WARNING: Compressed page not handled: obj.1.page.7WARNING: Compressed page not handled: obj.1.page.8WARNING: Compressed page not handled: obj.1.page.9WARNING: Compressed page not handled: obj.1.page.10WARNING: Compressed page not handled: obj.1.page.11WARNING: Compressed page not handled: obj.1.page.12WARNING: Compressed page not handled: obj.1.page.13WARNING: Compressed page not handled: obj.1.page.14WARNING: Compressed page not handled: obj.1.page.15WARNING: Compressed page not handled: obj.1.page.16WARNING: Compressed page not handled: obj.1.page.17WARNING: Compressed page not handled: obj.1.page.18WARNING: Compressed page not handled: obj.1.page.19WARNING: Compressed page not handled: obj.1.page.20WARNING: Compressed page not handled: obj.1.page.21WARNING: Compressed page not handled: obj.1.page.22WARNING: Compressed page not handled: obj.1.page.23WARNING: Compressed page not handled: obj.1.page.24WARNING: Compressed page not handled: obj.1.page.25WARNING: Compressed page not handled: obj.1.page.26WARNING: Compressed page not handled: obj.1.page.27WARNING: Compressed page not handled: obj.1.page.28WARNING: Compressed page not handled: obj.1.page.29WARNING: Compressed page not handled: obj.1.page.30WARNING: Compressed page not handled: obj.1.page.31WARNING: Compressed page not handled: obj.1.page.32WARNING: Compressed page not handled: obj.1.page.33WARNING: Compressed page not handled: obj.1.page.34WARNING: Compressed page not handled: obj.1.page.35WARNING: Compressed page not handled: obj.1.page.36WARNING: Compressed page not handled: obj.1.page.37WARNING: Compressed page not handled: obj.1.page.38WARNING: Compressed page not handled: obj.1.page.39WARNING: Compressed page not handled: obj.1.page.40WARNING: Compressed page not handled: obj.1.page.41WARNING: Compressed page not handled: obj.1.page.42WARNING: Compressed page not handled: obj.2.page.0WARNING: Compressed page not handled: obj.1.page.0WARNING: Compressed page not handled: obj.1.page.1WARNING: Compressed page not handled: obj.1.page.2WARNING: Compressed page not handled: obj.1.page.3WARNING: Compressed page not handled: obj.1.page.4WARNING: Compressed page not handled: obj.1.page.5WARNING: Compressed page not handled: obj.1.page.6WARNING: Compressed page not handled: obj.1.page.7WARNING: Compressed page not handled: obj.1.page.8WARNING: Compressed page not handled: obj.1.page.9WARNING: Compressed page not handled: obj.1.page.10WARNING: Compressed page not handled: obj.1.page.11WARNING: Compressed page not handled: obj.1.page.12WARNING: Compressed page not handled: obj.1.page.13WARNING: Compressed page not handled: obj.1.page.14WARNING: Compressed page not handled: obj.1.page.15WARNING: Compressed page not handled: obj.1.page.16WARNING: Compressed page not handled: obj.1.page.17WARNING: Compressed page not handled: obj.1.page.18WARNING: Compressed page not handled: obj.1.page.19WARNING: Compressed page not handled: obj.1.page.20WARNING: Compressed page not handled: obj.1.page.21WARNING: Compressed page not handled: obj.1.page.22WARNING: Compressed page not handled: obj.1.page.23WARNING: Compressed page not handled: obj.1.page.24WARNING: Compressed page not handled: obj.1.page.25WARNING: Compressed page not handled: obj.1.page.26WARNING: Compressed page not handled: obj.1.page.27WARNING: Compressed page not handled: obj.1.page.28WARNING: Compressed page not handled: obj.1.page.29WARNING: Compressed page not handled: obj.1.page.30WARNING: Compressed page not handled: obj.1.page.31WARNING: Compressed page not handled: obj.1.page.32WARNING: Compressed page not handled: obj.1.page.33WARNING: Compressed page not handled: obj.1.page.34WARNING: Compressed page not handled: obj.1.page.35WARNING: Compressed page not handled: obj.1.page.36WARNING: Compressed page not handled: obj.1.page.37WARNING: Compressed page not handled: obj.1.page.38WARNING: Compressed page not handled: obj.1.page.39WARNING: Compressed page not handled: obj.1.page.40WARNING: Compressed page not handled: obj.1.page.41WARNING: Compressed page not handled: obj.1.page.42WARNING: Compressed page not handled: obj.2.page.0 -- Use 'e asm.offset=true' to show offsets in 16bit segment addressing mode.
[0x00010000]> 
```

### Steps to reproduce the behavior
- Just open the file `rizin ls.exe`

### Additional Logs, screenshots, source code,  configuration dump, ...

[ls.zip](https://github.com/rizinorg/rizin/files/9634248/ls.zip)

### PR DESCRIPTION
**Pull request by pathefone**
**Your checklist for this pull request**
- [ X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Closing issues**

closes #3045

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
This fix is incorrect.

**Comment by wargio** [comment]
The correct fix would be to implement the decompress part of the code. or if you prefer, add a newline at the end of the warning string

**Comment by pathefone** [comment]
Thank you for guidance, the decompression sounds more interesting and will try my best. However, I'm not even sure what I need to decompress so will take time

**Comment by wargio** [comment]
> Thank you for guidance, the decompression sounds more interesting and will try my best. However, I'm not even sure what I need to decompress so will take time

http://www.oldlinux.org/Linux.old/study/sabre/os/files/Executables/LX.txt

**Comment by pathefone** [comment]
So I have been reading what wargio provided to me, and if I may I want to ask some questions, I really would love to improve myself in this field. So thanks wargio for providing extra info.

How will I check that I correctly decompressed object page table entries? If I understood it correctly what I am supposed to
decompress in the first place.

Also I did not find under "Object Page Table" a Compressed page flag, but in the code there is.
	     00h = Legal Physical Page  in the module (Offset from Preload Page Section).
             01h  = Iterated Data Page (Offset from  Iterated
             Data Pages Section).
             02h = Invalid Page (zero).
             03h = Zero Filled Page (zero).
             04h = Range of Pages.


So I am kind of lost, will I access the entries with RzBinSection, and decompress then, or how. Sorry if my questions seem stupid,
want to learn but I see that on my own I kind of lack some knowledge. Maybe I do not fully comprehend what is a page and difference between object page table, object table.

**Comment by wargio** [comment]
> So I have been reading what wargio provided to me, and if I may I want to ask some questions, I really would love to improve myself in this field. So thanks wargio for providing extra info.
> 
> How will I check that I correctly decompressed object page table entries? If I understood it correctly what I am supposed to decompress in the first place.
> 
> Also I did not find under "Object Page Table" a Compressed page flag, but in the code there is. 00h = Legal Physical Page in the module (Offset from Preload Page Section). 01h = Iterated Data Page (Offset from Iterated Data Pages Section). 02h = Invalid Page (zero). 03h = Zero Filled Page (zero). 04h = Range of Pages.
> 
> So I am kind of lost, will I access the entries with RzBinSection, and decompress then, or how. Sorry if my questions seem stupid, want to learn but I see that on my own I kind of lack some knowledge. Maybe I do not fully comprehend what is a page and difference between object page table, object table.

According to the doc there is no real compression method, just squashed memory space with the entries.
You just need to decode them iteratively based on the bytes you extract at each iteration.

**Comment by XVilka** [comment]
Closing because of no activity.

**Pull request closed without merging**
