### PR TITLE
Add ownership and nullable marks to the string API of RzUtil

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Added `RZ_NONNULL`/`RZ_NULLABLE` and `RZ_OWN`/`RZ_BORROW` where appropriate. Also added checks for NULL with `rz_return_*if_fail()` macroses and added `const` where appropriate.

String API is one of the most used across the Rizin code, it should be polished and documented first.

**Test plan**

CI is green.

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Comment by XVilka** [comment]
Already helped to spot few misuses:
```
[XX] db/formats/mach0/leb128 macho trie malformed uleb128
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc  bins/mach0/macho-trie-bad-export-info-malformed-uleb128
-- stderr
--- expected
+++ actual
@@ -0,3 +0,4 @@
 ERROR: malformed uleb128
 ERROR: malformed uleb128
+WARNING: rz_str_dup: assertion 'string' failed (line 893)

[XX] db/cmd/cmd_pd bin.str.enc error handling
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '(test_str.enc enc; e bin.str.enc=$0; e bin.str.enc)
.(test_str.enc UTF-32LE)
.(test_str.enc cat_sat_on_keyboard)
.(test_str.enc CAT_SAT_ON_KEYBOARD)
' =
-- stderr
--- expected
+++ actual
@@ -1,2 +1,5 @@
+WARNING: rz_str_cmp_list: assertion 'list && item' failed (line 833)
+WARNING: rz_str_cmp_list: assertion 'list && item' failed (line 833)
 Unknown encoding: cat_sat_on_keyboard
+WARNING: rz_str_cmp_list: assertion 'list && item' failed (line 833)
 Unknown encoding: CAT_SAT_ON_KEYBOARD
```

**Comment by ret2libc** [comment]
Please let's not cherry pick this for 0.3.0. I'm afraid there can be many cases we do not cover in tests and that would fail as well.

**Comment by XVilka** [comment]
@ret2libc I was not going to.

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
Closing this due to inactivity (*scolds himself*)

**Pull request closed without merging**
