### PR TITLE
Fix DWARF parsing

### LINKED ISSUE #4121: [Hexagon]  `rz_bin_dwarf_attr_addr: code should not be reached`
Warning thrown for Hexagon binary `v68_scalar` if opened.

```
> rizin test/bins/elf/hexagon/rzil/v68_scalar
WARNING: (../librz/include/rz_bin_dwarf.h:1853):rz_bin_dwarf_attr_addr: code should not be reached
ERROR: Location parse failed 0xea02 <Cannot find loclist>
WARNING: Unsupported opcode (null) 0x0
[0x00020d20]> 
```

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

closes #4121

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
LGTM if @Rot127 approves

**Review by Rot127 — CHANGES_REQUESTED** [review]
LGTM. Please only change the commit message to something more descriptive. Afterwards this can be merged.

**Comment by b1llow** [comment]
> LGTM. Please only change the commit message to something more descriptive. Afterwards this can be merged.

What do you think of the current one? I don't feel good at writing detailed commit descriptions.

**Comment by XVilka** [comment]
@imbillow I suppose something like `DWARF: fix CU attributes parsing and application`

**Pull request merged**
