### PR TITLE
Update capstone-v5 to 5.0.1

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

See https://github.com/capstone-engine/capstone/releases/tag/5.0.1

**Test plan**

CI is green

### CODE REVIEW

**Comment by XVilka** [comment]
@wargio is this new output better for Go binary?
```
[XX] db/analysis/golang Resolve all symbols on a linux go1.16 binary (arm32)
RZ_NOPLUGINS=1 /private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-1287038090/rizinorg/rizin/prefix/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'aalg
fl~sym.go.~?
pdfs @ main ~str.
izq~?
' bins/golang/btcctl-linux-armv7-v0.22.0-beta
-- stdout
--- expected
+++ actual
@@ -47,4 +47,4 @@
 0x0027401c str.btcctl.conf
 0x00274090 str.rpc.cert
 0x00274104 str.rpc.cert
-14056
+14104

-- stderr
[x] Found go 1.16 pclntab data.
[x] Recovered 5124 symbols and saved them at sym.go.*
[x] Analyze all flags starting with sym.go. (aF @@f:sym.go.*)
[x] Recovering go strings from bin maps
[x] Analyze all instructions to recover all strings used in sym.go.*
[x] Recovered 7502 strings from the sym.go.* functions.
```

**Comment by XVilka** [comment]
@imbillow from what I gathered the new output is the correct one, please confirm:
```
[XX] db/analysis/tricore TriCore multi
RZ_NOPLUGINS=1 /private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-1287038090/rizinorg/rizin/prefix/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc '!rz-asm -a tricore -d 0f0200007cb10880f8130200' malloc://512
-- stdout
--- expected
+++ actual
@@ -1,5 +1,5 @@
 sh d0, d2, d0
 jnz.a a11, #6
 ld.bu d0, [a15]#8
-st.a [sp]#0x13, a15
+st.a [sp]#0x4c, a15
 mov d0, d0

[XX] db/analysis/tricore TriCore multi
RZ_NOPLUGINS=1 /private/var/folders/bc/yvvw2g2s4jlg9r8x7tf61xv800009d/T/woodpecker-local-1287038090/rizinorg/rizin/prefix/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc '!rz-asm -a tricore -d 0f0200007cb10880f8130200' malloc://512
-- stdout
--- expected
+++ actual
@@ -1,5 +1,5 @@
 sh d0, d2, d0
 jnz.a a11, #6
 ld.bu d0, [a15]#8
-st.a [sp]#0x13, a15
+st.a [sp]#0x4c, a15
 mov d0, d0
```

**Comment by wargio** [comment]
> @wargio is this new output better for Go binary?

According to the diff, is better.

**Review by b1llow — APPROVED** [review]

**Comment by b1llow** [comment]
LGTM

**Pull request merged**
