### PR TITLE
rz-ax: move str to bin to rz_util

### LINKED ISSUE #2512: move bin -> str to rz_util
Refer [rz-ax.c#L400](https://github.com/rizinorg/rizin/blob/dev/librz/main/rz-ax.c#L400).
Moving this binary to string converter to ``rz_util/rz_str.h`` will help create an ``RZ_API`` which can b reused in other places.

Could probably name it ``rz_bin_to_str()``

### PR DESCRIPTION
**Pull request by DhruvaG2000**
Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

 

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

help create an RZ_API ``rz_str_to_bin( )`` which can be reused in other places
...

**Test plan**

TODO
...

**Closing issues**

closes #2512
...

### CODE REVIEW

**Comment by DhruvaG2000** [comment]
I think there is a more elegant solution possible for this, which would perhaps either be to convert the input string into a binary as it is passed by reference. However this would still essentially be a char string of 0's and 1's. Another idea is to have a second string passed as a parameter that will have the 0's and 1's copied to it.

Let me know if this PR as of [29bb1e2] is enough or I should implement what I have just discussed above and which approach of the 2.

**Comment by wargio** [comment]
to be fair, i do not see any reason for which that function should go on rz_util (the comment was set in this commit https://github.com/rizinorg/rizin/commit/82416b021239286833c2336dddcb3ac6d1dab165).
I would just delete the comment and keep it inside rz-ax since it is used only there.
Moving it under rz_util means that that printf needs to be replaced with a RzStrBuf and the function will need to return a buffer which will need to be freed afterwards.

so, for me i vote to just remove the line https://github.com/rizinorg/rizin/pull/2533/files#diff-e3a3e294ca71005889c57c12639ffb403ed92e6da1a6eb753b4f3d6ee533d377L400 and keep it in rz-ax

@XVilka @thestr4ng3r ?

**Comment by XVilka** [comment]
Agree with @wargio

**Comment by DhruvaG2000** [comment]
Closing this PR and doing this small tiny change in https://github.com/rizinorg/rizin/pull/2513 itself: 
29ac83f31620833d9d59d7c33776294fa8df6447

**Pull request closed without merging**
