### PR TITLE
attempt to improve distinction b/w ios and macbook m1

### PR DESCRIPTION
**Pull request by devnexen**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)

### CODE REVIEW

**Comment by wargio** [comment]
have you tried to build rizin for ios ?

**Comment by XVilka** [comment]
Instead of adding more and more `ifdef`-s, it's preferable to check the availability of certain functions or features through the buildsystem:
- https://github.com/rizinorg/rizin/issues/1261

**Comment by devnexen** [comment]
> have you tried to build rizin for ios ?

It s detected as ios in this case with this branch.

**Comment by devnexen** [comment]
> Instead of adding more and more `ifdef`-s, it's preferable to check the availability of certain functions or features through the buildsystem:
> 
> * [Migrate function checks from headers to Meson #1261](https://github.com/rizinorg/rizin/issues/1261)

in cmake it is doable regarding this case but with meson I do not find equivalent for ... any pointer ?

**Comment by XVilka** [comment]
>     * Meson

It is in the issue:
`meson.build` checks for some functions:
```meson
foreach item : [
    ['arc4random_uniform', '#include <stdlib.h>', []],
    ['explicit_bzero', '#include <string.h>', []],
    ['explicit_memset', '#include <string.h>', []],
    ['clock_nanosleep', '#include <time.h>', []],
    ['clock_gettime', '#include <time.h>', [lrt]],
    ['sigaction', '#include <signal.h>', []],
    ['pipe', '#include <unistd.h>', []],
    ['execv', '#include <unistd.h>', []],
    ['execve', '#include <unistd.h>', []],
    ['execvp', '#include <unistd.h>', []],
    ['execl', '#include <unistd.h>', []],
    ['system', '#include <stdlib.h>', []],
    ['fork', '#include <unistd.h>', []],
    ['pipe2', '#define _GNU_SOURCE\n#include <fcntl.h>\n#include <unistd.h>', []]
  ]
  func = item[0]
  ok = cc.has_function(func, prefix: item[1], dependencies: item[2])
  userconf.set10('HAVE_@0@'.format(func.to_upper()), ok)
endforeach
```

**Comment by devnexen** [comment]
that's the thing, `has_function` does not apply here. with cmake I would use `check_cxx_source_compiles` for example but I do not see something equivalent.

**Comment by XVilka** [comment]
If `cc.has_function` doesn't apply, another approach could be taken, like:
```meson
code = '#include <unistd.h>\nextern char **environ;\nint main() { char **env = environ; }'
have_environ = cc.links(code, name: 'have extern char **environ')
userconf.set10('HAVE_ENVIRON', have_environ)
message('HAVE_ENVIRON: @0@'.format(have_environ))
```

**Comment by XVilka** [comment]
See more at this documentation chapter: https://mesonbuild.com/Compiler-properties.html#compile-and-run-test-application

**Review by XVilka — APPROVED** [review]
LGTM, let's wait for @thestr4ng3r who is the MacOS M1 maintainer in Rizin.

**Comment by ret2libc** [comment]
> Instead of adding more and more `ifdef`-s, it's preferable to check the availability of certain functions or features through the buildsystem:
> - https://github.com/rizinorg/rizin/issues/1261

In theory the define target_os_ios should not even be necessary at some point, because that's just used to see if other functions like system or ptrace shall be used.

**Review by thestr4ng3r — APPROVED** [review]
Confirmed that `IS_IOS` is correctly set to 0 on macOS/M1 and the entire test suite still passes with the `TARGET_OS_IPHONE=0` change.

**Pull request merged**
