### PR TITLE
Fix #3493: Auto-add prefix to `is` symbol name

### LINKED ISSUE #3493: Auto-add prefixes to symbol names
**Is your feature request related to a problem? Please describe.**

Consider the following command sequence:

auto-add-prefix-1

Now I want to seek to `func_X`:

auto-add-prefix-2

Ok...

auto-add-prefix-3

Eh?! (The actual flag name is:)

auto-add-prefix-4

This feels like a somewhat sad state of affairs.

**Describe the solution you'd like**

If _symbolName_ (defined by `is`) is an unknown address, the following prefixes should be tried, in order:

1. `sym.`
2. `loc.`
3. `obj.`
4. ~~`reloc.`~~

**Describe alternatives you've considered**

Adding flags that directly correspond to the symbol names in `is` would clutter up the flag list even more.

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes #3493 by automatically adding either `sym.`, `loc.` or `obj.` to an `is` symbol name.

Note: no demangling support (yet?).

**Test plan**

All builds should be green.

**Closing issues**

Closes #3493.

### CODE REVIEW

**Comment by wargio** [comment]
I like the fact this might make things very simple, but i have an slightly different proposal.
I'm modifying currently RzBin and its output, and i wanted to add the `prefix` in the table as symbol type (or similar) to remove those `imp.XXXXXXX` from the table and have a more clean view.
What would you think about having instead that ?
like 
```
nth paddr      vaddr      bind   type   size lib prefix     name                  
----------------------------------------------------------------------------------
8   ---------- 0x00600b30 GLOBAL OBJ    8        obj.       stdout
9   ---------- 0x00600b20 GLOBAL OBJ    8        obj.       stdin
1   0x00000200 0x00400200 LOCAL  SECT   0        section.   .interp
2   0x0000021c 0x0040021c LOCAL  SECT   0        section.   .note.ABI-tag
3   0x0000023c 0x0040023c LOCAL  SECT   0        section.   .note.gnu.build-id
68  0x000006a4 0x004006a4 GLOBAL FUNC   127                 main
69  0x00000530 0x00400530 GLOBAL FUNC   0        sym.       _init
1   0x00000558 0x00400558 GLOBAL FUNC   16       imp.       printf
2   ---------- ---------- WEAK   NOTYPE 0        imp.       __gmon_start__
3   0x00000568 0x00400568 GLOBAL FUNC   16       imp.       puts
4   0x00000578 0x00400578 GLOBAL FUNC   16       imp.       __libc_start_main
5   0x00000588 0x00400588 GLOBAL FUNC   16       imp.       fgets
6   0x00000598 0x00400598 GLOBAL FUNC   16       imp.       strcmp
7   0x000005a8 0x004005a8 GLOBAL FUNC   16       imp.       fflush
```

**Comment by kazarmy** [comment]
I like it. It sounds far less complicated to implement and would work well with current autocomplete.

**Comment by kazarmy** [comment]
Also, the flag name for `printf` above is not `imp.printf`, it's `sym.imp.printf` i.e. a double prefix.

**Comment by kazarmy** [comment]
> I like it. It sounds far less complicated to implement and would work well with current autocomplete.

Also, the table provides more info at a glance.

**Comment by kazarmy** [comment]
Hmm I suppose the `bind` and `type` columns do provide sufficient information to infer the prefix.

**Comment by wargio** [comment]
> Also, the flag name for `printf` above is not `imp.printf`, it's `sym.imp.printf` i.e. a double prefix.

mine was a mockup.

**Comment by ret2libc** [comment]
I'm worried a new user would not understand that he needs to concatenate the prefix and the name when referencing the symbol . What do you think?

**Comment by wargio** [comment]
makes sense, but then with this code, i have 2 symbols with the same name but one is obj and the other one is sym the code might jump to the wrong one

**Pull request closed without merging**
