### PR TITLE
debug: generate core dump for FreeBSD.

### PR DESCRIPTION
**Pull request by devnexen**
from the 14.x (next) release, since the snapshot update, interface is available
 and allows enough flexibility thus here we re trying to dump data as much
 as possible.

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)

### CODE REVIEW

**Comment by XVilka** [comment]
Please fix `clang-format`:
```
Ubuntu clang-format version 11.0.0-2~ubuntu20.04.1
librz/debug/p/native/bsd/bsd_debug.c:127:31: error: code should be clang-formatted [-Wclang-format-violations]
        struct ptrace_coredump pc = {.pc_fd = dest->fd, .pc_flags = PC_ALL, .pc_limit = 0};
                                     ^
librz/debug/p/native/bsd/bsd_debug.c:127:83: error: code should be clang-formatted [-Wclang-format-violations]
        struct ptrace_coredump pc = {.pc_fd = dest->fd, .pc_flags = PC_ALL, .pc_limit = 0};
                                                                                         ^
```

**Review by XVilka — APPROVED** [review]
Not sure about `--allow-shlib-undefined` option though. Why it was needed?

**Comment by devnexen** [comment]
not needed for releases versions however for the snapshots I got little undefined __progname symbol.

**Comment by wargio** [comment]
> Not sure about `--allow-shlib-undefined` option though. Why it was needed?

it is needed since __progname is available only when you define the main.
@devnexen can you try to build on FreeBSD without `add_project_link_arguments('-Wl,--unresolved-symbols,ignore-in-object-files', language: 'c')` ?

**Review by yossizap — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Thanks!

**Pull request merged**
