### PR TITLE
Change io len parameter type to size_t

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Change `len` parameter type to `ut64`.

**Test plan**

All green

**Closing issues**

...

### CODE REVIEW

**Comment by Rot127** [comment]
Though the whole module uses `int` for `len`. We should possibly change that with https://github.com/rizinorg/rizin/issues/2695?notification_referrer_id=NT_kwDOArpJ-LMzODA3NjA1NTgyOjQ1NzYzMDY0#issuecomment-1814497959

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
maybe it should be `size_t` or `ssize_t`

**Review by XVilka — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
But it probably makes sense to use `size_t` then for all `rz_io_read_at()`, `rz_io_write_at()`, `rz_io_read_at_mapped()`, etc, just like @thestr4ng3r pointed out, since it can't be bigger than the length of the buffer (we should also note that in the Doxygen documentation).

**Comment by Rot127** [comment]
Most of the len parameters there use `int`. Should I attempt to change this PR to change all of them to `size_t`?

**Comment by wargio** [comment]
maybe. hopefully it won't break too much the code.

**Comment by Rot127** [comment]
Surprisingly it seems to work. Should I send it from `dist-` just to be sure?

**Comment by Rot127** [comment]
Superseded by https://github.com/rizinorg/rizin/pull/4012

**Pull request closed without merging**
