### PR TITLE
Add UTC timezone to timestamps

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR makes timestamps to be self-contained i.e. they do not need external information (which may not be available) to make them complete.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
I think you should use the `_r` versions of most of those functions. Anyway, the idea LGTM.

**Comment by kazarmy** [comment]
The `_r` versions aren't ANSI C89 but due to multithreading issues the change to them will be made, hopefully soon.

**Comment by kazarmy** [comment]
> I think you should use the `_r` versions of most of those functions.

Ok d0086699c04f8bb89534255b8e151b40e3ddd5b3

**Review by XVilka — DISMISSED** [review]
Looks good, but could you please use `dist-` branch instead to trigger more CI workers?

**Review by wargio — APPROVED** [review]

**Comment by kazarmy** [comment]
> Looks good, but could you please use `dist-` branch instead to trigger more CI workers?

The major `dist` builds of 784be1d70264e6732d2d8bfce090939f8d330e77 are green.

**Pull request merged**
