### PR TITLE
Remove sys/clang-format-diff.py

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

As suggested by https://github.com/rizinorg/rizin/pull/422#issuecomment-764727888, this pr removes `sys/clang-format-diff.py`. Devs should instead use git-clang-format 11 like the following to fix format violations:
```bash
git-clang-format-11 --extensions c,cpp,h,hpp,inc --style file dev
```

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Please update also developers.md

**Comment by kazarmy** [comment]
ok b535b40665f6bf7cee85cfa1f3651aba1023c9ce

**Comment by ret2libc** [comment]
About DEVELOPERS.md... I think it was not updated after switching to clang-format.

**Review by XVilka — APPROVED** [review]

**Comment by kazarmy** [comment]
> About DEVELOPERS.md... I think it was not updated after switching to clang-format.

I'll go through the items one-by-one and remove them if possible.

**Pull request merged**
