### PR TITLE
librz: syscalls in Linux 6.5.3

### PR DESCRIPTION
**Pull request by nyoxi**
Update Linux syscalls list to those of Linux 6.5.3 for x86 and aarch64.

 

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [X] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Patch updates list of Linux syscalls to those available in Linux 6.5.3. Only x86 and arm64 are updated as I don't have any arm32 machine to verify with.

**Test plan**

I don't think there are any relevant tests to update.

**Closing issues**

None.

### CODE REVIEW

**Comment by ret2libc** [comment]
Do we have any script to update these files?
@nyoxi how did you update them?

**Comment by nyoxi** [comment]
It also crossed my mind that having a script for that would be nice, but that's not so trivial. Perhaps also a test that ensures consistency of argument counts between architectures.

The syscall numbers come from kernel source code, specifically:
* x86 32bit: `./arch/x86/entry/syscalls/syscall_32.tbl`
* x86 64bit: `./arch/x86/entry/syscalls/syscall_64.tbl`
* arm64: `./tools/include/uapi/asm-generic/unistd.h` although you want to check also the `__ARCH_WANT_*` in `tools/arch/arm64/include/uapi/asm/unistd.h` to know which syscalls are defined.

As for the ones I did not update, arm32 is most likely `arch/arm/tools/syscall.tbl` but I cannot verify that at the moment. Mips and sparc I didn't check at all.

**Comment by nyoxi** [comment]
Hi, is this waiting for anything?

**Review by wargio — APPROVED** [review]
probably was lost. lgtm.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@nyoxi thanks for the PR, and sorry for the delay.

**Pull request merged**
