### PR TITLE
Add fast OpenBSD build

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr continues #1991 by adding a fast OpenBSD build for the possibility that it is actually `MALLOC_OPTIONS=S` that is somehow keeping the current OpenBSD build green.

**Test plan**

All OpenBSD builds are green, and remain green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Please rename the file to `openbsd_fast` instead.

**Comment by kazarmy** [comment]
Ok 639505aff9002b3ca819f7d34726ec88a1389e6d

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]
ok!

**Comment by kazarmy** [comment]
thanks!

**Pull request merged**
