### PR TITLE
Dalvik disassembly should not throw error for single opcode

### LINKED ISSUE #3254: The return-void instructions are parsed as invalid.
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Ubuntu 22.04
| File format of the file you reverse (mandatory)      | APK
| Architecture/bits of the file (mandatory)            | Dalvik
| `rizin -v` full output, **not truncated** (mandatory)  | rizin 0.5.0 @ darwin-x86-64, commit: 1165b20ee73c7c048aefcd2ac3106a5d31a75a78

### Expected behavior

Rizin analyzes the return-void instructions without error.

### Actual behavior

When analyzing an [APK](https://github.com/quark-engine/apk-malware-samples/blob/master/14d9f1a92dd984d6040cc41ed06e273e.apk)(SHA1: 42b25b60aa7d6d9f0b388c10a45e8a8f8c1fc718), Rizin parses the return-void instructions as invalid.

Take address **549755814278** as an example. 
After I run `aaaa` command, `pd` command returns a return-void instruction but `pdfj` returns an invalid instruction.

```bash
[0x10001122c]> pd 1 @ 549755814278
            ; CALL XREF from sym.Lcom_google_progress_AndroidClientService_1_.onCallStateChanged_ILjava_lang_String__V @ +0xc2c
            ;-- sym.Lcom_android_internal_telephony_ITelephony_.answerRingingCall__V:
┌ method.public.abstract.Lcom_android_internal_telephony_ITelephony_.answerRingingCall__V ();
│ bp: 0 (vars 0, args 0)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
└           0x8000000186      return-void


[0x10001122c]> pdfj @ 549755814278

{
    "name":"method.public.abstract.Lcom_android_internal_telephony_ITelephony_.answerRingingCall__V",
    "size":2,
    "addr":549755814278,
    "ops":[
        {
            "offset":549755814278,
            "size":1,
            "bytes":"0e00",
            "opcode":"invalid"
        },
        {
            "offset":549755814279,
            "size":1,
            "bytes":"00",
            "opcode":"invalid"
        }
    ]
}
```

I also found the error occurs in a variety of samples. For instance, it  occurs at address **549755817758** in the [APK sample](https://github.com/quark-engine/apk-malware-samples/blob/master/13667fe3b0ad496a0cd157f34b7e0c991d72a4db.apk)(SHA1: 13667fe3b0ad496a0cd157f34b7e0c991d72a4db).

```bash
[0x100028498]> pd 1 @ 549755817758
            ; CALL XREF from method.public.Landroid_support_v4_util_LongSparseArray_.clone__Landroid_support_v4_util_LongSparseArray @ 0x1000349be
            ; CALL XREF from method.public.Landroid_support_v4_util_SparseArrayCompat_.clone__Landroid_support_v4_util_SparseArrayCompat @ 0x100036fbe
┌ sym._Ljava_lang_Object_.clone__Ljava_lang_Object ();
│ bp: 0 (vars 0, args 0)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
└           0x8000000f1e      return-void


[0x100028498]> pdfj @ 549755817758

{
    "name":"sym._Ljava_lang_Object_.clone__Ljava_lang_Object",
    "size":2,
    "addr":549755817758,
    "ops":[
        {
            "offset":549755817758,
            "size":1,
            "bytes":"0e00",
            "opcode":"invalid"
        },
        {
            "offset":549755817759,
            "size":1,
            "bytes":"00",
            "opcode":"invalid"
        }
    ]
}
```

### Steps to reproduce the behavior
You may get the APK [here](https://github.com/quark-engine/apk-malware-samples/blob/master/14d9f1a92dd984d6040cc41ed06e273e.apk) and analyze it as follows.

    
```bash
$ rizin apk://14d9f1a92dd984d6040cc41ed06e273e.apk

[0x10001122c]> aaaa
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls
[x] Analyze len bytes of instructions for references
[x] Check for classes
[x] Finding xrefs in noncode section with analysis.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x10000f8ec to 0x100054714 (aav)
[x] 0x10000f8ec-0x100054714 in 0x10000f8ec-0x100054714 (aav)
[x] 0x10000f8ec-0x100054714 in 0x8000000000-0x800000079a (aav)
[x] Value from 0x8000000000 to 0x800000079a (aav)
[x] 0x8000000000-0x800000079a in 0x10000f8ec-0x100054714 (aav)
[x] 0x8000000000-0x800000079a in 0x8000000000-0x800000079a (aav)
[x] Emulate functions to find computed references
[x] Analyze local variables and arguments
[x] Applied 0 FLIRT signatures via sigdb
[x] Propagate noreturn information
[x] Resolve pointers to data sections
[x] Finding function preludes
[x] Enable constraint types analysis for variables

[0x10001122c]> pdfj @ 549755814278

{
    "name":"method.public.abstract.Lcom_android_internal_telephony_ITelephony_.answerRingingCall__V",
    "size":2,
    "addr":549755814278,
    "ops":[
        {
            "offset":549755814278,
            "size":1,
            "bytes":"0e00",
            "opcode":"invalid"
        },
        {
            "offset":549755814279,
            "size":1,
            "bytes":"00",
            "opcode":"invalid"
        }
    ]
}

```

Please let me know if anything is unclear.

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Dalvik bytecode disassembler uses `>=` to check if the provided buffer is of appropriate size. Instead it should just use `>`, This allows to disassemble singular opcodes.

**Test plan**

The new integration test should pass ~~(binary added in rizinorg/rizin-testbins#97)~~.

**Closing issues**

Closes #3254.

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
i think this could be triggered using a small basic block and doing a disassemble

**Comment by DMaroo** [comment]
> i think this could be triggered using a small basic block and doing a disassemble

Yeah, I have added the APK used in the original issue. Now there is an integration test for this scenario.

**Comment by wargio** [comment]
what is the license on the original APK?

**Comment by DMaroo** [comment]
Not really sure. The source of the APK is: https://github.com/quark-engine/apk-malware-samples.

**Comment by DMaroo** [comment]
I have opened an issue (quark-engine/apk-malware-samples#1) asking them about the licensing.

**Comment by wargio** [comment]
if it is malware i do not think is an issue. @XVilka @thestr4ng3r @ret2libc what do you think?

**Comment by XVilka** [comment]
No problem with the malware. Can we incapacitate it somehow? Or just use a piece of it.

**Comment by wargio** [comment]
~~tbh, i can't repro this with current dev. @DMaroo what is the exact bug?~~
Reproduced without the apk.
`rizin -a dalvik -qc "wx 0e00 ; af ; pdfj" =`

Can you change the test to execute only these commands?

**Comment by DMaroo** [comment]
I have added the new test without the binary.

**Pull request merged**
