### PR TITLE
Use pre-v5 enum names which are now supported by compatibility macros.

### PR DESCRIPTION
**Pull request by Rot127**
# SQUASH ME

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Supersedes https://github.com/rizinorg/rizin/pull/4690

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Two problems left:
```
cc -Ilibrz/arch/librz_arch.so.0.8.0.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -I../librz/arch/isa -I../librz/arch/isa_gnu -Ilibrz/arch -I../librz/arch -Ilibrz/util/sdb/src -I../librz/util/sdb/src -I../librz/bin/format -I../librz/type/parser -I../subprojects/capstone-next/include -I../subprojects/capstone-next/include/capstone -Isubprojects/rzspp -I../subprojects/rzspp -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -DSUPPORTS_PCRE2_JIT -D_GNU_SOURCE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -Wno-cpp -fPIC -MD -MQ librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o -MF librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o.d -o librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o -c ../librz/arch/isa/arm/arm_il32.c
../librz/arch/isa/arm/arm_il32.c:8:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
    8 | #pragma GCC diagnostic ignored "-Wenum-conversion"
      |                                ^~~~~~~~~~~~~~~~~~~
In file included from ../librz/arch/isa/arm/arm_il32.c:12:
../librz/arch/isa/arm/arm_cs.h:9:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
    9 | #pragma GCC diagnostic ignored "-Wenum-conversion"
      |                                ^~~~~~~~~~~~~~~~~~~
In file included from ../librz/arch/isa/arm/arm_il32.c:13:
../librz/arch/isa/arm/arm_accessors32.h:11:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
   11 | #pragma GCC diagnostic ignored "-Wenum-conversion"
      |                                ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
and 
```
[XX] 250 ms   db/asm/arm_64 <asm> mrs x1, NZCV

-- <asm> mrs x1, NZCV <--- 01423bd5 ---> <IL>

-- IL

--- expected

+++ actual

@@ -1,1 +1,0 @@

-(set x1 (| (ite (var nf) (bv 64 0x80000000) (bv 64 0x0)) (| (ite (var zf) (bv 64 0x40000000) (bv 64 0x0)) (| (ite (var cf) (bv 64 0x20000000) (bv 64 0x0)) (ite (var vf) (bv 64 0x10000000) (bv 64 0x0))))))

-- disasm exit status: 0

-- IL exit status: 1

-- IL stderr

Invalid instruction of lifting not implemented.

[XX] 213 ms   db/asm/arm_64 <asm> msr NZCV, x1

-- <asm> msr NZCV, x1 <--- 01421bd5 ---> <IL>

-- IL

--- expected

+++ actual

@@ -1,1 +1,0 @@

-(seq (set nf (! (is_zero (& (var x1) (bv 64 0x80000000))))) (set zf (! (is_zero (& (var x1) (bv 64 0x40000000))))) (set cf (! (is_zero (& (var x1) (bv 64 0x20000000))))) (set vf (! (is_zero (& (var x1) (bv 64 0x10000000))))))

-- disasm exit status: 0

-- IL exit status: 1

-- IL stderr

Invalid instruction of lifting not implemented.
```

**Comment by Rot127** [comment]
Blind fix, but this is very likely the reason for the endian issue:
https://github.com/capstone-engine/capstone/pull/2528

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
These are still left:
```
../librz/arch/isa/arm/arm_il64.c:7:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
    7 | #pragma GCC diagnostic ignored "-Wenum-conversion"
      |                                ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
[1558/2286] Compiling C object librz/arch/librz_arch.so.0.8.0.p/isa_arm_armass64.c.o
[1559/2286] Compiling C object librz/arch/librz_arch.so.0.8.0.p/isa_arm_armass.c.o
[1560/2286] Compiling C object librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o
FAILED: librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o 
cc -Ilibrz/arch/librz_arch.so.0.8.0.p -I. -I.. -Ilibrz -I../librz -Ilibrz/include -I../librz/include -I../librz/arch/isa -I../librz/arch/isa_gnu -Ilibrz/arch -I../librz/arch -Ilibrz/util/sdb/src -I../librz/util/sdb/src -I../librz/bin/format -I../librz/type/parser -I../subprojects/capstone-next/include -I../subprojects/capstone-next/include/capstone -Isubprojects/rzspp -I../subprojects/rzspp -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Werror -O3 -Wimplicit-fallthrough=3 -DRZ_PLUGIN_INCORE=1 -DSUPPORTS_PCRE2_JIT -D_GNU_SOURCE -DCC_SUPPORTS_W_ENUM_COMPARE --std=gnu99 -Werror=sizeof-pointer-memaccess -fvisibility=hidden -Wno-cpp -fPIC -MD -MQ librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o -MF librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o.d -o librz/arch/librz_arch.so.0.8.0.p/isa_arm_arm_il32.c.o -c ../librz/arch/isa/arm/arm_il32.c
In file included from ../librz/arch/isa/arm/arm_il32.c:19:
../librz/arch/isa/arm/arm_accessors32.h:11:32: error: unknown option after ‘#pragma GCC diagnostic’ kind [-Werror=pragmas]
   11 | #pragma GCC diagnostic ignored "-Wenum-conversion"
      |                                ^~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@Rot127 that PR still didn't help to resolve that endianess issue.

**Comment by Rot127** [comment]
Damn, was hoping I get around building qemu all over again.
Will do it tonight.

**Comment by Rot127** [comment]
https://github.com/capstone-engine/capstone/pull/2530 Sorry, of course I missed the obvious.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
