### PR TITLE
subprojects/zlib: Improve meson.build, emulating configure script

### PR DESCRIPTION
**Pull request by ur4t**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Use `compiler.get_argument_syntax()` instead of `compiler.get_id()` to improve `clang` compatibility.
- Detect headers and define macros to emulate the `configure` script.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
can you describe the specific issue you are having?

**Comment by ur4t** [comment]
> can you describe the specific issue you are having?

When building with the previous `meson.build`, `zconf.h` does not include `unistd.h` at all. So in the previous `meson.build`, `-Wno-implicit-function-declaration` is added to use functions like `write` and `read` which are declared in `unistd.h` and to link against libc.

I used a compiler script with a lot addtional compiler flags which causes Meson's `compiler.get_supported_arguments()` to fail (Meson detects compiler flags with `-Werror,-Wunused-command-line-argument`). Thus meson fails to add `-Wno-implicit-function-declaration` to `compiler_args` and the issue is exposed.

**Review by wargio — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]
I'm ok with the changes as long as https://github.com/rizinorg/rizin/pull/3768 passes :) Thanks!

**Comment by ret2libc** [comment]
dist- tests passed! LGTM

**Comment by XVilka** [comment]
Could you please bump the version too, while you are on it? 

August 18, 2023

Version 1.3 has these key updates from 1.2.13:

- Building using K&R (pre-ANSI) function definitions is no longer supported.
- Fixed a bug in deflateBound() for level 0 and memLevel 9.
- Fixed a bug when gzungetc() is used immediately after gzopen().
- Fixed a bug when using gzflush() with a very small buffer.
- Fixed a crash when gzsetparams() is attempted for a transparent write.
- Fixed test/example.c to work with FORCE_STORED.
- Fixed minizip to allow it to open an empty zip file.
- Fixed reading disk number start on zip64 files in minizip.
- Fixed a logic error in minizip argument processing.

**Comment by ur4t** [comment]
> Could you please bump the version too, while you are on it?

@XVilka Zlib in rizin is now updated to 1.3, but `zlib-1.3.tar.gz` is required to be present in `rizinorg/fallback-repo`. Could you please push the tarball to `rizinorg/fallback-repo`?

**Pull request merged**
