### PR TITLE
Simplify the `container_of` macro

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr simplifies the `container_of` macro for non-msvc compilers.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Please resend this PR from `dist-` branch.

**Comment by XVilka** [comment]
See also https://radek.io/2012/11/10/magical-container_of-macro/

**Review by ret2libc — COMMENTED** [review]
Any idea why it was done that way initially?

**Comment by kazarmy** [comment]
> See also https://radek.io/2012/11/10/magical-container_of-macro/

Hmm you're right ... there is type-checking in the current definition. Apparently it uses a [C99 compound literal expression](https://en.cppreference.com/w/c/language/compound_literal) for that.

**Pull request closed without merging**
