### PR TITLE
Show flag realname too in `fl.t` table output

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Since table is the more verbose, show both "name" and "realname" fields here in case they are different:

```
[0x1000033e4]> f "(🎈️)"
[0x1000033e4]> fl.
0x1000033e4 1 _________
[0x1000033e4]> fl.t
addr        size space name      realname
-------------------------------------------
0x1000033e4 1          _________ _________
[0x1000033e4]> fl.j
[{"name":"_________","size":1,"offset":4294980580}]
```

### CODE REVIEW

**Review by wargio — COMMENTED** [review]
i think we should probably change the function that generates these flags to something else.
Maybe using punycode?

**Comment by XVilka** [comment]
@wargio yes, fine for me as well. But it's for the issue, not this PR

**Comment by wargio** [comment]
i agree. was just a comment.

**Review by wargio — CHANGES_REQUESTED** [review]
add realname also in the json structure.

**Review by wargio — APPROVED** [review]

**Pull request merged**
