### PR TITLE
Few radare2 backports related to RzNum

### PR DESCRIPTION
**Pull request by ret2libc**

### CODE REVIEW

**Comment by XVilka** [comment]
```


[XX] db/cmd/cmd_help "binary shift"
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '"?b 1<<1"
' -
-- stdout
--- expected
+++ actual
@@ -1,1 +1,0 @@
-10b

-- stderr
^D
WARNING: freopen("/dev/tty", "rb", stdin) at ../librz/main/rizin.c:884 failed: No such device or address
WARNING: freopen("/dev/tty", "w", stdout) at ../librz/main/rizin.c:885 failed: No such device or address

-- exit status: 1
[**]                               db/cmd/feat_cmdsubst    11923 OK       880 BR        1 XX       22 FX
[**]                                    db/cmd/cmd_afvd    11924 OK       880 BR        1 XX       22 FX
WARNING: pj_ks: assertion 'j && k && v' failed (line 170)


[XX] db/cmd/cmd_help "comparison operators"
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '"?v 1<1"
"?v 1<2"
"?v 2<1"
"?v 1>1"
"?v 1>2"
"?v 2>1"
' -
-- stdout
--- expected
+++ actual
@@ -1,6 +1,0 @@
-0x0
-0x1
-0x0
-0x0
-0x0
-0x1

-- stderr
^D
WARNING: freopen("/dev/tty", "rb", stdin) at ../librz/main/rizin.c:884 failed: No such device or address
WARNING: freopen("/dev/tty", "w", stdout) at ../librz/main/rizin.c:885 failed: No such device or address

-- exit status: 1


[XX] db/cmd/cmd_help recursive help
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '?* zi
' =
-- stdout
--- expected
+++ actual
@@ -1,3 +1,5 @@
-10b
-10b
-100b
+| zi                   # Show zignatures matching information
+| zij                  # Show zignatures matching information (JSON mode)
+| zi*                  # Show zignatures matching information (rizin mode)
+| ziq                  # Show zignatures matching information (quiet mode)
+| zii <from> <to>      # Show zignatures matching information in range
```

**Comment by ret2libc** [comment]
Should be green now.

**Review by wargio — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
@ret2libc weren't `?b` and `?v` commands converted to a newshell thus requiring use `?b "1<<1"` instead of `"?b 1<<1"`?

**Comment by ret2libc** [comment]
> @ret2libc weren't `?b` and `?v` commands converted to a newshell thus requiring use `?b "1<<1"` instead of `"?b 1<<1"`?

No, `?` is not converted yet.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
