### PR TITLE
Implement RZIL effects: `BLK` and `REPEAT`

### LINKED ISSUE #1918: Implement missing RZIL operation handlers
## Bitvectors
- [x] SLE https://github.com/rizinorg/rizin/pull/2094
- [x] ULE https://github.com/rizinorg/rizin/pull/2094
- [ ] CONCAT (postponed until there is a real need)
- [x] APPEND  https://github.com/rizinorg/rizin/pull/1936
## Effects
- [x] JMP https://github.com/rizinorg/rizin/pull/1924
- [x] BLK https://github.com/rizinorg/rizin/pull/2119
- [x] REPEAT https://github.com/rizinorg/rizin/pull/2119

### PR DESCRIPTION
**Pull request by DMaroo**
# SQUASH ME

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Added implementation for `BLK` and `REPEAT` effects.

**Test plan**

New unit tests for each effect has been added.

~~For the implementation of `REPEAT`, in `rz_il_handler_repeat`, the function "performs" the effects on the provided VM (we need to perform the effects to check the updated value of the condition `c`), and returns `NULL`. I don't think this is appropriate (but this was the simplest solution I found). We could make a copy of the VM in the function and then apply all these effects to the copy to determine how many effects need to be performed, and then we can return a chain of such effects. This, in my opinion, will be better, but might be memory intensive because of copying the `RzILVM` instance. Please give inputs on what I should do.~~

This is fixed now with the help of changes introduced in #2109.

**Closing issues**

Closes #1918.

### CODE REVIEW

**Comment by DMaroo** [comment]
Should I add CONCAT handlers?

**Review by XVilka — APPROVED** [review]

**Comment by DMaroo** [comment]
I know that the test for `repeat` is failing because of invalid memory address. The root of this problem is the following line.

https://github.com/rizinorg/rizin/blob/4f9fe46b349253ee552b596cf87d43c26ca17b01/librz/il/il_vm.c#L478

Backtrace:

```
#0  rz_il_hash_cancel_binding (vm=0x555555562ce0, var=0x555555563dd0) at ../librz/il/il_vm.c:478
#1  0x00007ffff7e92580 in rz_il_set (vm=0x555555562ce0, var_name=0x55555555e447 "leetbap", is_local=false, is_mutable=true, val=0x555555564230) at ../librz/il/theory_effect.c:92
#2  0x00007ffff7e926bd in rz_il_handler_set (vm=0x555555562ce0, op=0x555555563c20) at ../librz/il/theory_effect.c:112
#3  0x00007ffff7e9d553 in eval_effect (vm=0x555555562ce0, op=0x555555563c20) at ../librz/il/il_vm_eval.c:251
#4  0x00007ffff7e9d8f7 in rz_il_evaluate_effect (vm=0x555555562ce0, op=0x555555563c20) at ../librz/il/il_vm_eval.c:343
#5  0x00007ffff7e92b5e in rz_il_handler_repeat (vm=0x555555562ce0, op=0x5555555641c0) at ../librz/il/theory_effect.c:187
#6  0x00007ffff7e9d553 in eval_effect (vm=0x555555562ce0, op=0x5555555641c0) at ../librz/il/il_vm_eval.c:251
#7  0x00007ffff7e9d8f7 in rz_il_evaluate_effect (vm=0x555555562ce0, op=0x5555555641c0) at ../librz/il/il_vm_eval.c:343
#8  0x000055555555b1e7 in test_rzil_vm_op_repeat () at ../test/unit/test_il_vm.c:367
#9  0x000055555555d302 in all_tests () at ../test/unit/test_il_vm.c:543
#10 0x000055555555d540 in main (argc=1, argv=0x7fffffffbea8) at ../test/unit/test_il_vm.c:553
```

This removes the global variable's value from the bag, but the rest of the code keeps on reusing the value corresponding to the old hash, and therefore invalid access of memory.

How should I fix this?

**Comment by XVilka** [comment]
```
test_rzil_vm_op_repeat ERR
[XX] Fail at line 374: bitv not correct: expected 0, got 1.
```

**Review by XVilka — APPROVED** [review]
@thestr4ng3r, @wargio  take a look please, if you are OK - lets merge this.

**Comment by DMaroo** [comment]
Yes. I have done all that I had to. Now this is ready to be reviewed and approved.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Review by thestr4ng3r — APPROVED** [review]

**Comment by wargio** [comment]
Great job @DMaroo

**Pull request merged**
