### PR TITLE
Install rz-ghidra in base docker image

### PR DESCRIPTION
**Pull request by fangxlmr**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR modifies Dockerfile to install rz-ghidra system widely in base image by default.

Decompiler plugin (i.e. RzGhidra) is so basic that it's reasonable to have it installed in base docker image.

**Test plan**

All tests pass

**Closing issues**

#1011

### CODE REVIEW

**Comment by XVilka** [comment]
Looks like CI takes the secrets from the forked repo, not this one cc @ret2libc

**Comment by fangxlmr** [comment]
I added personal token to the forked repo. Need to re-run the CI. @XVilka

**Comment by XVilka** [comment]
Looks like it didn't help.

**Comment by fangxlmr** [comment]
@XVilka @ret2libc Done in my private Action. And here is the link - https://hub.docker.com/r/fangxlmr/rizin

**Comment by fangxlmr** [comment]
CI jobs failed on this PR since it failed to login DockerHub due to secrets issue. This PR has already moved to #1034 in which commits will be merged from branch in rizinorg instead of mine.

**Pull request closed without merging**
