### PR TITLE
Rz testsuite expand

### LINKED ISSUE #114: Expand the testsuite
Current rizin testsuite is not extensive in regard to different compilers, optimization options, formats and programming languages. We need to expand it to cover more cases, platforms, ABIs, operating systems. Here are a few example where we can import some tests from:
- https://github.com/BinaryAnalysisPlatform/bap-testsuite
- https://github.com/LL-MM/approxis-groundtruth
- https://github.com/junxzm1990/x86-sok/tree/master/testsuite ([explanation paper](https://arxiv.org/ftp/arxiv/papers/2007/2007.14266.pdf))
- https://github.com/cmu-sei/pharos/tree/master/tests
- https://github.com/radareorg/radeco-regressions

### PR DESCRIPTION
**Pull request by Heersin**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr is aimed at fixing issue #114 - expand the testsuite. A new directory named `abi` will be created under /test/db/ for testing bins generated by different compilers and compiler options, different platforms and different languages

**Test status**

Pass `rz-test` in my local environment, and they catched some bugs

**Closing issues**

close #114

### CODE REVIEW

**Comment by Heersin** [comment]
Seems like parts of the main signatures have been fixed. I will fix them and update.

**Comment by Heersin** [comment]
Comments for related pr: 
- Permits in the section output was fixed by [#857] 
```
[XX] db/abi/platforms/sections MAIN_ABI : i686-w64-mingw32  sections
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'iS~tls
' bins/abi_bins/pe/platforms/i686-w64-mingw32-echo
-- stdout
@@ -1 +1 @@
-6   0x00002e00   0x200 0x00408000  0x1000 -rw- .tls           CNT_INITIALIZED_DATA,ALIGN_4BYTES,MEM_READ,MEM_WRITE
+6   0x00002e00   0x200 0x00408000  0x1000 -rw- .tls           CNT_INITIALIZED_DATA,ALIGN_4BYTES
```
- dwarf info changed in #869 #870
- main signature
  @XVilka I build rizin (48e899d08adf5cb7ce6e662806faf2e1151355b2) again and can't reproduce the result appeared in the test. 
```
RZ_NOPLUGINS=1 ./rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -A -Qc 'e scr.utf8=false
s main
pdf~main
' ~/Workspace/mine/rizin-testbins/abi_bins/elf/platforms/arm-linux-androideabi-echo 
/ main ();
...
```

but in rizin (rizin 0.1.0 4ac005d4894ac5f13b007784aad4d6147ebf1296 from my distribution repo) it has the following output , which is the expect correct output for signature.
```
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -A -Qc 'e scr.utf8=false  
s main
pdf~main
' ~/Workspace/mine/rizin-testbins/abi_bins/elf/platforms/arm-linux-androideabi-echo
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Finding xrefs in noncode section with analysis.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00008000 to 0x00008a28 (aav)
[x] 0x00008000-0x00008a28 in 0x8000-0x8a28 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
/ 632: int main (int argc, char **argv);
...
```
Is there any config variables I need to enable/disabled ?

If not, then one possible reason is I build rizin using `sys_capstone`(4.0.2-3) and `sys_tree_sitter` (for bad network to download latest) ?

**Comment by XVilka** [comment]
@Heersin yes, feel free to update tests that were fixed.
Regarding capstone - of course it can affect the results.
If you don't know the exact reason of failure, you could mark test as broken meanwhile and open a separate issue so this PR can be green to merge, and we can fix that problem later.

Regarding config variables used in `rz-test` runs you can see its sources: https://github.com/rizinorg/rizin/blob/dev/binrz/rz-test/run.c#L92

**Comment by ret2libc** [comment]
How are you getting the right results for each test? Are you using any particular tool or you verify each of them manually?

**Comment by Heersin** [comment]
> How are you getting the right results for each test? Are you using any particular tool or you verify each of them manually?

Yes, but not all.
for `entries` and `main signature` tests I used `ghidra` , `IDA` and `BAP`'s output  to verify them.
Regarding the `sections` I used `readelf` to verify them.
`languages` are compiled from source file, so I can verify their source language
for `dyn_symbol`, I use the result of BAP and x86-sok as ground truth, but only choose the `print` function families for verifying.

You reminded me there are two uncertain things :
`flagspaces` test aims at verifying whether rizin can recognize some functions from this binary, and the ability of different tools to detect functions is different, depends on their analysis strategies.
and `dwarf info`, I don't know for sure what debug info of dwarf get used in rizin. So I only checked whether rizn can load and parse it, not its correctness.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Pull request merged**
