### PR TITLE
Move the conditional skip for ci.yml

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ghost** [comment]
2021-02-14-215518_585x163_scrot
2021-02-14-215550_506x365_scrot

I just used the matrix.enable variable to disable the job after the name generation.

**Comment by ghost** [comment]
If failing before the jobs generations:
2021-02-14-215857_236x25_scrot

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Can we merge this @08A ?

**Comment by ghost** [comment]
> Can we merge this @08A ?

yes

**Pull request merged**
