### PR TITLE
sys/clang-format.py: Require clang-format 11

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr makes `sys/clang.format.py` check whether clang-format is version 11. Ubuntu 20.04 installs clang-format 10 by default which formats code differently even with the same `.clang-format`.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Do you have examples of such differences?

**Comment by ret2libc** [comment]
Oh, nice catch. Yeah also on Fedora 32 I got some differences while doing `sys/clang-format.py`.

```diff
diff --git a/librz/analysis/p/analysis_x86_cs.c b/librz/analysis/p/analysis_x86_cs.c
index c1ffb5ddf3..854747f388 100644
--- a/librz/analysis/p/analysis_x86_cs.c
+++ b/librz/analysis/p/analysis_x86_cs.c
@@ -378,14 +378,10 @@ static const char *reg32_to_name(ut8 reg) {
 
 static void anop_esil(RzAnalysis *a, RzAnalysisOp *op, ut64 addr, const ut8 *buf, int len, csh *handle, cs_insn *insn) {
        int rs = a->bits / 8;
-       const char *pc = (a->bits == 16) ? "ip" : (a->bits == 32) ? "eip"
-                                                                 : "rip";
-       const char *sp = (a->bits == 16) ? "sp" : (a->bits == 32) ? "esp"
-                                                                 : "rsp";
-       const char *bp = (a->bits == 16) ? "bp" : (a->bits == 32) ? "ebp"
-                                                                 : "rbp";
-       const char *si = (a->bits == 16) ? "si" : (a->bits == 32) ? "esi"
-                                                                 : "rsi";
+       const char *pc = (a->bits == 16) ? "ip" : (a->bits == 32) ? "eip" : "rip";
+       const char *sp = (a->bits == 16) ? "sp" : (a->bits == 32) ? "esp" : "rsp";
+       const char *bp = (a->bits == 16) ? "bp" : (a->bits == 32) ? "ebp" : "rbp";
+       const char *si = (a->bits == 16) ? "si" : (a->bits == 32) ? "esi" : "rsi";
```

```
diff --git a/librz/analysis/p/analysis_xtensa.c b/librz/analysis/p/analysis_xtensa.c
index f5f6d38c4d..a42f44ecb0 100644
--- a/librz/analysis/p/analysis_xtensa.c
+++ b/librz/analysis/p/analysis_xtensa.c
@@ -773,10 +773,10 @@ static void esil_load_imm(xtensa_isa isa, xtensa_opcode opcode, xtensa_format fo
        //                      = // assign to data reg
 
        ut8 data_size = opcode == 82 ? 2 // l16ui
-               : opcode == 83       ? 2 // l16si
-               : opcode == 84       ? 4 // l32i
-               : opcode == 31       ? 4 // l32i.n
-                                    : 1; // opcode == 86 ? 1 : 1; // l8ui
+                                    : opcode == 83 ? 2 // l16si
+                                                   : opcode == 84 ? 4 // l32i
+                                                                  : opcode == 31 ? 4 // l32i.n
+                                                                                 : 1; // opcode == 86 ? 1 : 1; // l8ui
 
```

```
diff --git a/librz/asm/arch/include/mybfd.h b/librz/asm/arch/include/mybfd.h
index 87f7828d2a..4d631a3939 100644
--- a/librz/asm/arch/include/mybfd.h
+++ b/librz/asm/arch/include/mybfd.h
@@ -921,18 +921,18 @@ bfd_boolean bfd_fill_in_gnu_debuglink_section(bfd *abfd, struct bfd_section *sec
        BFD_SEND(abfd, bfd_getx_signed_64, (ptr))
 
 #define bfd_get(bits, abfd, ptr) \
-       ((bits) == 8                   ? (bfd_vma)bfd_get_8(abfd, ptr) \
-                       : (bits) == 16 ? bfd_get_16(abfd, ptr) \
-                       : (bits) == 32 ? bfd_get_32(abfd, ptr) \
-                       : (bits) == 64 ? bfd_get_64(abfd, ptr) \
-                                      : (abort(), (bfd_vma)-1))
+       ((bits) == 8 ? (bfd_vma)bfd_get_8(abfd, ptr) \
+                    : (bits) == 16 ? bfd_get_16(abfd, ptr) \
+                                   : (bits) == 32 ? bfd_get_32(abfd, ptr) \
+                                                  : (bits) == 64 ? bfd_get_64(abfd, ptr) \
+                                                                 : (abort(), (bfd_vma)-1))
 
```

```
static bool listOpDescriptions(void *_core, const char *k, const char *v) {
@@ -2077,10 +2074,10 @@ static void core_analysis_bytes(RzCore *core, const ut8 *buf, int len, int nops,
                        }
                        if (op.direction != 0) {
                                const char *dir = op.direction == 1 ? "read"
-                                       : op.direction == 2         ? "write"
-                                       : op.direction == 4         ? "exec"
-                                       : op.direction == 8         ? "ref"
-                                                                   : "none";
+                                                                   : op.direction == 2 ? "write"
+                                                                                       : op.direction == 4 ? "exec"
+                                                                                                           : op.direction == 8 ? "ref"
+                                                                                                                               : "none";

```

These are just some.

**Comment by ret2libc** [comment]
Instead of *requiring* clang-format v11, I would prefer to make it work with v10 as well. I think many distros still provide that and it would avoid a lot of troubles to other devs.

**Comment by kazarmy** [comment]
> Do you have examples of such differences?

Also "`clang-format-10 -style=file -i librz/core/cmd_analysis.c`":

clang-format-10

**Comment by kazarmy** [comment]
> Instead of _requiring_ clang-format v11, I would prefer to make it work with v10 as well.

That might not be possible https://reviews.llvm.org/D50078#2056761

**Comment by XVilka** [comment]
We can just run predetermined version of `clang-format` on CI and stick to that.

**Comment by kazarmy** [comment]
I would still like this pr to be merged because I don't want to edit `sys/clang-format.py` every time I run it.

**Comment by ret2libc** [comment]
Yeah. I'd vote for clang-10 for now, but no strong objection either way.

**Comment by kazarmy** [comment]
I'd vote for the clang-format-11 requirement since devs should be able to download and use the latest-and-greatest stable version of clang-format, and if not, we can just do formatting post facto ... but we don't want accidental formatting using clang-format-10 as much as possible.

One can also explore code constructs that format the same under both 10 and 11 (e.g. using switch or if statements instead of ternary operators) but it's a lot of code to change and it's going to be low-prio.

**Comment by kazarmy** [comment]
> We can just run predetermined version of clang-format on CI and stick to that.

I think you need to run clang-format _before_ CI.

**Comment by kazarmy** [comment]
Now that I know about `update-alternatives` i.e.
```bash
sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-11 110 --slave /usr/bin/clang-format-diff clang-format-diff /usr/bin/clang-format-diff-11 --slave /usr/bin/git-clang-format git-clang-format /usr/bin/git-clang-format-11 --slave /usr/share/man/man1/clang-format.1.gz clang-format.1.gz /usr/share/man/man1/clang-format-11.1.gz --slave /usr/share/man/man1/clang-format-diff.1.gz clang-format-diff.1.gz /usr/share/man/man1/clang-format-diff-11.1.gz --slave /usr/share/man/man1/git-clang-format.1.gz git-clang-format.1.gz /usr/share/man/man1/git-clang-format-11.1.gz
```

this pr has become less critical to me so I'm going to close it. Still, I think that devs should be informed that they should use clang-format 11.

**Pull request closed without merging**
