### PR TITLE
Fix "att pa" test on asan

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

This pr fixes the following "att pa" test on asan (https://github.com/rizinorg/rizin/runs/1563760310#step:17:123):

att pa

It does so by allowing the following lines of code:

https://github.com/rizinorg/rizin/blob/4a6627929142627fdd55a56ce9abafa6565f9c22/librz/core/cconfig.c#L631-L638

to work as they should.

**Test plan**

All builds are green, including the asan build.

**Closing issues**

...

### CODE REVIEW

**Comment by kazarmy** [comment]
Drafting because the comment is wrong.

**Comment by kazarmy** [comment]
It was https://github.com/rizinorg/rizin/blob/4a6627929142627fdd55a56ce9abafa6565f9c22/librz/core/cconfig.c#L638-L641 that was setting `analysis.arch` to `null` in the absence of an analysis plugin for `asm.arch`.

**Comment by kazarmy** [comment]
Updated https://github.com/rizinorg/rizin/pull/202#issue-541192810.

**Review by wargio — APPROVED** [review]
Nice.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
