### PR TITLE
Remove binrz/preload

### PR DESCRIPTION
**Pull request by thestr4ng3r**
This is not used at all.

### CODE REVIEW

**Comment by ret2libc** [comment]
Could it be used by rz-run preload ?

**Comment by ret2libc** [comment]
```
librz/io/p/io_self.c:   // !!! may die if not running from r2preload !!! //
```

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
We could remove `self://` as well, @ret2libc  ;)

**Comment by thestr4ng3r** [comment]
> Could it be used by rz-run preload ?

No, rz-run preload is for setting things like `LD_PRELOAD` on a child.

> We could remove `self://` as well, @ret2libc  ;)

Actually I would move that to an external plugin. It's completely useless but fun.

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
