### PR TITLE
Transition of strings in RzBinPlugin (from list to pvector)

### PR DESCRIPTION
**Pull request by PeiweiHu**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

CI is green.

**Closing issues**

partially address https://github.com/rizinorg/rizin/issues/3775

### CODE REVIEW

**Comment by wargio** [comment]
looks like you broke something in the string part.

**Comment by PeiweiHu** [comment]
> looks like you broke something in the string part.

Thank you. I will fix it later.

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
Please modify `rz_pvector_len` and allow it to accept nullptr and return 0

**Review by XVilka — APPROVED** [review]
Awesome!

**Pull request merged**
