### PR TITLE
Remove TCP_NODELAY

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — COMMENTED** [review]
What is the reason behind this change? 

https://holmeshe.me/network-essentials-setsockopt-TCP_NODELAY/

Is it this?
> Use TCP_QUICKACK, not TCP_NODELAY
>
>Turning on TCP_NODELAY has similar effects, but can make throughput worse for small writes. If you write a loop which sends just a few bytes (worst case, one byte) to a socket with "write()", and the Nagle algorithm is disabled with TCP_NODELAY, each write becomes one IP packet. This increases traffic by a factor of 40, with IP and TCP headers for each payload. Tinygram prevention won't let you send a second packet if you have one in flight, unless you have enough data to fill the maximum sized packet. It accumulates bytes for one round trip time, then sends everything in the queue. That's almost always what you want. If you have TCP_NODELAY set, you need to be much more aware of buffering and flushing issues. None of this matters for bulk one-way transfers, which is most HTTP today. (I've never looked at the impact of this on the SSL handshake, where it might matter.) Short version: set TCP_QUICKACK.

**Comment by XVilka** [comment]
Please use `dist-` branch for such PRs btw, to check all platforms aren't broken.

**Comment by wargio** [comment]
because it is a bad idea. i have a huge amount of fail delivery on my own internal network. let the packages be handled by the OS.
this fixed all the issues i had.

**Comment by wargio** [comment]
https://github.com/rizinorg/rizin/pull/3443

**Pull request closed without merging**
