### PR TITLE
Fix PCRE2 sys build for FreeBSD

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix https://github.com/rizinorg/rizin/pull/4185#issuecomment-1962989769

**Test plan**

Locally tested 

**Closing issues**

...

### CODE REVIEW

**Comment by Rot127** [comment]
@arrowd Added a blind fix with https://github.com/rizinorg/rizin/pull/4307/commits/90c0207fa618a8cd614ca5279339bdde2ec9576e

Couldn't test it yet, because my internet connection is pretty slow at the moment and setting up FreeBSD takes quite long.
So if you are faster, feel free to drop a note here.

**Comment by arrowd** [comment]
Yep, I made the same change locally to fix the build. Thanks!

**Comment by XVilka** [comment]
Please open a new PR from the `rizinorg` account, and with `dist-` branch to trigger everything.

**Comment by Rot127** [comment]
Dist-fuzz build was green in https://github.com/rizinorg/rizin/pull/4310
Only using this for auto-merge

**Review by wargio — APPROVED** [review]

**Pull request merged**
