### PR TITLE
Use the no-pie version (no ASLR) for the test

### PR DESCRIPTION
**Pull request by wargio**
This may fix the annoying mach0 debug test from failing

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by wargio** [comment]
@XVilka can you rebuild the hello example for arm and remove the pie flag while building it?

**Comment by XVilka** [comment]
> @XVilka can you rebuild the hello example for arm and remove the pie flag while building it?

What file exactly do you mean?

**Comment by wargio** [comment]
that file was built with the -pie flag on macos. we need this to be without the ASLR support (https://stackoverflow.com/questions/23897963/documented-way-to-disable-aslr-on-os-x)

**Comment by wargio** [comment]
The binary i have added is broken. i will revert changes on the test repo

**Pull request closed without merging**
