### PR TITLE
Removed TTS

### PR DESCRIPTION
**Pull request by wargio**
# **SQUASH ME**

### CODE REVIEW

**Comment by wargio** [comment]
`    OSError: /usr/lib/librz_core.so: undefined symbol: __sync_fetch_and_add`

**Comment by XVilka** [comment]
@wargio it's this https://github.com/rizinorg/rizin/pull/354#issuecomment-761518588
We can probably disable TinyCC temporarily

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Just remove `?es` completely.

**Comment by Maijin** [comment]
If you remove ?Es you may as well remove all TTS support. I think that should be added later as a module

**Review by XVilka — APPROVED** [review]
It wasn't the right way to improve the accessibility anyway.

**Review by ret2libc — APPROVED** [review]

**Review by Maijin — APPROVED** [review]

**Pull request merged**
