### PR TITLE
Cherry-picks from 6502 Lifting

### PR DESCRIPTION
**Pull request by thestr4ng3r**
# Do not squash.

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Picked from https://github.com/rizinorg/rizin/pull/2100:
* Add tests for 6502 disasm (with a small syntax adjustment)
* Remove 6502.cs because it is unused and unneeded

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
Is 6502.c using capstone? Or our own disassembler?

**Comment by thestr4ng3r** [comment]
Our own disassemblers.

**Comment by ret2libc** [comment]
> Our own disassemblers.

Is it better than capstone one?

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
@ret2libc yes, it is.

**Comment by thestr4ng3r** [comment]
Better than the capstone **plugin**, yes. Asm seems to work after some code fixes, but analysis is quite broken.
Whether it is better than capstone in the sense of disassembling depends on a number of factors, but I don't see a reason why it would be worse, at least for raw 6502.
Keep in mind that this arch is super simple. All you need to disassemble is a table of 256 entries (or less if you don't count illegal ops) and capstone's 6502 support is still not in any release, after multiple years.

**Pull request merged**
