### PR TITLE
Full table header line

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Old behaviour:
```
nth paddr      vaddr      bind   type   size lib name           
―――――――――――――――――――――――――――――――――――――――――――――――――――――                   
118 0x000210a0 0x000220a0 GLOBAL OBJ    8        obstack_alloc_failed_handler                                                                    
119 0x0000fea0 0x0000fea0 GLOBAL FUNC   297      _obstack_newchunk                  
```
New behaviour:
```
nth paddr      vaddr      bind   type   size lib name                               
-----------------------------------------------------------------------------------
118 0x000210a0 0x000220a0 GLOBAL OBJ    8        obstack_alloc_failed_handler                                                                    
119 0x0000fea0 0x0000fea0 GLOBAL FUNC   297      _obstack_newchunk                                                                               
120 0x0000fe80 0x0000fe80 GLOBAL FUNC   25       _obstack_begin_1   

```
(ignore the utf8 line vs the ascii one, the difference is in the length).

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
The change itself is good, just please fix the tests.

**Comment by XVilka** [comment]
Looks like it's not that simple:
```
[XX] db/io/srec arm1.bin.srec
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'iI
iS
' srec://bins/srec/arm1.bin.srec
-- stdout
--- expected
+++ actual
@@ -1,5 +1,5 @@
-Name     Value
---------------
+Name     Value                                                    
+------------------------------------------------------------------
 arch     arm
 baddr    0x8000
 binsz    571848
```

**Comment by XVilka** [comment]
We could solve that by providing borders also, not only header/body separator.

**Comment by ret2libc** [comment]
> Looks like it's not that simple:
> 
> ```
> [XX] db/io/srec arm1.bin.srec
> RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'iI
> iS
> ' srec://bins/srec/arm1.bin.srec
> -- stdout
> --- expected
> +++ actual
> @@ -1,5 +1,5 @@
> -Name     Value
> ---------------
> +Name     Value                                                    
> +------------------------------------------------------------------
>  arch     arm
>  baddr    0x8000
>  binsz    571848
> ```

That is right. The full table indeed is:
```
[0x00008150]> iI
Name     Value                                                    
------------------------------------------------------------------
arch     arm
baddr    0x8000
binsz    571848
bintype  elf
bits     32
class    ELF32
compiler GCC: (Ubuntu 4.3.2-2ubuntu9) 4.3.3 20081217 (prerelease)
endian   LE
laddr    0x0
lang     c
machine  ARM
maxopsz  4
minopsz  4
os       linux
pcalign  4
rpath    NONE
subsys   linux
stripped false
crypto   false
havecode true
va       true
sanitiz  false
static   true
linenum  true
lsyms    true
canary   false
PIE      false
RELROCS  true
NX       true

```

**Comment by XVilka** [comment]
Looks a bit ugly, but ok.

**Comment by ret2libc** [comment]
> Looks a bit ugly, but ok.

I think the separator line should be as long as the maximum element in the column.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
