### PR TITLE
Don't create flags at UT64_MAX

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
It broke 3 tests:
```
[XX] db/formats/mach0/leb128 macho trie malformed uleb128
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc  bins/mach0/macho-trie-bad-export-info-malformed-uleb128
-- stderr
@@ -1,2 +1,3 @@
 malformed uleb128
 malformed uleb128
+WARNING: rz_flag_set: assertion 'f && name && *name && off != UT64_MAX' failed (line 714)

[XX] db/esil/x86_64 mem read
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e io.va=true
e esil.debug=true
e asm.arch=x86
e asm.bits=64
aei
aeim
aer rsp=0x00108000
.aer*
aer rdi=0xFFFFFFFFFFFFFFFF
ae rdi,rsp,=[8]
.aer*
ae rsp,[8],rax,=
.aer*
?v rax
' -
-- stdout
@@ -1 +1 @@
-0xffffffffffffffff
+0x0

[XX] db/cmd/cmd_i it2
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'mkdir .tmp
cp bins/mach0/fatmach0-3true .tmp/it2-modfile
o .tmp/it2-modfile
oo+
it
wx 0x90
it
o--
rm .tmp/it2-modfile
' --
-- stderr
@@ -1,3 +1,4 @@
+WARNING: rz_flag_set: assertion 'f && name && *name && off != UT64_MAX' failed (line 714)
 File has been modified.
 - md5 84144530144b53a704c84d9c65ab5f92
 + md5 9a99cca7bf3e27ee1c8964141cfad053
```

**Comment by p371jah** [comment]
About `db/esil/x86_64 mem read`: `aer` command execute `.dr*` (equivalent of `.aer*`)

**Review by XVilka — APPROVED** [review]

**Comment by p371jah** [comment]
Should `offset == UT64_MAX` be treated as an error? Not sure that skipping it silently is ok. But numerous warning messages are not ok too.

**Review by ret2libc — COMMENTED** [review]
Why do we need to consider UT64_MAX not valid? I guess this assumption is unfortunately done in many other places, right? :(

**Comment by p371jah** [comment]
Between `0` and `UT64_MAX` I would prefer the second one.

**Comment by p371jah** [comment]
But somewhere in rizin code `0` is used for invalid addresses, and as a result you get this https://github.com/rizinorg/rizin/issues/42

**Comment by ret2libc** [comment]
> Between `0` and `UT64_MAX` I would prefer the second one.

Oh well, yeah :D though I'd say there should be something else to indicate an invalid address, because the entire ut64 range is valid. But yeah, between the two I prefer UT64_MAX, but then you have the same problem only at a different (less common) address.

**Comment by p371jah** [comment]
Well, since the issue is relates mostly to symbols it would be better to use `undefined address` term.

**Comment by ret2libc** [comment]
I am not sure about this... 
`f world @ 0xffffffffffffffff` will not work anymore with this PR.

**Comment by wargio** [comment]
yes but `0xffffffffffffffff` is an impossible address

**Comment by ITAYC0HEN** [comment]
> yes but `0xffffffffffffffff` is an impossible address

but it might be a possible value (crypto, etc...)

**Comment by wargio** [comment]
Ok, so if we want to consider valid any address space, then we need to refactor all the methods to be like: `RZ_API bool my_function(...., ut64 *returned_address);` so we can check if the function has failed and allow UT64_MAX.

**Comment by ret2libc** [comment]
> Ok, so if we want to consider valid any address space, then we need to refactor all the methods to be like: `RZ_API bool my_function(...., ut64 *returned_address);` so we can check if the function has failed and allow UT64_MAX.

Yes I actually think this is the only real way. Rizin represents an address space of 64 bit, so you can't use one of those addresses as "invalid". You need to have some other ways to mark the invalid addr.

**Pull request closed without merging**
