### PR TITLE
Show available memory in Linux `ci.yml` jobs

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

As part of efforts towards resolving #2833, this pr makes `ci.yml` Linux jobs show available memory at start.

**Test plan**

Shown output is useful. All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
## linux-clang-tests-asan
```
Run free -h
              total        used        free      shared  buff/cache   available
Mem:          6.8Gi       655Mi       4.5Gi       9.0Mi       1.7Gi       5.8Gi
Swap:         4.0Gi          0B       4.0Gi
```
## linux-gcc-tests-asan
```
Run free -h
              total        used        free      shared  buff/cache   available
Mem:          6.8Gi       1.8Gi       3.2Gi       9.0Mi       1.8Gi       4.7Gi
Swap:         4.0Gi          0B       4.0Gi
```

**Comment by kazarmy** [comment]
There's swap of 4 gibibytes

**Comment by ret2libc** [comment]
Seems enough memory to run those things?

**Comment by kazarmy** [comment]
Seemingly, but rz-test runs fuzz tests in parallel so there's that to consider.

**Review by wargio — APPROVED** [review]
For me this can be merged.

**Review by XVilka — APPROVED** [review]
LGTM to print this always

**Pull request merged**
