### PR TITLE
Remove cosmetic changes from cris-dis.c

### PR DESCRIPTION
**Pull request by kazarmy**
# SQUASH

 

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr removes cosmetic changes from `librz/asm/arch/cris/gnu/cris-dis.c` so that it's closer to [upstream](https://github.com/bminor/binutils-gdb/blob/master/opcodes/cris-dis.c) and thus easier to merge changes from upstream. The removal process involves `git reset -p` and a lot of looking at code hunks, splitting them when necessary.

**Test plan**

The changes are cosmetic. All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
is this PR ready to be reviewed?

**Comment by kazarmy** [comment]
emm yes

**Review by wargio — APPROVED** [review]
some of these cosmetics changes looks weird to me, but the code looks the same.

**Comment by kazarmy** [comment]
unsure which ones look weird

**Pull request merged**
