### PR TITLE
#include <errno.h> explicitly in rz_types.h

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`errno` is explicitly used as part of `RZ_V_NOT` in `rz_types.h`, so this pr `#include`s its header file in `rz_types.h` explicitly as well to prevent weird build problems caused by broken `#include` assumptions aka "what? you didn't bring along `errno.h` with you??".

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
@ITAYC0HEN could you check if it fixes your problem?

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
> @ITAYC0HEN could you check if it fixes your problem?

TBH, i use arch and i do not have this issue

**Comment by kazarmy** [comment]
I think this pr should be merged whether or not it solves @ITAYC0HEN's problem.

**Comment by ITAYC0HEN** [comment]
Yes this fixed it :)
How would you explain that only I experienced this issue?

**Comment by kazarmy** [comment]
Idk tbh ... I suggest you do what @karliss suggested.

**Pull request merged**
