### PR TITLE
Revert OpenBSD `buildtype` back to `debugoptimized` and remove its `MALLOC_OPTIONS=S`

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

#1818 might have fixed whatever was causing the UAFs in the OpenBSD build so this pr reverts its `buildtype` back to `debugoptimized` and removes its `MALLOC_OPTIONS=S`.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Much better, it also made a significant difference in terms of the CI times. 👍

**Comment by kazarmy** [comment]
Noooooo #1818 didn't solve the issue (https://builds.sr.ht/~xvilka/job/606468#task-test-416) ... @XVilka do you want me to revert this?

**Comment by XVilka** [comment]
Yes

**Comment by kazarmy** [comment]
Ok 581e84a756cc24ff4850d72b224f37f2a945984a

**Pull request merged**
