### PR TITLE
Adding timeouts to long tests

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

If green, then merge

### CODE REVIEW

**Comment by XVilka** [comment]
Ideally, we should try to optimize these parsers and scenarios so they wouldn't be so slow.

**Comment by ret2libc** [comment]
What's the purpose of adding the timeouts? How is this going to fix anything?

**Comment by XVilka** [comment]
@ret2libc it fixed the red ASAN CI job, apparently

**Comment by wargio** [comment]
> What's the purpose of adding the timeouts? How is this going to fix anything?

some tests needs more time. this increases the timeout of those

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
