### PR TITLE
Use `clang-format-13` for linting

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`clang-format-13` automatically adds whitespaces in comments, making them more readable. Also, `clang-format-11` is now more than a year old, so on many Linux distributions' repositories, `clang-format-13` is the default `clang-format` version available. Therefore it is hard to consistently format code according to `clang-format-11`, while using `clang-format-13`.

**Test plan**

The old code should fail the linter test, and the newly formatted code shall pass.

**Closing issues**

None.

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Review by kazarmy — CHANGES_REQUESTED** [review]
Please update [DEVELOPERS.md#c](https://github.com/rizinorg/rizin/blob/dev/DEVELOPERS.md#c) as well.

**Comment by XVilka** [comment]
Please split/squash into two commits: one with the CI and documentation changes, and one with automatically-generated changes.

**Review by kazarmy — APPROVED** [review]

**Comment by kazarmy** [comment]
Wait for @XVilka first though.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Please rerun the `clang-format` again and I will merge this PR.

**Pull request merged**
