### PR TITLE
Fix integer overflow and excessive memory usage in jump table analysis

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

Tests pass

**Closing issues**

None

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Please run `clang-format`

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
@GustavoLCR were you able to analyze the binary referenced in r2? For me, it seems to require an infinite amount of time and i usually just ends up CTRL^C after a while.

**Comment by GustavoLCR** [comment]
> were you able to analyze the binary referenced in r2? For me, it seems to require an infinite amount of time and i usually just ends up CTRL^C after a while

fixed it with https://github.com/rizinorg/rizin/pull/1714/commits/52fac7f2ae9f7db3305ceeb0bb31f14d92e0c920

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]
Amazing! Thanks!

**Pull request merged**
