### PR TITLE
Remove `scr.html` config variable

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Removed `librz/cons/html.c` to filter non-HTML-compatible sequences
- Removed `RzCons` `.is_html` and `.was_html` members
- Removed `scr.html` configuration variable
- Removed `|H` "HTML pipe command"
- Removed `H>` and `H>>` HTML redirection commands

**Test plan**

CI is green

### CODE REVIEW

**Comment by wargio** [comment]
```
[XX] db/analysis/x86_64 a8 analyze bytes
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.arch=x86
e asm.bits=64
e asm.os=linux
a8 55|
' =
-- stdout
--- expected
+++ actual
@@ -1,20 +1,0 @@
-address: 0x0
-opcode: push rbp
-esilcost: 24
-disasm: push rbp
-pseudo: push rbp
-mnemonic: push
-description: push word, doubleword or quadword onto the stack
-mask: ff
-prefix: 0
-id: 588
-bytes: 55
-refptr: 0
-size: 1
-sign: false
-type: rpush
-cycles: 1
-esil: rbp,8,rsp,-,=[8],8,rsp,-=
-family: cpu
-stackop: inc
-stackptr: 8
-- stderr
WARNING: No handler for this kind of command `html_disable_stmt`
Error while executing command: a8 55|
```

**Review by ret2libc — APPROVED** [review]

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
Used in cutter: https://github.com/rizinorg/cutter/blob/a38d77c9690ea8160b152cde36ad97545aecbc66/src/dialogs/XrefsDialog.cpp#L129

**Comment by ret2libc** [comment]
> Used in cutter: https://github.com/rizinorg/cutter/blob/a38d77c9690ea8160b152cde36ad97545aecbc66/src/dialogs/XrefsDialog.cpp#L129

For those not familiar with it... How is that used? Why? :)

**Comment by XVilka** [comment]
Seems Cutter uses HTML as is: 
```cpp
    // Use cmd because cmRaw cannot handle the output properly. Why?
    QString disas = Core()->cmd("pd--20 @ " + QString::number(addr));
    ui->previewTextEdit->document()->setHtml(disas);
```

**Comment by ret2libc** [comment]
It remains to see the why! I guess it would be impossible for cutter to properly highlight the assembly by just looking at the json because there are not enough info provided, right @xarkes ?

**Comment by thestr4ng3r** [comment]
Yes, it's used for syntax highlighting of disassembly. In another place it does not use `scr.html`, but `rz_cons_html_filter()` directly (with strings containing ansi escape codes from json). https://github.com/rizinorg/cutter/blob/a38d77c9690ea8160b152cde36ad97545aecbc66/src/core/Cutter.cpp#L3966
https://github.com/rizinorg/cutter/blob/a38d77c9690ea8160b152cde36ad97545aecbc66/src/core/Cutter.cpp#L4099

Since `scr.html` causes all sorts of problems, I am also for removing it, but keeping `rz_cons_html_filter()` for now and rewriting the XrefsDialog in cutter to also convert manually.
Then we can either
* Keep `rz_cons_html_filter()` in rizin (without users, but it has a few tests and might turn out useful again
* Move it to Cutter
* or implement another conversion in Cutter from ansi to Qt-specific stuff without going through html.

**Comment by XVilka** [comment]
@thestr4ng3r what about "implement another conversion in Cutter from JSON to Qt-specific stuff without going through HTML"?

There is a nice API function for that `RZ_API int rz_core_print_disasm_json(RzCore *core, ut64 addr, ut8 *buf, int nb_bytes, int nb_opcodes, PJ *pj)`.

**Comment by wargio** [comment]
> @thestr4ng3r what about "implement another conversion in Cutter from JSON to Qt-specific stuff without going through HTML"?
> 
> There is a nice API function for that `RZ_API int rz_core_print_disasm_json(RzCore *core, ut64 addr, ut8 *buf, int nb_bytes, int nb_opcodes, PJ *pj)`.

how about just use rizin structures?

**Comment by thestr4ng3r** [comment]
> @thestr4ng3r what about "implement another conversion in Cutter from JSON to Qt-specific stuff without going through HTML"?
> 
> There is a nice API function for that `RZ_API int rz_core_print_disasm_json(RzCore *core, ut64 addr, ut8 *buf, int nb_bytes, int nb_opcodes, PJ *pj)`.

But that isn't the same as color codes in `pd`, is it?
In general, ansi codes actually are not too bad, they are short and easy to parse since we know beforehand what kinds of codes we can expect from rizin.

**Comment by ret2libc** [comment]
I think this can be closed for now. Until we first switch Cutter and/or provide a better "annotated asm" API I don't see us merging this.

**Pull request closed without merging**
