### PR TITLE
Remove command 0 (alias for s 0x)

### LINKED ISSUE #2363: Remove command `0` (alias for `s 0x...`)

### PR DESCRIPTION
**Pull request by PeiweiHu**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

waiting the result of CI to remove related test

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/2363

...

### CODE REVIEW

**Review by ret2libc — CHANGES_REQUESTED** [review]
You also have to remove all the `number_stmt` references in the rzshell parser/grammar and rebuild the grammar please (see grammar.js and https://github.com/rizinorg/rizin/blob/dev/subprojects/rizin-shell-parser/README.md)

**Comment by PeiweiHu** [comment]
@ret2libc Sorry for bothering you. Do you mean remove command 0 completely including both old-style (`rz_cmd_ox()`) and rzshell style (`parser-grammar` and `DEFINE_HANDLE_TS_FCN_AND_SYMBOL(number_stmt)` )?

**Comment by ret2libc** [comment]
> @ret2libc Sorry for bothering you. Do you mean remove command 0 completely including both old-style (`rz_cmd_ox()`) and rzshell style (`parser-grammar` and `DEFINE_HANDLE_TS_FCN_AND_SYMBOL(number_stmt)` )?

Isn't that the purpose or did I misunderstood?

**Comment by PeiweiHu** [comment]
I thought just remove the old code. I will remove command 0 completely. ：-）

**Comment by ret2libc** [comment]
@XVilka we wanted to remove the 0x... command completely, right?

**Comment by PeiweiHu** [comment]
If no need to completely remove the command 0 in rzshell, just tell me then I will cancel the last commit.

**Comment by wargio** [comment]
```
[XX] db/formats/elf/helloworld-gcc-elf p-
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '0x8048000
e search.in=io.map
p-
e search.in=io.maps
p-
' bins/elf/analysis/x86-helloworld-gcc
-- stdout
--- expected
+++ actual
@@ -1,2 +1,0 @@
-0x08048000 [^._______ss_s__s_sss_ssssss_ss_ss__sz_s____] 0x0804859c
-0x08048000 [^_sssssszss_____________________________sss] 0x080496d0

-- stderr
Error while parsing command: `0x8048000
e search.in=io.map
p-
e search.in=io.maps
p-

```
please add an `s` in front of `0x8048000` (in the test)

**Review by XVilka — APPROVED** [review]

**Pull request merged**
