### PR TITLE
Add /*<type>*/ annotations everwhere

### PR DESCRIPTION
**Pull request by wingdeans**
**Addresses https://github.com/rizinorg/rizin/issues/2981**

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This commit adds `/*<type>*/` annotations to **almost** all `RzList`, `RzVector`, `RzPVector`, and `RzGraph` occurrences in function declarations. The missing annotations were detected using [a libclang python script](https://github.com/wingdeans/rz-bindgen/blob/ff92b4ea2b3247153bac24c8d05a6bea20c62e26/src/lint.py) and the types were then manually added.

There are a few non-comment changes which shouldn't affect any functionality. Let me know if I should revert them.
 - removed unused `intern_table` arguments in `pyc_dis.c`, `pyc_dis.h`, `asm_pyc.c`
 - removed unused `classes` argument from `place_nodes` in `agraph.c`
 - removed unused `recurse` and `recurse_bb` functions in `canalysis.c`
 - removed unused `vars` field from `RzPrint` struct
 - removed unused `RzAnalysisType*` structs from `rz_analysis.h`
 - removed unused `list` field from `RzEgg` struct
 - fixed bug in `bp_plugin.c` where duplication checking logic iterates over the wrong list
 - removed unused `q_regs` field from `RzDebug` struct
 - removed unused `backtrace` field from `RzDebugPlugin` struct
 - removed unused `classes_list` field from `RzBinNXOObj` struct
 - removed unused `methods_list` and `classes_list` fields from `RzBinZimgObj` struct

**TODO**
 - [x] extend checks to struct members

**Test plan**

The annotations are currently only for developer ergonomics and are not verified in any way. [rz-bindgen](https://github.com/rizinorg/rz-bindgen) utilizes them, but only from a limited subset of the headers, so there is no way to verify their correctness.

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Please add the CI job itself that runs the linter. Also, please resolve the conflicts.

**Comment by wingdeans** [comment]
Not sure what the `RzDebugPlugin` fields `tids` and `kill_list` are supposed to return, but they actually have usages (returning null) unlike the other things I removed.

**Comment by XVilka** [comment]
```
clang.cindex.LibclangError: /usr/lib//libclang.so: cannot open shared object file: No such file or directory. To provide a path to libclang use Config.set_library_path() or Config.set_library_file().
```

**Comment by wingdeans** [comment]
> Not sure what the `RzDebugPlugin` fields `tids` and `kill_list` are supposed to return, but they actually have usages (returning null) unlike the other things I removed.

Do these function pointers have a specified return type, or should I or remove them (or annotate with `void*`)?

**Comment by XVilka** [comment]
@wingdeans annotate with `void *` for now.

**Comment by wingdeans** [comment]
Only errors are due to inconsistencies in rz-hexagon ([PR here](https://github.com/rizinorg/rz-hexagon/pull/78))
```
Missing type comment at <rizin/librz/asm/arch/hexagon/hexagon.h:151:10> (token is not a comment)
Mismatched function annotation for hex_const_ext_free at <rizin/librz/asm/arch/hexagon/hexagon_arch.h:69:13> : None (was RZ_NULLABLE at <rizin/librz/asm/arch/hexagon/hexagon_arch.c:226:13>
Missing type comment at <rizin/librz/asm/arch/hexagon/hexagon_arch.c:787:59> (token is not a comment)
```

**Comment by XVilka** [comment]
@wingdeans what is the status of this PR? Could you please update and rebase it on top of the latest `dev`?

**Comment by wingdeans** [comment]
> Only errors are due to inconsistencies in rz-hexagon ([PR here](https://github.com/rizinorg/rz-hexagon/pull/78))
> 
> ```
> Missing type comment at <rizin/librz/asm/arch/hexagon/hexagon.h:151:10> (token is not a comment)
> Mismatched function annotation for hex_const_ext_free at <rizin/librz/asm/arch/hexagon/hexagon_arch.h:69:13> : None (was RZ_NULLABLE at <rizin/librz/asm/arch/hexagon/hexagon_arch.c:226:13>
> Missing type comment at <rizin/librz/asm/arch/hexagon/hexagon_arch.c:787:59> (token is not a comment)
> ```

The linter is ready, it just needs https://github.com/rizinorg/rz-hexagon/pull/78 in rz-hexagon to address the emitted warnings.

**Comment by wingdeans** [comment]
>     * removed unused `intern_table` arguments in `pyc_dis.c`, `pyc_dis.h`, `asm_pyc.c`
>     * removed unused `classes` argument from `place_nodes` in `agraph.c`
>     * removed unused `recurse` and `recurse_bb` functions in `canalysis.c`
>     * removed unused `vars` field from `RzPrint` struct
>     * removed unused `RzAnalysisType*` structs from `rz_analysis.h`
>     * removed unused `list` field from `RzEgg` struct
>     * fixed bug in `bp_plugin.c` where duplication checking logic iterates over the wrong list
>     * removed unused `q_regs` field from `RzDebug` struct
>     * removed unused `backtrace` field from `RzDebugPlugin` struct
>     * removed unused `classes_list` field from `RzBinNXOObj` struct
>     * removed unused `methods_list` and `classes_list` fields from `RzBinZimgObj` struct

There are a lot of non-comment changes, for generic types I couldn't infer the specializations for since they weren't being used.

**Comment by wargio** [comment]
> RzBinNXOObj

why you are exporting plugin headers? the only headers that should be exported are those in the `rzlib/include` folder

**Comment by XVilka** [comment]
@wingdeans yes, step by step. Having the linter opens the potential to improve the inference and detection.

**Comment by wingdeans** [comment]
> > RzBinNXOObj
> 
> why you are exporting plugin headers? the only headers that should be exported are those in the `rzlib/include` folder

The goal is to add type annotations everywhere and make sure that they are consistent between definition and declaration, with the linter checking this. I can take them out if it's too much but I think it's useful for development (and maybe adding actual typechecking in the future).

**Review by wargio — APPROVED** [review]
Nice cleanup

**Comment by XVilka** [comment]
@wingdeans LGTM, but please rebase and fix the conflicts.

**Review by XVilka — APPROVED** [review]
Lets merge this and fix the hexagon issue separately.

**Comment by XVilka** [comment]
I merged it as is then and created a separate issue to fix those warnings: https://github.com/rizinorg/rizin/issues/3020
Please address it as soon as possible. Thank you!

**Pull request merged**
