### PR TITLE
Remove `-` (open editor) from rzshell

### LINKED ISSUE #1585: Port `-` (open editor) to rzshell

### PR DESCRIPTION
**Pull request by chinggg**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

1. modify `type` and `args` of `"-"` in `cmd_descs.yaml`
2. add `rz_cmd_stdin_handler()` in `cmd.c`
3. ~~replace `rz_cmd_stdin()` with `rz_cmd_stdin_handler()` in `cmd_desc.h`~~
4. ~~modify `cmd_stdin_cd` in `cmd_desc.c`, add `cmd_stdin_args[]` to `cmd_stdin_help`~~

Question: The summary defined in `cmd_descs.yaml` is `Open cfg.editor and run script`, but the command actually prompted `'-' '.-' '. -' do the same` before. Now I choose the former, should the latter be kept as well?

**Test plan**

...

**Closing issues**

closes #1585 
...

### CODE REVIEW

**Comment by ret2libc** [comment]
Did you manually modify cmd_descs.c/.h ? They are automatically generated from the yaml files, as it should be explained at the top of the files. You just need to have python-pyyaml installed (you also have to delete and recreate the build dir if pyyaml was not installed when you first created the build dir)

**Comment by chinggg** [comment]
Yeah actually I wondered why I need to do the boring job of adding these things after I did this, since `docs/rzshell.md` says it will be auto generated.  At first I forgot to add `args` to `cmd_descs.yaml` and the build fail, so I thought I should manually add these things, which is a wrong decision.

**Review by XVilka — APPROVED** [review]
In the future, we might want to change also the `rz_core_run_script(core, "-")` function cc @ret2libc . For now, it's fine as is. Thank you!

**Comment by ret2libc** [comment]
> Yeah actually I wondered why I need to do the boring job of adding these things after I did this, since `docs/rzshell.md` says it will be auto generated.  At first I forgot to add `args` to `cmd_descs.yaml` and the build fail, so I thought I should manually add these things, which is a mistake.

Only .yaml file changes should be needed indeed. Please let me know if there is something missing in the documentation or parts we should improve. I'd love to make sure people can easily add commands as needed!

**Comment by chinggg** [comment]
> > Yeah actually I wondered why I need to do the boring job of adding these things after I did this, since `docs/rzshell.md` says it will be auto generated.  At first I forgot to add `args` to `cmd_descs.yaml` and the build fail, so I thought I should manually add these things, which is a mistake.
> 
> Only .yaml file changes should be needed indeed. Please let me know if there is something missing in the documentation or parts we should improve. I'd love to make sure people can easily add commands as needed!

In fact the https://github.com/rizinorg/rizin/blob/dev/doc/rzshell.md#how-to-write-a-new-command part is clear enough, the only thing that confuses me is `args` is required even if there is no args for a command, at first I forgot to add `args: []`, which will cause compile error.

**Comment by ret2libc** [comment]
> > > Yeah actually I wondered why I need to do the boring job of adding these things after I did this, since `docs/rzshell.md` says it will be auto generated.  At first I forgot to add `args` to `cmd_descs.yaml` and the build fail, so I thought I should manually add these things, which is a mistake.
> > 
> > 
> > Only .yaml file changes should be needed indeed. Please let me know if there is something missing in the documentation or parts we should improve. I'd love to make sure people can easily add commands as needed!
> 
> In fact the https://github.com/rizinorg/rizin/blob/dev/doc/rzshell.md#how-to-write-a-new-command part is clear enough, the only thing that confuses me is `args` is required even if there is no args for a command, at first I forgot to add `args: []`, which will cause compile error.

Ok I will probably add few lines to make that clearer then! Thanks

**Comment by ret2libc** [comment]
> Question: The summary defined in `cmd_descs.yaml` is `Open cfg.editor and run script`, but the command actually prompted `'-' '.-' '. -' do the same` before. Now I choose the former, should the latter be kept as well?

I'm tempted to say that maybe `-` is not really needed after all... I would keep just `.-`, What do you think?
cc @XVilka @wargio ?

**Comment by XVilka** [comment]
Yes, it makes sense to remove it completely.

**Comment by wargio** [comment]
i agree with you.

**Comment by ret2libc** [comment]
Sorry @chinggg for this....
Could you please remove this command completely?

If you want, there are other issues like https://github.com/rizinorg/rizin/issues/1588 to starting help with.

**Comment by chinggg** [comment]
Yeah I will change this PR to remove the `-` command completely.
Wait... I find Error while parsing command: `.-`, it exists before my modification. I will also fix this.
image

**Comment by ret2libc** [comment]
> Yeah I will change this PR to remove the `-` command completely.
> Wait... I find Error while parsing command: `.-`, it exists before my modification. I will also fix this.

Yes, `.-` already exists and it is already converted to rzshell. In other words, this `-` command is a duplicate.

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — APPROVED** [review]

**Comment by chinggg** [comment]
I mean `.-` does not work as expected, but `.- ` does. `.-` will not call `rz_interpret_editor_2_handler`.
```yaml
  - name: .-  # adding `""` here will not help too
    cname: interpret_editor_2
    summary: Open cfg.editor and interpret tmp file
    args: []
```

**Comment by ret2libc** [comment]
> I mean `.-` does not work as expected, but `.- ` does. `.-` will not call `rz_interpret_editor_2_handler`.
> 
> ```yaml
>   - name: .-  # adding `""` here will not help too
>     cname: interpret_editor_2
>     summary: Open cfg.editor and interpret tmp file
>     args: []
> ```

Yeah... I will provide a fix for this. Thanks for noticing. It requires updates to the grammar.js file.

**Comment by ret2libc** [comment]
See https://github.com/rizinorg/rizin/pull/1608

**Pull request merged**
