### PR TITLE
Remove all flaky download pdb test

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Those tests are flaky by definition.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
I am not sure it's a good idea. This feature should be tested somehow. Maybe just check the HTTP request instead? So it should match to what really server responds right now.

**Comment by ghost** [comment]
> This feature should be tested somehow. Maybe just check the HTTP request instead? So it should match to what really server responds right now.

We can open an issue to fix it later.

This PR is a small patch to fix quickly this annoying behavior.

**Review by ret2libc — CHANGES_REQUESTED** [review]
I'm actually against this without another test or something else in the same PR (things tends to get forgotten with "later" :D ) also, it just happens some times, but we can always restart the build. I'd prefer to have something better to test these things.

**Comment by wargio** [comment]
not a good idea, but we should allow them to fail, but not crash.

**Comment by wargio** [comment]
or we can run a python server that provides the pdb and the test will download from there.

**Comment by kazarmy** [comment]
It would be great if we could have 3-colour builds: red and green as normal, and yellow if this test fails.

**Pull request closed without merging**
