### PR TITLE
Import patches from radare2

### PR DESCRIPTION
**Pull request by XVilka**
DO NOT SQUASH

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Sync to the latest radare2, but not everything is imported - only minor changes.

cc @eagleoflqj

### CODE REVIEW

**Comment by XVilka** [comment]
I will rebase for AppVeyor once https://github.com/rizinorg/rizin/pull/226 merged. Please wait before that until doing the actual merge.

**Comment by XVilka** [comment]
I had to import also removal of `RZ_ANALYSIS_CC_*` hardcoded constants and using `analysis.cc` and `analysis.syscc` config variables instead for the @pelijah's patch.

**Comment by XVilka** [comment]
@eagleoflqj and it seems to break ARMv8 build:
https://travis-ci.com/github/rizinorg/rizin/jobs/463463117#L2497
```
[**]                             db/cmd/feat_arithmetic      793 OK        32 BR        0 XX        1 FX
[XX] db/cmd/cmd_av avj
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aaa
avj
' bins/elf/analysis/elf-virtualtable
-- stdout
@@ -1 +1 @@
-[{"offset":4197608,"methods":[{"offset":4197064,"name":"method.A.greet__"},{"offset":4197368,"name":"method.C.printValue__"}]},{"offset":4197640,"methods":[{"offset":4197064,"name":"method.A.greet__"},{"offset":4197250,"name":"method.B.printValue__"}]},{"offset":4197672,"methods":[{"offset":4197064,"name":"method.A.greet__"},{"offset":4197108,"name":"method.A.printValue__"}]}]
+[{"offset":4197608,"methods":[{"offset":4197064,"name":"method.A.greet"},{"offset":4197368,"name":"method.C.printValue"}]},{"offset":4197640,"methods":[{"offset":4197064,"name":"method.A.greet"},{"offset":4197250,"name":"method.B.printValue"}]},{"offset":4197672,"methods":[{"offset":4197064,"name":"method.A.greet"},{"offset":4197108,"name":"method.A.printValue"}]}]
-- stderr
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Use -AA or aaaa to perform additional experimental analysis.
```

**Comment by XVilka** [comment]
There are also two RISC-V related issues:
https://travis-ci.com/github/rizinorg/rizin/jobs/463463117#L2904
```
[XX] db/formats/elf/elf-riscv64 ELF: riscv64: main analysis
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.bytes=true
e analysis.vars.stackname=true
e asm.calls=false
s sym.main
af
pdf
' bins/elf/analysis/guess-number-riscv64
-- stdout
@@ -1,19 +1,21 @@
 / (fcn) main 160
-// int main (int argc, char **argv, char **envp);
+// int main (int argc, int64_t arg6);
 |           ; var int64_t var_18h @ s0-0x18
 |           ; var int64_t var_14h @ s0-0x14
 |           ; var int64_t var_10h @ sp+0x10
 |           ; var int64_t var_8h @ sp+0x18
+|           ; arg int argc @ a0
+|           ; arg int64_t arg6 @ a5
 |           0x00010150      130101fe       addi sp, sp, -32
 |           0x00010154      233c1100       sd ra, 24(sp)
 |           0x00010158      23388100       sd s0, 16(sp)
 |           0x0001015c      13040102       addi s0, sp, 32
-|           0x00010160      9307b007       li a5, 123
-|           0x00010164      2326f4fe       sw a5, -20(s0)
-|           0x00010168      9307f0ff       li a5, -1
-|           0x0001016c      2324f4fe       sw a5, -24(s0)
+|           0x00010160      9307b007       li a5, 123                  ; arg6
+|           0x00010164      2326f4fe       sw a5, -20(s0)              ; arg6
+|           0x00010168      9307f0ff       li a5, -1                   ; arg6
+|           0x0001016c      2324f4fe       sw a5, -24(s0)              ; arg6
 |      ..-> 0x00010170      b7170200       lui a5, 0x21
-|      ::   0x00010174      1385874f       addi a0, a5, 1272
+|      ::   0x00010174      1385874f       addi a0, a5, 1272           ; arg6
 |      ::   0x00010178      ef00c01f       jal ra, sym.printf
 |      ::   0x0001017c      930784fe       addi a5, s0, -24
 |      ::   0x00010180      93850700       mv a1, a5

[XX] db/formats/elf/elf-riscv64 ELF: riscv64: full analysis
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -A -Qc 'e asm.bytes=true
e asm.calls=false
s sym.main
pdf
' bins/elf/analysis/guess-number-riscv64
-- stdout
@@ -1,32 +1,34 @@
             ; CALL XREF from entry0 @ 0x10040
 / (fcn) main 160
-// int main (int argc, char **argv, char **envp);
+// int main (int argc, int64_t arg6);
 |           ; var int64_t var_bp_18h @ s0-0x18
 |           ; var int64_t var_14h @ s0-0x14
 |           ; var int64_t var_10h @ sp+0x10
 |           ; var int64_t var_18h @ sp+0x18
+|           ; arg int argc @ a0
+|           ; arg int64_t arg6 @ a5
 |           0x00010150      130101fe       addi sp, sp, -32
 |           0x00010154      233c1100       sd ra, 24(sp)
 |           0x00010158      23388100       sd s0, 16(sp)
 |           0x0001015c      13040102       addi s0, sp, 32
-|           0x00010160      9307b007       li a5, 123
-|           0x00010164      2326f4fe       sw a5, -20(s0)
-|           0x00010168      9307f0ff       li a5, -1
-|           0x0001016c      2324f4fe       sw a5, -24(s0)
+|           0x00010160      9307b007       li a5, 123                  ; arg6
+|           0x00010164      2326f4fe       sw a5, -20(s0)              ; arg6
+|           0x00010168      9307f0ff       li a5, -1                   ; arg6
+|           0x0001016c      2324f4fe       sw a5, -24(s0)              ; arg6
 |           ; CODE XREFS from main @ 0x101c8, 0x101d8
 |      ..-> 0x00010170      b7170200       lui a5, 0x21
-|      ::   0x00010174      1385874f       addi a0, a5, 1272           ; const char *format
+|      ::   0x00010174      1385874f       addi a0, a5, 1272           ; arg6
 |      ::   0x00010178      ef00c01f       jal ra, dbg.printf
 |      ::   0x0001017c      930784fe       addi a5, s0, -24
 |      ::   0x00010180      93850700       mv a1, a5
 |      ::   0x00010184      b7170200       lui a5, 0x21
-|      ::   0x00010188      13850751       addi a0, a5, 1296           ; const char *format
+|      ::   0x00010188      13850751       addi a0, a5, 1296
 |      ::   0x0001018c      ef00402f       jal ra, dbg.scanf
 |      ::   0x00010190      032784fe       lw a4, -24(s0)
 |      ::   0x00010194      8327c4fe       lw a5, -20(s0)
 |     ,===< 0x00010198      631cf700       bne a4, a5, 0x101b0
 |     |::   0x0001019c      b7170200       lui a5, 0x21
-|     |::   0x000101a0      13858751       addi a0, a5, 1304           ; const char *s
+|     |::   0x000101a0      13858751       addi a0, a5, 1304
 |     |::   0x000101a4      ef00002d       jal ra, dbg.puts
 |     |::   0x000101a8      93070000       li a5, 0
 |    ,====< 0x000101ac      6f000003       j 0x101dc
@@ -35,12 +37,12 @@
 |    | ::   0x000101b4      8327c4fe       lw a5, -20(s0)
 |    |,===< 0x000101b8      635af700       ble a5, a4, 0x101cc
 |    ||::   0x000101bc      b7170200       lui a5, 0x21
-|    ||::   0x000101c0      13858752       addi a0, a5, 1320           ; const char *s
+|    ||::   0x000101c0      13858752       addi a0, a5, 1320
 |    ||::   0x000101c4      ef00002b       jal ra, dbg.puts
 |    ||`==< 0x000101c8      6ff09ffa       j 0x10170
 |    || :   ; CODE XREF from main @ 0x101b8
 |    |`---> 0x000101cc      b7170200       lui a5, 0x21
-|    |  :   0x000101d0      13858753       addi a0, a5, 1336           ; const char *s
+|    |  :   0x000101d0      13858753       addi a0, a5, 1336
 |    |  :   0x000101d4      ef00002a       jal ra, dbg.puts
 |    |  `=< 0x000101d8      6ff09ff9       j 0x10170
 |    |      ; CODE XREF from main @ 0x101ac
-- stderr
[x] Analyze all flags starting with sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Finding xrefs in noncode section with analysis.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00025164 to 0x00025208 (aav)
[x] 0x00025164-0x00025208 in 0x25164-0x25208 (aav)
[x] 0x00025164-0x00025208 in 0x10000-0x25164 (aav)
[x] Value from 0x00010000 to 0x00025164 (aav)
[x] 0x00010000-0x00025164 in 0x25164-0x25208 (aav)
[x] 0x00010000-0x00025164 in 0x10000-0x25164 (aav)
[x] Emulate functions to find computed references (aaef)
[x] Type matching analysis for all functions (aaft)
[x] Propagate noreturn information
[x] Integrate dwarf function information.
[x] Use -AA or aaaa to perform additional experimental analysis.
```

**Comment by XVilka** [comment]
Looks like the failure is related to missing https://github.com/radareorg/radare2/commit/aaa930ab261a31e58b1257df06db02481cd3bd55 ("Improve and formalize r_name_check() along all the base ##core")

Let me know if you think we should import it too or just change the test instead.

**Comment by XVilka** [comment]
I changed the test then, this commit can be evaluated separately.

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
