### PR TITLE
Add support for `sltu` and `sgtu` instructions for RISC-V's ESIL #emu

### PR DESCRIPTION
**Pull request by officialcjunior**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Add support for `sltu` and `sgtu` instructions for RISC-V's ESIL, which are basically just unsigned-versions of `stl` and `sgtu`.

**Test plan**
I do not know how to add tests for this, at the moment. Would like directions as I'm currently learning more about it from the [previous tests](https://github.com/rizinorg/rizin/blob/dev/test/db/esil/riscv_64#L33-L53).

**Closing issues**

None

### CODE REVIEW

**Comment by ret2libc** [comment]
> **Test plan**
> I do not know how to add tests for this, at the moment. Would like directions as I'm currently learning more about it from the [previous tests](https://github.com/rizinorg/rizin/blob/dev/test/db/esil/riscv_64#L33-L53).

You can just do: `rizin -a riscv -b 32 -c "pade 33b7e500" -` (`33b7e500` is `sltu a4, a1, a4`).

However, your change seems not required, because this already works. Indeed, the lines you changed are `!strncmp (v, "slt", 3)`, which is true even if the string is `sltu`.

**Comment by ret2libc** [comment]
@thestr4ng3r could you you have a look? As said, I think this patch is not necessary because those additional `strcmp` check are redundant and sgtu/sltu are already considered in the more general case sgt/slt.

**Comment by thestr4ng3r** [comment]
Yes, `strncmp` already takes care of it. If the esil fits for both instructions, I would just add a comment that it also considers the `u` variants so it's easier to see.
But I think for unsigned comparison, this esil is wrong anyway as signed and unsigned comparison are not the same. See https://github.com/rizinorg/rizin/blob/449989c2e27c7bfc80976d015e399f7aedda9b1f/librz/analysis/esil.c#L2731-L2736
It will be best to have tests for the relevant cases (comparing -something to +something, etc.) for all these instructions.

**Comment by officialcjunior** [comment]
Oh, I see. Sounds fair. You may close this.
Also, what if I were to send something like this:
```diff
diff --git a/librz/analysis/p/analysis_riscv.c b/librz/analysis/p/analysis_riscv.c
index 26a6dd2e85..ac5f9e6f3d 100644
--- a/librz/analysis/p/analysis_riscv.c
+++ b/librz/analysis/p/analysis_riscv.c
@@ -556,7 +556,14 @@ static int riscv_op(RzAnalysis *analysis, RzAnalysisOp *op, ut64 addr, const ut8
                        esilprintf (op, "%s,%s,>=,%s,=", ARG (2), ARG (1), ARG (0));
                } else if (!strncmp (name, "sgt", 3) || !strcmp (name, "sgtu")) {
                        esilprintf (op, "%s,%s,>,%s,=", ARG (2), ARG (1), ARG (0));
-               }
+               } else if (!strcmp (name, "seqz")) {
+                       esilprintf (op, "%s,0,==,%s,=", ARG (1), ARG (0));
+               } else if (!strcmp (name, "sgtz")) {
+                       esilprintf (op, "%s,0,>,%s,=", ARG (1), ARG (0));
+               } else if (!strcmp (name, "sltz")) {
+                       esilprintf (op, "%s,0,<,%s,=", ARG (1), ARG (0));
+               } else if (!strcmp (name, "snez")) {
+                       esilprintf (op, "%s,0,!=,%s,=", ARG (1), ARG (0));
                // debug
                //else if (strcmp (name, "unimp") != 0 && name[0] != 'f' && name[1] != 'm') {
                //      int i;

```

**Comment by thestr4ng3r** [comment]
Yes, I'm no expert on risc-v semantics but this seems to make sense to me.

**Pull request closed without merging**
