### PR TITLE
Add RzIL vm event memory (read|write) index

### PR DESCRIPTION
**Pull request by b1llow**
This is because the memory of the RzIL VM has an index, but the index is ignored when an event is generated.

 

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
I am surprised it wasn't covered by unit tests. Please add a few basic ones for all events:
```
$ rg rz_il_event test/
```
returns nothing.

**Comment by b1llow** [comment]
> I am surprised it wasn't covered by unit tests. Please add a few basic ones for all events:
> 
> ```
> $ rg rz_il_event test/
> ```
> 
> returns nothing.

Maybe this will find some.

```
➤ rg RzILEvent test/                                                                                                                    (base) 
test/unit/test_il_vm.c
337:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
559:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
607:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
640:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
669:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
701:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
731:	RzILEvent *ev = rz_pvector_at(vm->events, 0);
```

**Comment by wargio** [comment]
> I am surprised it wasn't covered by unit tests. Please add a few basic ones for all events:
> ```
> $ rg rz_il_event test/
> ```
> returns nothing.

I did not add C tests for this. Only regression tests

**Review by XVilka — APPROVED** [review]
Ok, lets merge then

**Review by wargio — APPROVED** [review]

**Pull request merged**
