### PR TITLE
Update stable to 0.7.4 with patches

### PR DESCRIPTION
**Pull request by XVilka**
# DO NOT SQUASH

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Import some security fixes from `dev`.

Blocked on https://github.com/rizinorg/rz-bindgen/issues/66

**Test plan**

CI is green

### CODE REVIEW

**Comment by wargio** [comment]
i think you need to cherrypick also the changes for the CI made by @kazarmy

**Comment by XVilka** [comment]
Everything works except `rz-bindgen`:
```
Found ninja-1.11.1.git.kitware.jobserver-1 at /usr/local/bin/ninja
ninja: Entering directory `/home/runner/work/rizin/rizin/rz-bindgen/build'
[1/7] Generating bindgen_outputs with a custom command
FAILED: rizin.i 
/usr/bin/python3 ../src/main.py -o . --clang-path /usr/lib/llvm-14/lib --clang-args ' -resource-dir="/usr/lib/llvm-14/lib/clang/14.0.0"' --rizin-include-path /usr/include/librz --targets SWIG
Traceback (most recent call last):
  File "/home/runner/work/rizin/rizin/rz-bindgen/build/../src/main.py", line 51, in <module>
    bindings.run()
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/bindings.py", line 43, in run
    builders = [HeaderBuilder(name) for name in threaded_headers]
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/bindings.py", line 43, in <listcomp>
    builders = [HeaderBuilder(name) for name in threaded_headers]
  File "/home/runner/work/rizin/rizin/rz-bindgen/src/cparser_header.py", line 101, in __init__
    assert os.path.exists(filename), f"File {filename} does not exist"
AssertionError: File /usr/include/librz/rz_util/ht_sp.h does not exist
[2/7] Generating plugin/swig_runtime with a custom command
ninja: build stopped: subcommand failed.
```

We should make it working with two branches too, like `jsdec`, for example - with `dev` and `stable`: https://github.com/rizinorg/rz-bindgen/issues/66

**Comment by wargio** [comment]
i think it can be merged even without bindgen

**Comment by wargio** [comment]
given that everything is green besides bindgen, i think we can merge?

**Comment by XVilka** [comment]
> given that everything is green besides bindgen, i think we can merge?

No, lets fix bindgen first.

**Comment by XVilka** [comment]
I created `dev` and `stable` branches in `rz-bindgen`, we need fix Rizin CI scripts to use corresponding branch and then we can merge.

We also need to fix `rz-bindgen` first as well: https://github.com/rizinorg/rz-bindgen/pull/68

**Comment by XVilka** [comment]
Decided to fix rz-bindgen in separate commits/PR

**Pull request merged**
