### PR TITLE
[ARM] Test Capstone auto-sync

### PR DESCRIPTION
**Pull request by Rot127**
### Do not merge

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This draft PR's only purpose is to test the new [Capstone updater](https://github.com/capstone-engine/capstone/pull/1949) `auto-sync`.

Eventually more tests for the new instructions supported by Capstone will be added.

### CODE REVIEW

**Comment by XVilka** [comment]
```
../librz/analysis/p/analysis_arm_cs.c:294: error: 'ARM_MB_INVALID' undeclared
```

**Comment by XVilka** [comment]
@Rot127 please rebase and update this PR since there were a lot of changes in your auto-sync since.

**Comment by Rot127** [comment]
@XVilka So the build works now. Still a lot of tests are fail because of:
- Missing register name aliases (`fp` etc.)
- Some assertions.

I tested one or two assertions and they do not happen with `cstool -d`. So it is probably because the memory operands now includes offset registers and immediates which were prior `auto-sync` their own operands.
So Rizin likely passes a wrong operand to `getRegName()` and hits an assertion.

**Comment by Rot127** [comment]
Superseded by https://github.com/rizinorg/rizin/pull/3591

**Pull request closed without merging**
