### PR TITLE
Fix gcov working directory for Codecov

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

This pr fixes errors like the following (https://github.com/rizinorg/rizin/runs/1576711889#step:18:9654):

cannot_open_src_file

thus fixing the problem of the shrunken `.gcov` files (https://github.com/rizinorg/rizin/runs/1576711889#step:18:9654):

shrunk-gcov

and the Codecov problem.

**Test plan**

Codecov works.

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
> This pr tries to fix errors like the following (https://github.com/rizinorg/rizin/runs/1576711889#step:18:9563):

Mmm is this consistent?
If not, how can we see if it works? :D

**Comment by kazarmy** [comment]
What does "consistent" mean here?

**Comment by ret2libc** [comment]
> What does "consistent" mean here?

Does the error always happen?

**Comment by kazarmy** [comment]
> Does the error always happen?

Afaik yes.

**Comment by kazarmy** [comment]
Since Codecov is currently basing its code on Ubuntu 18.04 aka `ubuntu-latest` (e.g. [codecov-action](https://github.com/codecov/codecov-action/blob/7de43a7373de21874ae196a78f8eb633fcf7f0c4/.github/workflows/main.yml#L5) and [codecov-bash](https://github.com/codecov/codecov-bash/blob/11c8610e67a7d3bd12c77f6aa6411c7d14c3355e/.travis.yml#L1)), I think we should just use `ubuntu-latest` for now for the code coverage build.

Besides, there seem to be subtle differences between [gcov in gcc 7.5.0](https://github.com/gcc-mirror/gcc/blob/releases/gcc-7.5.0/gcc/gcov.c) and [gcov in gcc 9.3.0](https://github.com/gcc-mirror/gcc/blob/releases/gcc-9.3.0/gcc/gcov.c).

**Comment by ret2libc** [comment]
Mmm... that is really bad. GHA is switching ubuntu-latest to ubuntu-20.04 quite soon (You can see the warnings in the CI actions). Also, the coverage build on ubuntu-18.04 was becoming quite slow, probably because of older gcc/gcov and interactions with multi-threading.

**Comment by kazarmy** [comment]
> GHA is switching ubuntu-latest to ubuntu-20.04 quite soon

~~This is why I think doing custom scripting won't be worthwhile (though it would be an interesting exercise, with the risk that Codecov won't accept Ubuntu 20.04's gcov output without unreasonable effort).~~

~~Also, code coverage isn't critical, so I think we can bear with 100% Codecov output (apparently caused by no tracked files at all) for a little while longer.~~

**Comment by kazarmy** [comment]
Codecov is back! You can see the report at https://codecov.io/github/rizinorg/rizin/commit/e71b6a37377b5e19614f58374c3164e54674236b or https://github.com/rizinorg/rizin/pull/222#issuecomment-748219962 above.

**Comment by ret2libc** [comment]
> Codecov is back! You can see the report at https://codecov.io/github/rizinorg/rizin/commit/e71b6a37377b5e19614f58374c3164e54674236b or https://github.com/rizinorg/rizin/pull/222#issuecomment-748219962 above.

So it was just the missing script?

**Comment by kazarmy** [comment]
No, it was the wrong working directory. The script is run by the `codecov-action` GHA but the `working-directory` option works for `run:` but doesn't work for `uses:` afaik (https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#defaultsrun).

**Comment by kazarmy** [comment]
And `gcov` in gcc 9.3.0 won't work properly if it can't find the source file, while `gcov` in gcc 7.5.0 just carries on merrily for some reason.

**Review by ret2libc — APPROVED** [review]
If this makes it work, I'm happy with it 👍

**Comment by kazarmy** [comment]
If it doesn't, well it's back to the drawing board :persevere:

**Pull request merged**
