### PR TITLE
Fix inflate/deflate tests on Windows

### PR DESCRIPTION
**Pull request by ret2libc**
Patch developed by dmaroo

Check windows build.

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Looks good if it's green.

**Comment by XVilka** [comment]
So the difference is:
```
86/89 inflate_deflate                FAIL             0.03s   exit status 1
------------------------------------- 8< -------------------------------------
test_rz_inflate OK
test_rz_deflate ERR
[XX] Fail at line 42: rz_deflate failed:
expected 
1f 8b 08 00 00 00 00 00 00 0b 35 90 c1 71 43 31 08 44 ef a9 62 0b f0 fc 2a 92 5b ae 29 80 20 ec 30 23 09 59 02 8f cb 0f f2 4f 6e 42 c0 b2 fb 3e 6d 4a 83 8e 15 0d c5 aa 4d 2c 75 50 13 bf 80 ad 2f 61 17 8f 09 2a 3a 74 b1 f6 1b a4 6a 36 97 94 5c 80 68 ac 66 05 2e 6d e4 b2 76 d6 a2 25 ba 23 1c 95 be 53 1e e2 a7 b4 a0 d1 ad 13 a8 ea 3d e8 c0 97 43 ba b6 d4 46 d3 fd 78 64 49 ed 82 7b e8 42 b7 e5 33 0a e4 29 93 d5 c9 d5 3a a2 56 6a 6c a7 f2 1e d2 a5 fb d2 4b 52 47 0e 43 28 8d b7 f4 64 67 80 3c e5 07 de b7 24 85 0b 74 46 3a 39 b3 6a c7 94 31 e5 47 7a 91 99 c1 f3 e3 61 35 46 9e 93 b4 93 49 21 6b 09 58 6b fd 27 94 81 02 d7 b8 29 39 fa 36 84 41 33 8b 98 07 3e 9e 2c c3 25 36 c6 64 60 cc 24 9c 73 1c 43 0b f9 de c8 14 63 9a 16 e9 9b e2 26 95 47 39 ea a0 9d 1b 76 bd 2a 2b a1 c8 92 b9 bb cd ea b6 41 1b 90 26 8e f5 c7 35 da f1 f6 0b 67 7b 9f 87 be 01 00 00
got
1f 8b 08 00 00 00 00 00 00 0a 35 90 c1 71 43 31 08 44 ef a9 62 0b f0 fc 2a 92 5b ae 29 80 20 ec 30 23 09 59 02 8f cb 0f f2 4f 6e 42 c0 b2 fb 3e 6d 4a 83 8e 15 0d c5 aa 4d 2c 75 50 13 bf 80 ad 2f 61 17 8f 09 2a 3a 74 b1 f6 1b a4 6a 36 97 94 5c 80 68 ac 66 05 2e 6d e4 b2 76 d6 a2 25 ba 23 1c 95 be 53 1e e2 a7 b4 a0 d1 ad 13 a8 ea 3d e8 c0 97 43 ba b6 d4 46 d3 fd 78 64 49 ed 82 7b e8 42 b7 e5 33 0a e4 29 93 d5 c9 d5 3a a2 56 6a 6c a7 f2 1e d2 a5 fb d2 4b 52 47 0e 43 28 8d b7 f4 64 67 80 3c e5 07 de b7 24 85 0b 74 46 3a 39 b3 6a c7 94 31 e5 47 7a 91 99 c1 f3 e3 61 35 46 9e 93 b4 93 49 21 6b 09 58 6b fd 27 94 81 02 d7 b8 29 39 fa 36 84 41 33 8b 98 07 3e 9e 2c c3 25 36 c6 64 60 cc 24 9c 73 1c 43 0b f9 de c8 14 63 9a 16 e9 9b e2 26 95 47 39 ea a0 9d 1b 76 bd 2a 2b a1 c8 92 b9 bb cd ea b6 41 1b 90 26 8e f5 c7 35 da f1 f6 0b 67 7b 9f 87 be 01 00 00
test_rz_inflate_buf OK
test_rz_deflate_buf ERR
[XX] Fail at line 74: rz_deflate_buf does not return expected output:
expected
1f 8b 08 00 00 00 00 00 00 0b 35 90 c1 71 43 31 08 44 ef a9 62 0b f0 fc 2a 92 5b ae 29 80 20 ec 30 23 09 59 02 8f cb 0f f2 4f 6e 42 c0 b2 fb 3e 6d 4a 83 8e 15 0d c5 aa 4d 2c 75 50 13 bf 80 ad 2f 61 17 8f 09 2a 3a 74 b1 f6 1b a4 6a 36 97 94 5c 80 68 ac 66 05 2e 6d e4 b2 76 d6 a2 25 ba 23 1c 95 be 53 1e e2 a7 b4 a0 d1 ad 13 a8 ea 3d e8 c0 97 43 ba b6 d4 46 d3 fd 78 64 49 ed 82 7b e8 42 b7 e5 33 0a e4 29 93 d5 c9 d5 3a a2 56 6a 6c a7 f2 1e d2 a5 fb d2 4b 52 47 0e 43 28 8d b7 f4 64 67 80 3c e5 07 de b7 24 85 0b 74 46 3a 39 b3 6a c7 94 31 e5 47 7a 91 99 c1 f3 e3 61 35 46 9e 93 b4 93 49 21 6b 09 58 6b fd 27 94 81 02 d7 b8 29 39 fa 36 84 41 33 8b 98 07 3e 9e 2c c3 25 36 c6 64 60 cc 24 9c 73 1c 43 0b f9 de c8 14 63 9a 16 e9 9b e2 26 95 47 39 ea a0 9d 1b 76 bd 2a 2b a1 c8 92 b9 bb cd ea b6 41 1b 90 26 8e f5 c7 35 da f1 f6 0b 67 7b 9f 87 be 01 00 00
got
1f 8b 08 00 00 00 00 00 00 0a 35 90 c1 71 43 31 08 44 ef a9 62 0b f0 fc 2a 92 5b ae 29 80 20 ec 30 23 09 59 02 8f cb 0f f2 4f 6e 42 c0 b2 fb 3e 6d 4a 83 8e 15 0d c5 aa 4d 2c 75 50 13 bf 80 ad 2f 61 17 8f 09 2a 3a 74 b1 f6 1b a4 6a 36 97 94 5c 80 68 ac 66 05 2e 6d e4 b2 76 d6 a2 25 ba 23 1c 95 be 53 1e e2 a7 b4 a0 d1 ad 13 a8 ea 3d e8 c0 97 43 ba b6 d4 46 d3 fd 78 64 49 ed 82 7b e8 42 b7 e5 33 0a e4 29 93 d5 c9 d5 3a a2 56 6a 6c a7 f2 1e d2 a5 fb d2 4b 52 47 0e 43 28 8d b7 f4 64 67 80 3c e5 07 de b7 24 85 0b 74 46 3a 39 b3 6a c7 94 31 e5 47 7a 91 99 c1 f3 e3 61 35 46 9e 93 b4 93 49 21 6b 09 58 6b fd 27 94 81 02 d7 b8 29 39 fa 36 84 41 33 8b 98 07 3e 9e 2c c3 25 36 c6 64 60 cc 24 9c 73 1c 43 0b f9 de c8 14 63 9a 16 e9 9b e2 26 95 47 39 ea a0 9d 1b 76 bd 2a 2b a1 c8 92 b9 bb cd ea b6 41 1b 90 26 8e f5 c7 35 da f1 f6 0b 67 7b 9f 87 be 01 00 00
------------------------------------------------------------------------------
```

Somehow it sets the value as "TOPS-20"...
```
  0 - FAT filesystem (MS-DOS, OS/2, NT/Win32)
  1 - Amiga
  2 - VMS (or OpenVMS)
  3 - Unix
  4 - VM/CMS
  5 - Atari TOS
  6 - HPFS filesystem (OS/2, NT)
  7 - Macintosh
  8 - Z-System
  9 - CP/M
 10 - TOPS-20
 11 - NTFS filesystem (NT)
 12 - QDOS
 13 - Acorn RISCOS
255 - unknown
```

**Comment by XVilka** [comment]
A blast from the past:

> The [TOPS-20 operating system](https://en.wikipedia.org/wiki/TOPS-20) by Digital Equipment Corporation (DEC) was a proprietary OS used on some of DEC's 36-bit mainframe computers. The Hardware Reference Manual was described as for "DECsystem-10/DECSYSTEM-20 Processor" (meaning the DEC PDP-10 and the DECSYSTEM-20).

> TOPS-20 began in 1969 as the TENEX operating system of Bolt, Beranek and Newman (BBN) and shipped as a product by DEC starting in 1976. TOPS-20 is almost entirely unrelated to the similarly named TOPS-10, but it was shipped with the PA1050 TOPS-10 Monitor Calls emulation facility which allowed most, but not all, TOPS-10 executables to run unchanged. As a matter of policy, DEC did not update PA1050 to support later TOPS-10 additions except where required by DEC software.

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
Good if green, but please remove `meson test -v` change before merging.

**Pull request merged**
