### PR TITLE
v850: Add some undocumented instructions

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`bins/v850/hello-v850e`

```
            0x001006da      invalid
            0x001006db      unaligned
            0x001006dc      sldh  0[ep] r14
            0x001006de      invalid
            0x001006df      unaligned
            0x001006e0      sldh  0[ep] r0
```

```
│           0x00100eb8      addi  8, r13, r29
            0x00100ebc      invalid
            0x00100ebd      unaligned
            0x00100ebe      sldh  0[ep] r2
            0x00100ec0      invalid
            0x00100ec1      unaligned
            0x00100ec2      sldh  0[ep] r0
        ┌─< 0x00100ec4      be    0x101246
        │   0x00100ec8      addi  1, r22, r16                          ; vfprintf.c:1751
        │   0x00100ecc      add   r23, r10                             ; vfprintf.c:1754
```

_Nset function in v850/ired_v850 (at 0x100fcc)

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
After missing instructions are implemented, please add a test with disasm of the function at 0x1005e8 of `v850/hello-v850e`

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
@imbillow do you plan to work in this PR further or is it ready to be reviewed?

**Comment by b1llow** [comment]
> @imbillow do you plan to work in this PR further or is it ready to be reviewed?

I think it's ready for review

This PR should have greatly improved the disassembly of rh850, although there is no RzIL part.

**Comment by b1llow** [comment]
> > @imbillow do you plan to work in this PR further or is it ready to be reviewed?
> 
> I think it's ready for review
> 
> This PR should have greatly improved the disassembly of rh850, although there is no RzIL part.

A part of the C code snippet for the disassembly is based on sleigh generation, and I'm not sure if generating C code for RzIL is a good idea.

[sleigh2c](https://github.com/imbillow/sleigh2c)

**Review by XVilka — APPROVED** [review]
Yes, I also tested it on my files, much better. Good job!

**Comment by XVilka** [comment]
> > > @imbillow do you plan to work in this PR further or is it ready to be reviewed?
> > 
> > 
> > I think it's ready for review
> > This PR should have greatly improved the disassembly of rh850, although there is no RzIL part.
> 
> A part of the C code snippet for the disassembly is based on sleigh generation, and I'm not sure if generating C code for RzIL is a good idea.
> 
> [sleigh2c](https://github.com/imbillow/sleigh2c)

Please add a good readme to that project and transfer it to the `rizinorg` As for generating RzIL from it - I don't think it's a good idea. Given how hard it might be to derive and map the semantics of the instructions to RzIL functions, I think it will be faster and easier to do it by hand.

**Pull request merged**
