### PR TITLE
Add file percentage in visual mode (V/Vv)

### LINKED ISSUE #4477: Show file/address space percentage in the right screen corner in the visual mode
[Neo]Vim shows the percentage of the file, where you are located in the bottom right corner. Rizin could show it too, in visual modes. Both top right and bottom right corner locations are fine:

Screenshot 2024-05-06 at 9 12 18 PM

Screenshot 2024-05-06 at 9 13 03 PM

Screenshot 2024-05-06 at 9 12 40 PM

See how it's done in NeoVim:

Screenshot 2024-05-06 at 9 15 51 PM

### PR DESCRIPTION
**Pull request by PeiweiHu**
## PLEASE DON'T SQUASH

two commits are individual 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

**calculation logics**

For Vv, the percentage is calculated based on the lines of output in the right column: 

`current_line_no / total_line_num`

For V, the percentage is calculated based on the percentage of the current address against the mapped section memory:

`(address - section_start_addr) / section_size`

**This pr adds a static global variable:**

```c
static ut64 column_nlines = 0;
``` 

No worries. I will remove it with other related global variables in subsequent pr.

```c
static int level = 0;
static st64 delta = 0;
static ut64 column_nlines = 0;
// output is used to store the result of printCmds
// and avoid duplicated analysis while j and k is pressed
static char *output = NULL;
// output_mode labels which printCmds' result is stored in output
static int output_mode = -1;
static int output_addr = -1;
static int option = 0;
static int variable_option = 0;
static int printMode = 0;
static bool selectPanel = false;
```

**Test plan**

manual test since we don't have a mechanism for testing tui

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/4477

https://github.com/rizinorg/rizin/assets/58985155/08d6e7a0-a956-44bf-b37e-99b4a84680f5

### CODE REVIEW

**Comment by wargio** [comment]
it would be nice to at least have one big struct and just one global.

**Comment by wargio** [comment]
For those like me not seeing it, percentage is on the lower corner in `v` mode and upper corner in `V` mode.

**Review by wargio — CHANGES_REQUESTED** [review]
.

**Review by XVilka — APPROVED** [review]
I see where the global added. While they should be eliminated, if you *really* plan to remove them in bulk from `vmenus.c` - I suppose it's okay for now.

**Comment by XVilka** [comment]
Please rebase to fix the red CI

**Comment by PeiweiHu** [comment]
> For those like me not seeing it, percentage is on the lower corner in `v` mode and upper corner in `V` mode.

Sorry, I don't get it. I think I didn't add percentage in `v` mode (visual panel mode). Do you mean that the positions of percentage are different in `Vv` and `V` modes?

**Comment by wargio** [comment]
> > For those like me not seeing it, percentage is on the lower corner in `v` mode and upper corner in `V` mode.
> 
> Sorry, I don't get it. I think I didn't add percentage in `v` mode (visual panel mode). Do you mean that the positions of percentage are different in `Vv` and `V` modes?

kinda. i actually never seen the perc value thus that is why i was actively searching for it :D ignore my comment :)

**Review by wargio — APPROVED** [review]
<3

**Comment by XVilka** [comment]
@PeiweiHu it doesn't work in the simple visual mode. Simply do `rizin /bin/ls`, then `V` and scroll. You can try different modes with `p`/`P` and scroll - it also always stays at 0%.

**Comment by XVilka** [comment]
> @PeiweiHu it doesn't work in the simple visual mode. Simply do `rizin /bin/ls`, then `V` and scroll. You can try different modes with `p`/`P` and scroll - it also always stays at 0%.

What's interesting, that it works in the "last" of the visual modes (the "hexII" mode, the "sparse hexdump", press `V` then `p` multiple times), while doesn't in any other mode.

**Pull request merged**
