### PR TITLE
Fix `rax -t` not considering GMT argument

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

Tests pass

**Closing issues**

None

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
As tests were passing even before, maybe a new test for this?

**Comment by XVilka** [comment]
@ret2libc it's for https://github.com/rizinorg/rizin/pull/1502#issuecomment-922226376

**Comment by kazarmy** [comment]
> As tests were passing even before, maybe a new test for this?

I agree. Also the GMT argument is undocumented.

**Comment by XVilka** [comment]
There is a test already for this:
```
NAME=rz-ax -t "1234567890 GMT-1"
FILE==
CMDS=!rz-ax -t "1234567890 GMT-1" | cut -d " " -f 1,2
EXPECT=<<EOF
Fri Feb
EOF
RUN
```
https://github.com/rizinorg/rizin/blob/dev/test/db/tools/rz_ax#L375

**Comment by GustavoLCR** [comment]
> @ret2libc it's for [#1502 (comment)](https://github.com/rizinorg/rizin/pull/1502#issuecomment-922226376)

@XVilka I don't think this will fix that case. It's just something I noticed while trying to debug that

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
