### PR TITLE
Release 0.2.1 cherrypicks

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Cherry-pick UAFs for 0.2.1 bugfix release.

**Test plan**

CI is green

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]
I think we can merge right now.

**Comment by wargio** [comment]
@XVilka you should add my patches for java once merged

**Comment by XVilka** [comment]
@wargio but those are just leaks, no?

**Comment by wargio** [comment]
yes they are

**Review by wargio — APPROVED** [review]

**Pull request merged**
