### PR TITLE
Implement float80, RzFloat to decimal string and refactoring RzReg to use Bitvectors

### PR DESCRIPTION
**Pull request by wargio**
# DO NOT SQUASH

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Adds support to float80
- Rewrites how float/double/long double are converted to RzFloat to support float80 and float128 natively
- Adds RzFloat to decimal string
- Refactors RzReg to use RzBitVector

Small note, the "constants" for float/double/long double are like that because windows compilers doesn't like INFINITY and NAN, but at the same time, doing like this makes the code very portable since the functions are C90 compatible.

Original PR #3140

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
<details>
  <summary>Click me</summary>

One broken Windows test:

```
[XX] C:\projects\rizin\test\db\archos\windows-x64\dbg_dts continue backwards
ANSICON=1 RZ_NOPLUGINS=1 C:\projects\rizin\rizin-vs2022_64-v0.5.0\bin\rizin.exe -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e dbg.create_new_console=false
ood
db @ main
3dc
dr rflags=0x200 > nul
dr rflags
dr rax
dts+
7ds
dr rflags
dr rax
dcb
dr rflags
dr rax
doc
' bins/pe/ioli/w32/crackme0x00.exe
-- stdout
--- expected
+++ actual
@@ -1,6 +1,6 @@
-0x00000200
-0x00000001
-0x00000216
-0x0000001e
-0x00000200
-0x00000001
+0x0000000000000200
+0x0000000000000001
+0x0000000000000216
+0x000000000000001e
+0x0000000000000200
+0x0000000000000001
-- stderr
Spawned new process with pid 1832, tid = 5164
ERROR: File dbg://C:\\projects\\rizin\\test\\bins/pe/ioli/w32/crackme0x00.exe  reopened in read-write mode
hit breakpoint at: 0x401310
Reading 65536 byte(s) from 0x00010000...
Reading 32768 byte(s) from 0x00098000...
Reading 8192 byte(s) from 0x000b0000...
Reading 32768 byte(s) from 0x000f8000...
Reading 53248 byte(s) from 0x00160000...
Reading 32768 byte(s) from 0x0030c000...
Reading 4096 byte(s) from 0x00405000...
Reading 4096 byte(s) from 0x00406000...
Reading 12288 byte(s) from 0x0060d000...
Reading 135168 byte(s) from 0x00780000...
Reading 4096 byte(s) from 0x00a7f000...
Reading 40960 byte(s) from 0x00c10000...
Reading 8192 byte(s) from 0x7497a000...
Reading 4096 byte(s) from 0x758f0000...
Reading 12288 byte(s) from 0x75d95000...
Reading 16384 byte(s) from 0x763e5000...
Reading 4096 byte(s) from 0x77e14000...
Reading 24576 byte(s) from 0x77f3e000...
Reading 4096 byte(s) from 0x7ff58000...
Reading 4096 byte(s) from 0x7ff61000...
Reading 4096 byte(s) from 0x7ff80000...
Reading 4096 byte(s) from 0x7ff91000...
Reading 4096 byte(s) from 0x7ffc87b5a000...
Reading 4096 byte(s) from 0x7ffc885aa000...
Reading 4096 byte(s) from 0x7ffc88bcf000...
Reading 32768 byte(s) from 0x7ffc88bd2000...
hit breakpoint at: 0x401310 cnum: 0
```
And two on Alpine Linux (static build):
```

[XX] db/abi/compilers/gcc_64 ELF_ABI : gcc Of flagspaces
RZ_NOPLUGINS=1 /github/home/rizin-static/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -A -Qc 'fsl~functions
' bins/abi_bins/elf/compilers/gcc/echo_gcc_Of
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-   45 * functions
+   44 * functions

-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] Analyze len bytes of instructions for references
[
[x] Analyze len bytes of instructions for references
[ ] Check for classes
[
[x] Check for classes
[ ] Analyze local variables and arguments
[
[x] Analyze local variables and arguments
[ ] Type matching analysis for all functions
[
[x] Type matching analysis for all functions
[ ] Applying signatures from sigdb
[
[x] Applied 1 FLIRT signatures via sigdb
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Resolve pointers to data sections
[
[x] Resolve pointers to data sections

[x] Use -AA or aaaa to perform additional experimental analysis.



[XX] db/abi/compilers/gcc_64 ELF_ABI : gcc O3 flagspaces
RZ_NOPLUGINS=1 /github/home/rizin-static/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -A -Qc 'fsl~functions
' bins/abi_bins/elf/compilers/gcc/echo_gcc_O3
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-   44 * functions
+   43 * functions

-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[ ] Analyze function calls
[
[x] Analyze function calls
[ ] Analyze len bytes of instructions for references
[
[x] Analyze len bytes of instructions for references
[ ] Check for classes
[
[x] Check for classes
[ ] Analyze local variables and arguments
[
[x] Analyze local variables and arguments
[ ] Type matching analysis for all functions
[
[x] Type matching analysis for all functions
[ ] Applying signatures from sigdb
[
[x] Applied 1 FLIRT signatures via sigdb
[ ] Propagate noreturn information
[
[x] Propagate noreturn information
[ ] Integrate dwarf function information.
[
[x] Integrate dwarf function information.
[ ] Resolve pointers to data sections
[
[x] Resolve pointers to data sections

[x] Use -AA or aaaa to perform additional experimental analysis.
```

</details>

**Comment by XVilka** [comment]
Please import https://github.com/Chatterino/api/pull/383 to fix the GitHub Action Windows builds

**Review by Heersin — APPROVED** [review]

**Comment by XVilka** [comment]
Not sure if random or relevant:
```
[XX] db/asm/arm_64 <asm> ldrsh w0, [x1]
-- <asm> ldrsh w0, [x1] <--- 2000c079 ---> <IL>
-- IL
--- expected
+++ actual
@@ -1,1 +1,0 @@
-(set x0 (cast 64 false (cast 32 (msb (loadw 0 16 (var x1))) (loadw 0 16 (var x1)))))
```
on macOS

**Comment by wargio** [comment]
> Not sure if random or relevant:
> 
> ```
> [XX] db/asm/arm_64 <asm> ldrsh w0, [x1]
> -- <asm> ldrsh w0, [x1] <--- 2000c079 ---> <IL>
> -- IL
> --- expected
> +++ actual
> @@ -1,1 +1,0 @@
> -(set x0 (cast 64 false (cast 32 (msb (loadw 0 16 (var x1))) (loadw 0 16 (var x1)))))
> ```
> 
> on macOS

random.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
