### PR TITLE
Revert memory leak fix for relocs

### PR DESCRIPTION
**Pull request by giridharprasath**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

See: [#4426 ](https://github.com/rizinorg/rizin/pull/4426#discussion_r1578997169)

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — COMMENTED** [review]
I wonder why it reverted the test result back?

**Review by p371jah — APPROVED** [review]

**Comment by p371jah** [comment]
> I wonder why it reverted the test result back?

IDK about vaddr of the import, might be a bug in PE plugin or in bin lib. But case of a name is a good example of side effects: PE plugin modifies a duplicate which is not presented in imports list.

**Comment by p371jah** [comment]
@XVilka What worries me more is that asan jobs didn't catch those UAF/double free.

**Comment by XVilka** [comment]
It probably means we don't have enough testcases for these paths - PE, COFF format parsers.

**Comment by p371jah** [comment]
> It probably means we don't have enough testcases for these paths - PE, COFF format parsers.

No, it is enough to just open/close with rizin any COFF file from testbins to trigger UAF.

**Comment by p371jah** [comment]
But ASAN is happy if I run `rz-test test/db/formats/coff`

**Comment by pelijah** [comment]
> What worries me more is that asan jobs didn't catch those UAF/double free.

@thestr4ng3r @ret2libc Is it possible that ASAN is disabled in forked process?

**Comment by p371jah** [comment]
Nevermind it is all about `Q` option

**Pull request merged**
