### PR TITLE
Remove dead code in RzCons dietline

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`USE_UTF8` was always set to 1 for quite a while. Removed unused code.

**Test plan**

CI is green, Rizin console works as before.

### CODE REVIEW

**Review by wargio — APPROVED** [review]
This needs to be tested on windows just to ensure it doesn't bring any new problem

**Comment by XVilka** [comment]
@wargio tested on Windows. Doesn't seem completely work, but it was the same before my changes.

## ConEmu

image

## cmd.exe

image

## PowerShell

image

**Comment by XVilka** [comment]
Works if I use comments, but it seems there is a lack of fonts or something in both cmd.exe and PowerShell?

image

**Comment by XVilka** [comment]
Changing the code page doesn't help:

image

**Comment by XVilka** [comment]
If I change the code page to 936, it works in PowerShell:

image

and cmd.exe:

image

**Comment by wargio** [comment]
interesting, could be something we should not handle (thus ok like that).

**Pull request merged**
