### PR TITLE
Update Docker image from Debian 10 ("buster") to Debian 12 ("bookworm")

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Debian 10 doesn't receive updates anymore and almost EOL. Time to update the base for the Docker image.

**Test plan**

CI is green

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]
LGTM

**Comment by thestr4ng3r** [comment]
Buster still has LTS until June 30th, 2024: https://wiki.debian.org/LTS
Since the purpose of this job is explicitly to test support on old systems, it should not be updated before that.

**Comment by thestr4ng3r** [comment]
Sorry, I thought this was rz-ghidra. I still do think we should keep it on 10.

**Comment by XVilka** [comment]
Lets keep Debian 10 for a year then.

**Pull request closed without merging**
