### PR TITLE
Disable ARM hacks for Capstone 6

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

After auto-sync updates in Capstone, there is no need for those anymore. Moreover, they were implemented inefficiently, so that it leads to a small increase in performance (5-15% depending on the file).

**Test plan**

CI is green

### CODE REVIEW

**Comment by XVilka** [comment]
Looks like the new output is the right one, @Rot127 please confirm.
```
[XX] db/analysis/arm64 ao mte irg addg
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'ao@ 0x100007f10
echo --
ao@ 0x100007f14
' bins/mach0/hello-mte
-- stdout
--- expected
+++ actual
@@ -16,10 +16,10 @@
 family: sec
 --
 address: 0x100007f14
-opcode: addg x9, x8, 0x20, 0x0
+opcode: addg x9, x8, 0x20, 0
 esilcost: 0
-disasm: addg x9, x8, 0x20, 0x0
-pseudo: asm("addg x9, x8, 0x20, 0x0")
+disasm: addg x9, x8, 0x20, 0
+pseudo: asm("addg x9, x8, 0x20, 0")
 mnemonic: addg
 mask: ffffffff
 prefix: 0



[XX] db/analysis/arm64 ao mte big endian
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -a arm -b 64 -e cfg.bigendian=true -Qc 'wx 91a0090c918201099ac813e8
ao@ 0
echo ---
ao@ 4
echo ---
ao@ 8
' =
-- stdout
--- expected
+++ actual
@@ --1,10 +-1,10 @@
 address: 0x0
-opcode: addg x12, x8, 0x0, 0x2
+opcode: addg x12, x8, 0x200, 2
 esilcost: 0
-disasm: addg x12, x8, 0x0, 0x2
-pseudo: asm("addg x12, x8, 0x0, 0x2")
+disasm: addg x12, x8, 0x200, 2
+pseudo: asm("addg x12, x8, 0x200, 2")
 mnemonic: addg
 mask: ffffffff
 prefix: 0
@@ -16,10 +16,10 @@
 family: sec
 ---
 address: 0x4
-opcode: addg x9, x8, 0x20, 0x0
+opcode: addg x9, x8, 0x20, 0
 esilcost: 0
-disasm: addg x9, x8, 0x20, 0x0
-pseudo: asm("addg x9, x8, 0x20, 0x0")
+disasm: addg x9, x8, 0x20, 0
+pseudo: asm("addg x9, x8, 0x20, 0")
 mnemonic: addg
 mask: ffffffff
 prefix: 0
[XX] db/asm/arm_64 <asm> stzg x13, [x3, 0x0]!
-- <asm> stzg x13, [x3, 0x0]! <--- 6d0c60d9
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-stzg x13, [x3, 0x0]!
+stzg x13, [x3, 0]!



[XX] db/asm/arm_64 <asm> stzg x13, [x3, 0x0]
-- <asm> stzg x13, [x3, 0x0] <--- 6d0860d9
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-stzg x13, [x3, 0x0]
+stzg x13, [x3]



[XX] db/asm/arm_64 <asm> ldg x13, [x3, 0x0]
-- <asm> ldg x13, [x3, 0x0] <--- 6d0060d9
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-ldg x13, [x3, 0x0]
+ldg x13, [x3]



[XX] db/asm/arm_64 <asm> stg x13, [x3], 0x0
-- <asm> stg x13, [x3], 0x0 <--- 6d0420d9
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-stg x13, [x3], 0x0
+stg x13, [x3], 0



[XX] db/asm/arm_64 <asm> cmpp sp, x13
-- <asm> cmpp sp, x13 <--- ff03cdba
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-cmpp sp, x13
+subps xzr, sp, x13



[XX] db/asm/arm_64 <asm> addg x12, x8, 0x0, 0x2
-- <asm> addg x12, x8, 0x0, 0x2 <--- 91a0090c
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-addg x12, x8, 0x0, 0x2
+addg x12, x8, 0x200, 2



[XX] db/asm/arm_64 <asm> addg x0, sp, 0x80, 0x4
-- <asm> addg x0, sp, 0x80, 0x4 <--- e0138891
-- disassembly
--- expected
+++ actual
@@ -1,1 +1,1 @@
-addg x0, sp, 0x80, 0x4
+addg x0, sp, 0x80, 4
```

**Comment by wargio** [comment]
That fail on ccmp kinda make sense.
```
-cmpp sp, x13
+subps xzr, sp, x13
```

**Comment by Rot127** [comment]
Output of llvm matches with the new one:

```
> echo "<bytes>" | llvm-mc-18 --triple=arm64 --mattr=mte --disassemble --print-imm-hex --show-encoding
	stzg	x13, [x3, #0x0]!                // encoding: [0x6d,0x0c,0x60,0xd9]
	stzg	x13, [x3]                       // encoding: [0x6d,0x08,0x60,0xd9]
	ldg	x13, [x3]                       // encoding: [0x6d,0x00,0x60,0xd9]
	stg	x13, [x3], #0x0                 // encoding: [0x6d,0x04,0x20,0xd9]
	subps	xzr, sp, x13                    // encoding: [0xff,0x03,0xcd,0xba]
	addg	x12, x8, #0x200, #0x2           // encoding: [0x0c,0x09,0xa0,0x91]
	addg	x0, sp, #0x80, #0x4             // encoding: [0xe0,0x13,0x88,0x91]
```

So they are correct.

**Review by Rot127 — APPROVED** [review]
Fix the tests and we are good to go

**Comment by wargio** [comment]
@XVilka you should probably also fix the capstone hacks and output the correct `subps xzr`

**Comment by XVilka** [comment]
> @XVilka you should probably also fix the capstone hacks and output the correct `subps xzr`

I don't want to invest time into something that will be relatively soon deleted, to be honest.

**Pull request merged**
