### PR TITLE
Use UTC timezone for tests

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This is the Rizin version of radareorg/radare2#19056 and fixes the following local problem:

TZ

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by wargio — APPROVED** [review]
<3

**Review by ret2libc — APPROVED** [review]

**Comment by XVilka** [comment]
@kazarmy @GustavoLCR @pelijah will it work for Windows as well?

**Comment by kazarmy** [comment]
yes it will

**Comment by XVilka** [comment]
@kazarmy didn't help in the curious case of Alpine Linux though: https://github.com/rizinorg/rizin/pull/1635/checks?check_run_id=3550852838#step:8:99

**Comment by kazarmy** [comment]
I don't know of any time zones that shift time by a few decades so probably not related.

**Pull request merged**
