### PR TITLE
Fixes for old Debian (Wheezy, Jessie)

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Compiling Rizin for Debian Wheezy and Jessie became problematic, there are some annoying GCC bugs in it: https://github.com/rizinorg/rizin/pull/322#issuecomment-755969176
```
make[3]: Entering directory `/__w/rizin/rizin/rizin/librz/cons'
...
gcc -c -std=gnu99 -MD   -fPIC -g -Wall -D__UNIX__=1 -I/__w/rizin/rizin/rizin/librz -I/__w/rizin/rizin/rizin/librz/include -I/__w/rizin/rizin/rizin/librz/../shlr/sdb/src -fvisibility=hidden -o pal.o pal.c
pal.c:99:2: error: initializer element is not constant
pal.c:99:2: error: (near initialization for 'colors[0].rcolor')
make[3]: *** [pal.o] Error 1
make[3]: Leaving directory `/__w/rizin/rizin/rizin/librz/cons'
make[2]: Leaving directory `/__w/rizin/rizin/rizin/librz'
make[2]: *** [cons] Error 2
make[1]: Leaving directory `/__w/rizin/rizin/rizin/librz'
```

**Test plan**

All green.

### CODE REVIEW

**Comment by ret2libc** [comment]
Is it really not possible to keep supporting it somehow? Since Centos6 went EOL I would love to keep support for compilation on some old platforms...

**Comment by XVilka** [comment]
Sure, it's possible with some code changes.

**Comment by XVilka** [comment]
I have no idea why GCC complains - all initialization is done by the compile-time constants.

**Comment by XVilka** [comment]
One failing test on Wheezy:
```

[XX] db/tools/rz no preincrement/predecrement in 3rd part of for statement
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '"!git grep \"for[[:space:]]*([^;)]*;[^;)]*;\([^,)(]*,\)*[[:space:]]*\(++\|--\)[[:space:]]*[[:alpha:]_][[:alnum:]_]*[[:space:]]*[,)]\" -- .. :!db/tools/rz :!../shlr/** :!../librz/asm/arch/** :!../**/mangling/cxx/cp-demangle.c"' -
-- stderr
@@ -0,0 +1 @@
+fatal: Unimplemented pathspec magic '!' in ':!db/tools/rz'
```
Also should disable debugging tests somehow, `rz-test` should have an `ignore` option for this https://github.com/rizinorg/rizin/issues/336.

I think we should actually drop this "test" completely. It should be substituted by clang-format and clang-tidy instead.

**Review by ret2libc — APPROVED** [review]
The real thing here should be to use meson/ninja to build on old debians as well and that is required to kill acr/make.

**Review by wargio — APPROVED** [review]

**Pull request merged**
