### PR TITLE
Cherrypicks for 0.1.1

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Imported a few important fixes from the `dev` branch for the upcoming 0.1.1 release

**Test plan**

Everything green

**Closing issues**

Related to https://github.com/rizinorg/cutter/issues/2577

### CODE REVIEW

**Comment by ret2libc** [comment]
Commit on changing how version is displayed is broken. I forgot to check the output of `-V` and that still uses the last tag.

**Comment by ret2libc** [comment]
> Commit on changing how version is displayed is broken. I forgot to check the output of `-V` and that still uses the last tag.

Maybe just completely remove that commit. It will be there for 0.2.0. I'm afraid to break stuff.

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
Either remove 819f157 "Fixes for jump table ##analysis" or add  4ef3ed08f3383066a35916225a9f802ace3ad244 "Fix gcc 9.2.0 kind of x86_64 jumptables (#475)"

**Comment by XVilka** [comment]
Removed both `-v` and jump table commits.

**Review by ret2libc — APPROVED** [review]

**Review by thestr4ng3r — APPROVED** [review]

**Comment by XVilka** [comment]
@ret2libc I cherry-picked the fix for wrongly removed `Shift-Tab` action in ASCII graph and your Windows 32bit build changes.
@karliss I think those two shouldn't affect Cutter things anyway.

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
@karliss is there anything else for Cutter? Could we merge this (and https://github.com/rizinorg/rizin/pull/627 subsequently) and craft a 0.1.1?

**Review by yossizap — APPROVED** [review]

**Review by thestr4ng3r — APPROVED** [review]

**Pull request merged**
