### PR TITLE
Fix default arch of x86

### LINKED ISSUE #2680: ELF arch handling
**Is your feature request related to a problem? Please describe.**
The ELF plugin [defaults to returning x86](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L1405) when `e_machine` is `EM_NONE` or not present in the [arch_translation_table](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L242). This has the undesired effect of falsely reporting that an ELF's arch is x86 in many cases. For instance, `EM_BPF` is not currently handled in elf_info.c's [machine_name_translation_table](https://github.com/rizinorg/rizin/blob/782fcd5257f6f16f924162675c2f0f6189f864a4/librz/bin/format/elf/elf_info.c#L69). `rz-bin` shows the machine type as unknown with the raw `e_machine` value, which is fine, but the architecture as x86, which is definitely incorrect. I have also seen firmware that uses ELF as a container but does not specify `e_machine`, which of course gets reported as x86 by default.

**Describe the solution you'd like**
`EM_NONE` should be represented in the `arch_translation_table`, and the `EM_80386` and `EM_X86_64` types should be added and explicitly mapped to `x86`. [rz_bin_elf_get_arch](https://github.com/rizinorg/rizin/blob/dev/librz/bin/format/elf/elf_info.c#L1396) should appropriately return "No machine" when `e_machine` is `EM_NONE`, and "Unknown or unsupported machine" when the `e_machine` value does not map to a currently-supported architecture.

**Describe alternatives you've considered**
Based on my initial review of the code, I'm not seeing any great alternatives and the solution appears fairly obvious. Happy to hear alternatives or justification for why x86 needs to be the default.

**Additional context**
I haven't fully investigated if fixing this requires changes outside of the ELF plugin to handle new `arch` types (e.g., "none" or "unknown"). I'm happy to get a PR going, but want to make sure I understand the full scope of any impacts this has on the larger project before undertaking it.

### PR DESCRIPTION
**Pull request by bdemick**
Fixes default arch of x86 when unknown, unsupported, or no machine specified. ##bin

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Adds `EM_NONE`, `EM_386`, and `EM_X86_64` to the `arch_translation_table`, and changes the default return value for the rz_bin_elf_get_arch function to "Unknown or unsupported arch" instead of "x86". This makes `rz-bin`'s ELF info output more accurate when `EM_NONE` is specified, or an unhandled `e_machine` value is present.

**Test plan**

I verified that these changes worked by running `rz-bin -I` on several example ELF files to ensure that the desired output was achieved.

1. x86 and x86-64 ELF files to ensure that the arch returned is still `x86`
2. An ARM ELF file to ensure that a non-x86 arch is not impacted by this change
3. An ELF file with `EM_NONE` for the `e_machine`, which resulted in `No machine` for `arch`
4. An ELF file with an unsupported `e_machine` type (Linux eBPF), which resulted in `Unknown or unsupported arch` for `arch`

**Closing issues**

closes #2680

### CODE REVIEW

**Review by beigela — APPROVED** [review]
This is incredible. I love it. Thank you.

**Comment by ret2libc** [comment]
Looks good, let's wait for ci

**Review by XVilka — APPROVED** [review]

**Comment by bdemick** [comment]
I made the same (roughly) PR for radare2, and they recommended having `EM_NONE` map to "null" to allow the "null" plugin to run for that case. Happy to make that change here as well, if it applies.

**Comment by ret2libc** [comment]
> I made the same (roughly) PR for radare2, and they recommended having `EM_NONE` map to "null" to allow the "null" plugin to run for that case. Happy to make that change here as well, if it applies.

I'm ok with this, though please also apply this patch:
```diff
diff --git a/librz/asm/meson.build b/librz/asm/meson.build
index c64c3127ac..2eddbcf467 100644
--- a/librz/asm/meson.build
+++ b/librz/asm/meson.build
@@ -27,6 +27,7 @@ asm_plugins = [
   'mcs96',
   'mips_cs',
   'msp430',
+  'null',
   'or1k',
   'pic',
   'ppc_as',
@@ -105,6 +106,7 @@ rz_asm_sources = [
   'p/asm_mcs96.c',
   'p/asm_mips_cs.c',
   'p/asm_msp430.c',
+  'p/asm_null.c',
   'p/asm_or1k.c',
   'p/asm_pic.c',
   'p/asm_mcore.c',

```

However, we should also change the `strdup("Unknown or unsupported arch");`, otherwise rizin will try to set asm.arch to "Unknown or unsupported arch". It should probably become either `strdup("")` (in which case it would set the default architecture, which AFAIK is what your host is on) or `strdup("null")` (in which case it would work similarly to EM_NONE). Preferences?

**Comment by ret2libc** [comment]
> An ELF file with an unsupported e_machine type (Linux eBPF), which resulted in Unknown or unsupported arch for arch

By the way, if you can add that currently unsupported machine type for bpf it would be great :)

**Comment by bdemick** [comment]
I think it's important to have the distinction between "No machine" and "machine specified but unknown". Especially if you want to engage some architecture guessing algorithms downstream. I'll make the "null" and empty string changes and pull that patch in, as well as the BPF change here shortly.

**Comment by XVilka** [comment]
@bdemick please also rebase, to fix the CI network errors.

**Review by ret2libc — APPROVED** [review]

**Comment by bdemick** [comment]
Argh derp, I clicked the wrong button in the UI!

**Comment by XVilka** [comment]
Please update the tests output also then:
```
[XX] db/cmd/cmd_list Print the asm/analysis plugins in quiet mode
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc Laq =
-- stdout
--- expected
+++ actual
@@ -26,6 +26,7 @@
 mcs96
 mips
 msp430
+null
 or1k
 pic
 ppc.as
[XX] db/cmd/cmd_list Print the asm/analysis plugins
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc La =
-- stdout
--- expected
+++ actual
@@ -26,6 +26,7 @@
 _d__  16         mcs96       LGPL3   condrets car
 adAe  16 32 64   mips        BSD     Capstone MIPS disassembler
 _dA_  16         msp430      LGPL3   msp430 disassembly plugin
+adA_  16 32 64   null        MIT     no disassemble (by pancake) v1.0.0
 _dA_  32         or1k        LGPL3   OpenRISC 1000
 _dAe  8          pic         LGPL3   PIC disassembler
 a___  32 64      ppc.as      LGPL3   as PPC Assembler (use RZ_PPC_AS environment) (by eagleoflqj)
```
https://github.com/rizinorg/rizin/runs/6842167345?check_suite_focus=true#step:12:122

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Thanks for your contribution :)

**Comment by bdemick** [comment]
You're welcome, happy to help!

**Pull request merged**
