### PR TITLE
Refactor output modes to use enum

### LINKED ISSUE #489: Refactor output modes to use enum
Currently you can often see in the code the following pattern:
```c
RZ_API void rz_core_task_list(RzCore *core, int mode) {
    if (mode == 'j') {
         ...
    }
}
```
In some cases it looks like that:
```c
RZ_API int rz_core_disasm_pde(RzCore *core, int nb_opcodes, int mode) {
    if (mode == RZ_MODE_JSON) {
        ...
    }
}
```
Sometimes there is no "mode" word, and it looks like that:
```
RZ_API void rz_analysis_xrefs_list(RzAnalysis *analysis, int rad) {
    ...
    if (rad == 'j') {
        ...
    }
```

I recommend to search for `int mode` and `char mode` patterns in the code.

It prevents catching some errors at the compilation time and reduces the readability.
Should be refactored to use enum instead, across the whole Rizin code.

After everything ported, the following hardcoded values should be removed from `librz/include/rz_types.h`:
```c
#define RZ_MODE_PRINT     0x000
#define RZ_MODE_SET       0x002
#define RZ_MODE_SIMPLE    0x004
#define RZ_MODE_JSON      0x008
#define RZ_MODE_SIMPLEST  0x020
```

See, for example:
```
librz/util/range.c
314:int rz_range_list(RRange *rgs, int rad) {

librz/io/io_cache.c
93:RZ_API bool rz_io_cache_list(RzIO *io, int rad) {

librz/main/rz-bin.c
63:static RzOutputMode rad2outputmode(int rad) {
471:static int rabin_do_operation(RzBin *bin, const char *op, int rad, const char *output, const char *file) {
622:static void __listPlugins(RzBin *bin, const char *plugin_name, PJ *pj, int rad) {
656:    int rad = 0;

librz/core/core_private.h
123:RZ_IPI bool rz_core_debug_reg_list(RzCore *core, int type, int size, bool skip_covered, PJ *pj, int rad, const char *use_color);

librz/core/cdebug.c
300:RZ_IPI bool rz_core_debug_reg_list(RzCore *core, int type, int size, bool skip_covered, PJ *pj, int rad, const char *use_color) {

librz/core/cmd/cmd_flag.c
734:    int rad;
759:static void print_function_labels_for(RzAnalysisFunction *fcn, int rad, PJ *pj) {
772:static void print_function_labels(RzAnalysis *analysis, RzAnalysisFunction *fcn, int rad) {

librz/core/canalysis.c
4157:static bool found_xref(RzCore *core, ut64 at, ut64 xref_to, RzAnalysisXRefType type, PJ *pj, int rad, int cfg_debug, bool cfg_analysis_strings) {
4225:RZ_API int rz_core_analysis_search_xrefs(RzCore *core, ut64 from, ut64 to, PJ *pj, int rad) {

librz/core/cmd/cmd_analysis.c
7005:   int rad;

librz/debug/ddesc.c
71:RZ_API int rz_debug_desc_list(RzDebug *dbg, int rad) {

librz/flag/flag.c
374:RZ_API void rz_flag_list(RzFlag *f, int rad, const char *pfx) {

librz/debug/p/bfvm.c
273:RZ_API void bfvm_show_regs(BfvmCPU *c, int rad) {
289:RZ_API void bfvm_maps(BfvmCPU *c, int rad) {

librz/cons/pal.c
526:RZ_API void rz_cons_pal_list(int rad, const char *arg) {

librz/include/rz_flag.h
97:RZ_API void rz_flag_list(RzFlag *f, int rad, const char *pfx);

librz/include/rz_debug.h
518:RZ_API int rz_debug_desc_list(RzDebug *dbg, int rad);

librz/include/rz_cons.h
953:RZ_API void rz_cons_pal_list(int rad, const char *arg);

librz/include/rz_analysis.h
55:     int rad;

librz/include/rz_io.h
394:RZ_API bool rz_io_cache_list(RzIO *io, int rad);

librz/include/rz_core.h
670:RZ_API int rz_core_analysis_search_xrefs(RzCore *core, ut64 from, ut64 to, PJ *pj, int rad);

librz/include/rz_util/rz_range.h
35:RZ_API int rz_range_list(RRange *rgs, int rad);
```

### PR DESCRIPTION
**Pull request by valdaarhun**
Original PR: https://github.com/rizinorg/rizin/pull/929

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Refactored output modes to use enum. int mode and char mode patterns in the code have been replaced with RzOutputMode enum type.

_Refactoring is still in progress._

**Test plan**

...

**Closing issues**

closes #489

### CODE REVIEW

**Comment by XVilka** [comment]
1. Wrongly comitted `librz/main/rz-ax.c~HEAD `
2. It breaks many tests:

The test breakage happens because you didn't change the places where this function is called so they use the old "modes" which don't match a new parameter.

```
[XX] db/cmd/cmd_avr avra and avrr msvc x86
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aar
avra
?e --
avrr
acll
' bins/pe/cpp-msvc-x86.exe
-- stdout
@@ -116,22 +116,5 @@
 
 --
 [Album]
-  (vtable at 0x412164)
-nth name           addr vt_offset type
---------------------------------------
-1   virtual_0  0x40105d 0x0       VIRTUAL
-2   virtual_4  0x4010a7 0x4       VIRTUAL
-
 [InAbsentia: Album]
-  (vtable at 0x4121a4)
-nth name           addr vt_offset type
---------------------------------------
-1   virtual_0  0x401088 0x0       VIRTUAL
-2   virtual_4  0x4010b3 0x4       VIRTUAL
-
 [type_info]
-  (vtable at 0x4121fc)
-nth name           addr vt_offset type
---------------------------------------
-1   virtual_0  0x401136 0x0       VIRTUAL
-

[XX] db/cmd/cmd_acll PR#898
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aaa
acll
' bins/elf/analysis/classes_Polygon
-- stdout
@@ -1,46 +1,6 @@
 [Polygon]
-  (vtable at 0x3d20)
-nth name          addr vt_offset type
--------------------------------------
-1   Polygon     0x11ea -1        CONSTRUCTOR
-2   Polygon1    0x121e -1        DEFAULT
-3   Poly        0x122e -1        DEFAULT
-4   ~Polygon    0x123e -1        DESTRUCTOR
-5   set_values  0x14b6 -1        DEFAULT
-6   area        0x14e0 0x0       VIRTUAL
-7   sides       0x14f4 0x8       VIRTUAL
-
 [Rectangle: Polygon]
-  (vtable at 0x3d00)
-nth name          addr vt_offset type
--------------------------------------
-1   area        0x1508 0x0       VIRTUAL
-2   sides       0x1528 0x8       VIRTUAL
-3   Rectangle   0x1578 -1        CONSTRUCTOR
-4   ~Rectangle  0x15a6 -1        DESTRUCTOR
-
 [Triangle: Polygon]
-  (vtable at 0x3ce0)
-nth name         addr vt_offset type
-------------------------------------
-1   area       0x153c 0x0       VIRTUAL
-2   sides      0x1564 0x8       VIRTUAL
-3   Triangle   0x15d4 -1        CONSTRUCTOR
-4   ~Triangle  0x1602 -1        DESTRUCTOR
-
 [std::basic_ostream_char__std::char_traits_char_____std::endl_char__std]
-nth name                   addr vt_offset type
-----------------------------------------------
-1   char_traits<char> >  0x3fd0 -1        DEFAULT
-
 [std::ios_base::Init]
-nth name     addr vt_offset type
---------------------------------
-1   Init   0x3fb0 -1        DEFAULT
-2   ~Init  0x3ff8 -1        DEFAULT
-
 [std::ostream]
-nth name          addr vt_offset type
--------------------------------------
-1   operator<<  0x3fb8 -1        DEFAULT
-


-- stderr
Warning: run rizin with -e io.cache=true to fix relocations in disassembly
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[XX] db/cmd/cmd_acll acll list class detailed
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'aaa
acll
' bins/elf/analysis/elf-virtualtable
-- stdout
@@ -1,45 +1,7 @@
 [A]
-  (vtable at 0x400d28)
-nth name            addr vt_offset type
----------------------------------------
-1   greet       0x400ac8 0x0       VIRTUAL
-2   printValue  0x400af4 0x8       VIRTUAL
-3   A           0x400b36 -1        CONSTRUCTOR
-
 [B: A]
-  (vtable at 0x400d08)
-nth name                addr vt_offset type
--------------------------------------------
-1   B               0x400b4e -1        CONSTRUCTOR
-2   printValue      0x400b82 0x8       VIRTUAL
-3   method.A.greet  0x400ac8 0x0       VIRTUAL
-
 [C: A]
-  (vtable at 0x400ce8)
-nth name                addr vt_offset type
--------------------------------------------
-1   C               0x400bc4 -1        CONSTRUCTOR
-2   printValue      0x400bf8 0x8       VIRTUAL
-3   method.A.greet  0x400ac8 0x0       VIRTUAL
-
 [std::basic_ostream_char__std::char_traits_char_____std::endl_char__std]
-nth name                     addr vt_offset type
-------------------------------------------------
-1   char_traits<char> >  0x6012a8 -1        DEFAULT
-
 [std::basic_ostream_char__std::char_traits_char_____std::operator____std]
-nth name                     addr vt_offset type
-------------------------------------------------
-1   char_traits<char> >  0x601298 -1        DEFAULT
-
 [std::ios_base::Init]
-nth name       addr vt_offset type
-----------------------------------
-1   Init   0x601278 -1        DEFAULT
-2   ~Init  0x601290 -1        DEFAULT
-
 [std::ostream]
-nth name            addr vt_offset type
----------------------------------------
-1   operator<<  0x6012a0 -1        DEFAULT
-


-- stderr
[ ] Analyze all flags starting with sym. and entry0 (aa)
[
[x] Analyze all flags starting with sym. and entry0 (aa)

[XX] db/cmd/cmd_ac acvf
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ac A
ac B
ac C
acv A 0x00400d28 0x0 0x10
acv B 0x00400d08 0x0 0x10
acv C 0x00400ce8 0x0 0x10
acll
acvf 0x0 A
acvf 0x8 B
acvf 0x16 C dasdass
acvf 0x0
acvf -50
acvf 0x0 000ASDASdjpsadoaspdjasdaspodasDDD
acv A 0x00400d28 0x0
' bins/elf/analysis/elf-virtualtable
-- stdout
@@ -1,9 +1,6 @@
 [A]
-  (vtable at 0x400d28)
 [B]
-  (vtable at 0x400d08)
 [C]
-  (vtable at 0x400ce8)
```
https://builds.sr.ht/~xvilka/job/474974#task-test-0

**Comment by valdaarhun** [comment]
1. I think I accidentally committed `librz/main/rz-ax.c~HEAD` while merging from upstream and resolving conflicts. I'll uncommit this.
2. Should I progress by refactoring a few files at a time while ensuring that the function declarations, definitions and calls are all changed at the same time?

**Comment by XVilka** [comment]
@valdaarhun yes, change one file and all callers of functions from that file.

**Comment by wargio** [comment]
i would still go with function by function.

**Comment by valdaarhun** [comment]
I think I have messed up this branch while updating and resolving conflicts. I think it'll be better if I close this issue and start from scratch in a new branch.

**Pull request closed without merging**
