### PR TITLE
Cherrypicks for the 0.3.1 release

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
Fixes required for Cutter 2.0.4, see https://github.com/rizinorg/cutter/milestone/23
Also imported fixes for bugs reported by distributions (please check if I imported everything):
- https://github.com/gentoo/gentoo/tree/master/dev-util/rizin/files

**Test plan**

CI is green

### CODE REVIEW

**Comment by ret2libc** [comment]
LGTM so far

**Comment by wargio** [comment]
please add also the commit for the bottleneck on dex

**Comment by XVilka** [comment]
@wargio it's optimization-only patch, not exactly a bugfix, are you sure it should be in the 0.3.1?

**Comment by wargio** [comment]
yes. the dex code was sooooo slow. it took 3-4 mins to open an 8MB dex and with that 30 secs

**Comment by wargio** [comment]
also add the timeout commit

**Pull request merged**
