### PR TITLE
Capstone v5

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

An updated version of abandoned https://github.com/rizinorg/rizin/pull/345

I also set the capstone version to the latest 5.0 release candidate: https://github.com/capstone-engine/capstone/releases/tag/5.0-rc2

**Test plan**

CI is green

See also related https://github.com/rizinorg/rizin/issues/3210

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Also enable these:
https://github.com/rizinorg/rizin/blob/907e0981c58bc32e1622feadc165284b69deb542/test/db/asm/arm_32#L361
https://github.com/rizinorg/rizin/blob/907e0981c58bc32e1622feadc165284b69deb542/test/db/asm/arm_64#L467

**Comment by XVilka** [comment]
@Rot127 assigned to you since it's closely related to the auto-sync work. Feel free to modify/update/etc

**Comment by XVilka** [comment]
A prerequisite for https://github.com/rizinorg/rizin/pull/3463 to be merged once it's done.

**Comment by XVilka** [comment]
Too many broken things in ARM and PPC. We probably should wait first until all our ARM, PPC, and ARM64 auto-sync pull requests are merged first, before updating the capstone. @imbillow it would mean that to keep the build green, we will have to keep the Tricore work in a separate branch(es) for now and rebase it periodically on top of the latest `dev`. Once these merged, we could port all our tests to them and migrate to the capstone-next, skipping the `v5` version all together.

@Rot127 @wargio @ret2libc @thestr4ng3r  thoughts about this?

**Comment by wargio** [comment]
wow, that is indeed very broken
I do prefer the PRs to be merged here and then we can merge (no-squash) to dev later, once everything is green

**Comment by Rot127** [comment]
>  Once these merged, we could port all our tests to them and migrate to the capstone-next, skipping the v5 version all together.

This would effectively mean to skip CS `v5` in favor of CS `v5.1` (or whatever it might be named)?

I am very in favor of this!

**Pull request closed without merging**
