### PR TITLE
elfsymbols: fix warning on non pointer check

### PR DESCRIPTION
**Pull request by devnexen**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Comment by ghost** [comment]
Do you have an example?

**Comment by ghost** [comment]
The section->name check was wrong indeed, but if you could add test or an example it could be great.

**Comment by thestr4ng3r** [comment]
It might be hard to find an example for this since the change was probably only made because of the warning:
```
../librz/bin/format/elf/elf_symbols.c:657:26: warning: address of array 'section->name' will always evaluate to 'true' [-Wpointer-bool-conversion]
        if (section && section->name && is_section_local_symbol(bin, symbol)) {
                    ~~ ~~~~~~~~~^~~~
1 warning generated.
```
@08A would you say checking for `section->name[0] != '\0'` makes sense vs. not checking here at all and just letting `rz_str_ncpy(elf_symbol->name, ..` copy the empty string?

**Comment by ghost** [comment]
> It might be hard to find an example for this since the change was probably only made because of the warning:
> 
> ```
> ../librz/bin/format/elf/elf_symbols.c:657:26: warning: address of array 'section->name' will always evaluate to 'true' [-Wpointer-bool-conversion]
>         if (section && section->name && is_section_local_symbol(bin, symbol)) {
>                     ~~ ~~~~~~~~~^~~~
> 1 warning generated.
> ```
> 
> @08A would you say checking for `section->name[0] != '\0'` makes sense vs. not checking here at all and just letting `rz_str_ncpy(elf_symbol->name, ..` copy the empty string?

Checking section->name[0] make no sense.

**Comment by thestr4ng3r** [comment]
Check removed

**Pull request merged**
