### PR TITLE
Remove citem

### PR DESCRIPTION
**Pull request by Maijin**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Removing citem which is used by `i.` command.  A dup command of `pdj`
E.g.

`[XXX]>i.`
`{"type":"code","perm":"r-x","size":1,"addr":4294983804,"next":4294983805,"prev":4294983799,"sectname":"0.__TEXT.__text","data":"push rbp"}`

### CODE REVIEW

**Comment by ret2libc** [comment]
How are they dupped?

```
[0x000067d0]> pdj 1
[{"offset":26576,"esil":"","refptr":false,"fcn_addr":0,"fcn_last":0,"size":4,"opcode":"endbr64","disasm":"endbr64","bytes":"f30f1efa","family":"cpu","type":"null","reloc":false,"type_num":0,"type2_num":0,"flags":["entry0","rip"]}]
[0x000067d0]> i.
{"type":"code","perm":"r-x","size":4,"addr":26576,"next":26580,"prev":26573,"sectname":".text","data":"endbr64"}
```
They seem different to me. `i.` looks like `vmmap` in gdb peda, no?

**Comment by Maijin** [comment]
Here are other considerations for killing:

- It's a dup of `iSj.`/`omj` (mapping) and `pdJ` (which globs everything already sections+opcode etc.)
- `i.` is not a j ending command so it shouldn't print json
- it doesn't seem to have any relation with the rest of `i` command especially `i`, it's a meli-melo of various commands.
- It's not tested

**Comment by thestr4ng3r** [comment]
What is a citem?

**Comment by Maijin** [comment]
"core item"

**Review by ret2libc — APPROVED** [review]
Ok for killing. It seems it's not even in the help, so definitely.

**Review by thestr4ng3r — APPROVED** [review]

**Comment by ret2libc** [comment]
Merged, thanks!

**Pull request merged**
