### PR TITLE
[RzIL] fix jmp & added bitvector type due limitation of int type

### LINKED ISSUE #1859: Use RzILBitVector directly in rzil_op_int_t
The int opcode currently looks like this:
```c
/**
 *  \struct rzil_op_int_t
 *  \brief op structure for `int` (val int : 's Bitv.t Value.sort -> word -> 's bitv)
 *
 *  int s x is a bitvector constant x of sort s.
 */
struct rzil_op_int_t {
	ut32 length; ///< s -- sort(type), length of bitvector
	int value; ///< x -- value of bitvector
};
```

It simply represents a constant bitvector value and in practice will be converted to RzILBitVector for further usage:
```c
void *rz_il_handler_int(RzILVM *vm, RzILOp *op, RzILOpArgType *type) {
	RzILOpInt *op_int = op->op.int_;

	ut32 length = op_int->length;
	int value = op_int->value;
	RzILBitVector *bv = rz_il_bv_new_from_ut32(length, value);

	*type = RZIL_OP_ARG_BITV;
	return bv;
}
```

So the op could actually be just:
```c
struct rzil_op_int_t {
	RzILBitVector bv; // no pointer
};
```

It might make sense to do #1858 first, for less memory usage.

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- Adds RZIL_OP_BITV and removes RZIL_OP_INT because it is very limited to what ìnt` is on the host arch and platform
- Fixed type RZIL_OP_JMP to work and apply effect.
- Implemented  `rz_il_bv_new_from_st32` `rz_il_bv_new_from_st64`

Closes https://github.com/rizinorg/rizin/issues/1859

### CODE REVIEW

**Comment by wargio** [comment]
Linked to https://github.com/rizinorg/rizin/issues/1918

**Comment by wargio** [comment]
fail on windows is a false positive.

**Review by XVilka — CHANGES_REQUESTED** [review]
Looks good, could you please add a unit test for those?
- `test/unit/test_il_*`

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
This should replace the int op entirely, otherwise it's redundant: https://github.com/rizinorg/rizin/issues/1859

**Comment by wargio** [comment]
if we do this, i think i should add a method to convert signed numbers to bitv

**Comment by XVilka** [comment]
Yes, please do. In fact, it was the original meaning of this operation,
just to show a representation, not to use it in the VM.

**Review by XVilka — APPROVED** [review]

**Pull request merged**
