### PR TITLE
Make Tests use x86.as only on x86 Host

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

x86.as depends an the `as` executable to be available, which usually on non-x86 isn't. I rewrote tests that didn't explicitly test this plugin to not use it and moved the others to archos.

**Test plan**

run tests on e.g. arm

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Review by ret2libc — COMMENTED** [review]
Why x86.as shouldn't be available on non-x86 machines? I think on Mac you can install gnu-binutils and you can have assemblers for other architectures anyway, no?

**Comment by wargio** [comment]
i believe the issue is valid.

**Comment by thestr4ng3r** [comment]
It is possible yes, like here for example:
https://github.com/rizinorg/rizin/blob/3f71f45c533e81fc6e5cc6c298709eeed3bf1144/.travis.yml#L48
You would have to set the `RZ_X86_AS` env var. I think the question is whether the entire test suite succeeding should depend on this to be available. An alternative would be to put it into `db/extras` or similar.

**Comment by Maijin** [comment]
It's a good first step but it only underlines a deeper issue/enhancement to work on. Imho x86.as should be killed completely because there is already `e asm.assembler`.

Imho rizin should automatically list the assembler available in asm.assembler wether it's then embedded (e.g x86.nz but also all the one available for other architectures), `r2pm` when installed (keystone) and the system's one (nasm, or other etc.) and show that to user also in e `asm.assembler`...

**Comment by ret2libc** [comment]
Anyway, ok to merge, do not let me block you ;)

**Pull request merged**
