### PR TITLE
Download submodules in appveyor

### PR DESCRIPTION
**Pull request by ret2libc**
It should fix https://ci.appveyor.com/project/rizinorg/rizin/builds/36726589 hopefully. Also, I hope to enable appveyor for PR that has "windows" in the name.

### CODE REVIEW

**Comment by wargio** [comment]
maybe is better to push the rz-pipe package to pip

**Comment by XVilka** [comment]
```
copy C:\Python38-x64\python.exe C:\Python38-x64\python3.exe
        1 file(s) copied.
python3 -m pip install "https://github.com/rizinorg/rz-pipe#egg=rzpipe&subdirectory=python"
Collecting rzpipe
  Downloading https://github.com/rizinorg/rz-pipe
  ERROR: Cannot unpack file C:\Users\appveyor\AppData\Local\Temp\1\pip-unpack-uyz3x440\rz-pipe (downloaded from C:\Users\appveyor\AppData\Local\Temp\1\pip-install-prlyt540\rzpipe, content-type: text/html; charset=utf-8); cannot detect archive format
ERROR: Cannot determine archive format of C:\Users\appveyor\AppData\Local\Temp\1\pip-install-prlyt540\rzpipe
WARNING: You are using pip version 20.0.2; however, version 20.3.1 is available.
You should consider upgrading via the 'C:\Python38-x64\python3.exe -m pip install --upgrade pip' command.
```

**Comment by thestr4ng3r** [comment]
Url should be git+https instead of https I think.

**Comment by ret2libc** [comment]
Ok, it's still red but that is known for the moment. I think we can merge, right @thestr4ng3r ?

**Review by XVilka — APPROVED** [review]

**Pull request merged**
