### PR TITLE
ci: switch to softprops/action-gh-release

### LINKED ISSUE #3357: Switch to another GitHub Action for producing releases
[`actions/create-release`](https://github.com/actions/create-release) and [`actions/upload-release-asset`](https://github.com/actions/upload-release-asset) are abandoned, both recommend using https://github.com/softprops/action-gh-release

It also affects other projects:
- rz-ghidra
- jsdec
- rz-retdec

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

**Test plan**

I could not test it correctly because it's used at the end of the release process... We would need to do a -beta release before 0.7.0 to make sure it works. Does that sound good?

**Closing issues**

Closes #3357

### CODE REVIEW

**Comment by XVilka** [comment]
@ret2libc you can test it in a fork

**Comment by ret2libc** [comment]
> @ret2libc you can test it in a fork

Ok, it's going to take a bit of time though as i have to setup docker login etc. in the fork so that it reaches the release point.

**Review by wargio — APPROVED** [review]

**Comment by ret2libc** [comment]
It works finally https://github.com/ret2libc/rizin/actions/runs/6459411870/job/17536447165 @XVilka

**Review by wargio — APPROVED** [review]
<3

**Pull request merged**
