### PR TITLE
Update `RZ_BIRTH` on every build

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr properly updates `RZ_BIRTH` (the timestamp shown by `rizin -v`) on every build i.e. every time `ninja` is invoked, instead of only every time a `meson.build` file is changed.

**Test plan**

Check manually whether the timestamp shown by `rizin -v` reflects the time of the last build after making a change to a `.c` or `.h` file. All CI builds should be green.

**Closing issues**

...

### CODE REVIEW

**Comment by kazarmy** [comment]
Updated the [head comment](https://github.com/rizinorg/rizin/pull/2799#issue-1299874188).

**Comment by ret2libc** [comment]
How many files are rebuilt when you don't change anything at all and you re-run ninja?

**Comment by kazarmy** [comment]
Three basically:

1. "rz_build.h"
2. "str_version.c" because it depends on "rz_build.h"
3. "librz_util.so.0.5.0" because it depends on "str_version.o"

**Review by thestr4ng3r — CHANGES_REQUESTED** [review]
That is quite a lot actually. Especially on slower devices, relinking rz_util can take a significant amount of time, and this also depends on python. So I don't think this is a good idea. Do you have any concrete use-case where you really need the exact build time rather than the configure time?

**Comment by XVilka** [comment]
Another solution would be to move the `rz_str_version` from RzUtil to somewhere else, it doesn't really belong here anyway.

**Comment by kazarmy** [comment]
> Especially on slower devices, relinking rz_util can take a significant amount of time, and this also depends on python.

I can have `str_version()` read the build timestamp from a file, instead of the timestamp being compiled in as part of librz_util. Would that be okay?

> Do you have any concrete use-case where you really need the exact build time rather than the configure time?

Nothing significant really. It's just that the output of `rizin -v` that we ask as part of the GitHub bug report template may not be entirely accurate, particularly the git hash. But we are going to check with HEAD anyway so this issue is somewhat moot.

This pr is about the build timestamp rather than the git hash because that appears easier to fix, and fixing the git hash would require this kind of infra anyway.

**Comment by kazarmy** [comment]
> Another solution would be to move the `rz_str_version` from RzUtil to somewhere else, it doesn't really belong here anyway.

It could be in RzMain but I don't want to be delayed unnecessarily by a linking step either.

**Comment by ret2libc** [comment]
I'm not sure any of the other tools around do something like this. It is kinda expected that if you run two times "make" or ninja or whatever without changing the source code nothing is done. With this PR there is always something to compile. 

TBH I'm not sure the build time is even that useful. The git tag is probably more useful if it's accurate and it's also more stable than the time.

**Comment by kazarmy** [comment]
> TBH I'm not sure the build time is even that useful.

I agree, let's remove it ... never seen a tool include it as part of their `--version` output either. It's only that R2/Rizin has always been somewhat ... different.

**Comment by thestr4ng3r** [comment]
I do remember seeing the build time in many tools actually, for example the macos kernel:
```
florian-macbook:rizin florian$ uname -v
Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:29 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T8101
```

Linux:
```
florian@florian-desktop ~ $ uname -v
#1 SMP Sun Jul 3 12:57:10 CEST 2022
```

But it really is usually just the configure time, so just as we do it.

**Comment by kazarmy** [comment]
Oh ok

**Comment by kazarmy** [comment]
Still I don't see why the configure time is useful for a tool like Rizin, even for debugging purposes.

**Pull request closed without merging**
