### PR TITLE
Use fallback repo for xz 5.2.9

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The official xz repo has been disabled so this pr downloads xz ~~5.4.3~~ 5.2.9 from the Rizin fallback repo ~~(with same hash as before)~~.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Gentoo maintainers claim we should unroll even further, see https://bugs.gentoo.org/928134
Could you please roll back to 5.4.2? 

> This is the last release signed by Lasse Collin, the previous signer of xz-utils releases.

**Comment by kazarmy** [comment]
As per off-pr discussion, now downgrading to xz 5.2.9 507d08cfcfb7ad72a15d6215527aedf7e3ab2e6a

**Review by XVilka — APPROVED** [review]
Maybe worth making 0.7.3 with this.

**Comment by XVilka** [comment]
We need a patch for this for `clang-cl` on Windows:
```
In file included from ../subprojects/xz-5.2.9/src/liblzma/common/common.c:13:
In file included from ../subprojects/xz-5.2.9/src/liblzma/common/common.h:18:
..\subprojects\xz-5.2.9\src\common\tuklib_integer.h(605,2): error: call to undeclared library function '_BitScanReverse' with type 'unsigned char (unsigned long *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  605 |         _BitScanReverse(&i, n);
      |         ^
..\subprojects\xz-5.2.9\src\common\tuklib_integer.h(605,2): note: include the header <intrin.h> or explicitly provide a declaration for '_BitScanReverse'
..\subprojects\xz-5.2.9\src\common\tuklib_integer.h(707,2): error: call to undeclared library function '_BitScanForward' with type 'unsigned char (unsigned long *, unsigned long)'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  707 |         _BitScanForward(&i, n);
      |         ^
..\subprojects\xz-5.2.9\src\common\tuklib_integer.h(707,2): note: include the header <intrin.h> or explicitly provide a declaration for '_BitScanForward'
```

**Comment by kazarmy** [comment]
Patch is blind, hope it works

**Review by wargio — APPROVED** [review]

**Pull request merged**
