### PR TITLE
Add asan build for clang

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The reasoning for this pr goes like this:

1. The non-optimized OpenBSD builds seem to be far more stable than the optimized builds.
2. OpenBSD uses Clang.
3. Clang might treat some UB code differently from gcc.
4. Ergo, we should have an optimized asan build for Clang as well.

Fortunately, the default Clang version for GitHubCI's `ubuntu-20.04` is the same as for OpenBSD i.e. 11.

**Test plan**

All builds are green. The `linux-clang-tests-asan` build works as expected.

**Closing issues**

...

---

- The removal of the `pkgcfg_sanitize_libs` lines was done using

```sh
REGEX='pkgcfg_sanitize_libs,$' bash -c 'git grep -l "$REGEX" | xargs -n 1 sed -i "/$REGEX/d"'
```

- The addition of the `library_linkflags` lines was done using

```sh
REGEX="^\([[:blank:]]*\)\(soversion: rizin_libversion\)" bash -c 'git grep -l "$REGEX" | xargs -n 1 sed -i "s/$REGEX/\1link_args: library_linkflags,\n\1\2/"'
```

with some manual minor editing done afterwards.

- The addition of the `binrz` `executable_cflags` lines was done using

```sh
REGEX="^\([[:blank:]]*\)\(include_directories: \[platform_inc\],\)" bash -c 'git grep -l "$REGEX" | grep "binrz/\(rizin/\)\|\(rz-.*/\)" | xargs -n 1 sed -i "s/$REGEX/\1c_args: executable_cflags,\n\1\2/"'
```

- The addition of the `binrz` `executable_linkflags` lines was done using

```sh
REGEX="^\([[:blank:]]*\)\(implicit_include_directories: false\),\?" bash -c 'git grep -l "$REGEX" | grep "binrz/\(rizin/\)\|\(rz-.*/\)" | xargs -n 1 sed -i "s/$REGEX/\1\2,\n\1link_args: executable_linkflags/"'
```

- The editing of the test `meson.build` files was done manually.

- Info about what happens when `-shared-libasan` is used can be found [here](https://github.com/google/sanitizers/issues/1086).

### CODE REVIEW

**Comment by kazarmy** [comment]
Despite the redness, could this pr be merged so that me or others can work on the XX?

**Comment by wargio** [comment]
let me patch those XX

**Comment by wargio** [comment]
@kazarmy you should drop UndefinedBehaviorSanitizer because it throws a lot of false positives

**Comment by kazarmy** [comment]
let me see whether i can make UBSan happy ... this will take a while

**Review by ret2libc — APPROVED** [review]
I'm fine with this as long as it is run only on push, as you did.

**Comment by kazarmy** [comment]
Thanks but now I think that I should resolve the issues before merging, since a red dev might result in other problems slipping in unnoticed and there is no rush apparently.

**Comment by ret2libc** [comment]
Please convert it back to non-draft when ready to review.

**Comment by kazarmy** [comment]
Ok

**Comment by kazarmy** [comment]
https://github.com/rizinorg/rizin/pull/1910#issue-769858963 updated.

**Comment by wargio** [comment]
the usage of ASAN=1 or or ASAN=0 is because there is a bug when compiling with GCC the hexagon disassembler. essentially it makes the PC go OOM

**Comment by kazarmy** [comment]
yes, that ASAN=1 is still alive (it's under the "Build with Meson" task of `ci.yml`) ... otherwise i doubt the gcc asan build would be green

**Review by wargio — COMMENTED** [review]
this LGTM, but i feel that ret2libc should approve this.
anyway good job

**Comment by kazarmy** [comment]
thanks

**Comment by wargio** [comment]
@XVilka i guess we can merge this too

**Pull request merged**
