### PR TITLE
Fix UAF in rz-find when opening multiple files

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Based on https://github.com/rizinorg/rizin/pull/1018/ .

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
```
[XX] db/tools/rz_find rz-find recursive
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-find -q -s README bins/arm' -
-- stdout
--- expected
+++ actual
@@ -1,1 +1,0 @@
-0x0

-- stderr
^D

-- exit status: 
[XX] db/tools/rz_find rz-find multiple files
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-find -s README bins/arm/README bins/arm/README' -
-- stdout
--- expected
+++ actual
@@ -1,4 +1,0 @@
-File: bins/arm/README
-0x0
-File: bins/arm/README
-0x0
```

**Comment by XVilka** [comment]
Why not to push directly to that PR instead?

**Comment by ret2libc** [comment]
> Why not to push directly to that PR instead?

I wanted to try a slightly different way to fix the UAF. Then I realized i needed a bunch of commits from that PR

**Comment by ret2libc** [comment]
> ```
> [XX] db/tools/rz_find rz-find recursive
> RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-find -q -s README bins/arm' -
> -- stdout
> --- expected
> +++ actual
> @@ -1,1 +1,0 @@
> -0x0
> 
> -- stderr
> ^D
> 
> -- exit status: 
> [XX] db/tools/rz_find rz-find multiple files
> RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-find -s README bins/arm/README bins/arm/README' -
> -- stdout
> --- expected
> +++ actual
> @@ -1,4 +1,0 @@
> -File: bins/arm/README
> -0x0
> -File: bins/arm/README
> -0x0
> ```

I can't reproduce even with asan/ubsan :/

**Comment by wargio** [comment]
@ret2libc add `asan` in the name of the branch

**Comment by ret2libc** [comment]
> @ret2libc add `asan` in the name of the branch

I think *BSD CI don't care about the asan branch name

**Pull request closed without merging**
