### PR TITLE
Disable rz-pm (script) installation

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Prevents users from using the deprecated `rz-pm` script.

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
I am not sure we should disable it until the new **rz-pm** in Go *works*.

**Comment by ret2libc** [comment]
The fact is that the shell one is almost useless at this point ...

**Comment by wargio** [comment]
this is my point, i prefer to disable it.

**Comment by thestr4ng3r** [comment]
I would remove it completely

**Review by XVilka — APPROVED** [review]
Let's go with the disabling option, and we can remove it completely once the version in Go works.

**Pull request merged**
