### PR TITLE
Introduce `portable` build option to use relative paths

### LINKED ISSUE #392: Make Rizin work when the whole install dir is moved
**Is your feature request related to a problem? Please describe.**
Suppose you compile Rizin statically so that anyone can run it without installing everything. Now the problem is that actually Rizin expects some files in specific absolute directories (e.g. sdb calling convention, formats, etc.) and if you don't place your static installation exactly in the same prefix used during configuration time, things won't work.

**Describe the solution you'd like**
Provide a meson option to make Rizin "portable", meaning that all files are accessed relative to where the rizin executable is. This would allow to move the entire install directory without breaking things.

**Describe alternatives you've considered**
None.

**Additional context**
This requires a bit of work on meson.build side to make sure the defines in `rz_userconf.h` are relative, but also some adjustments at the code level to make sure paths are not made absolute. In particular, right now paths are used in an inconsistent way, with some paths that are already absolute, others that are relative to a dir and others relative to another. As part of this feature everything should be made uniform.

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible) TODO
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed) TODO

**Detailed description**

`portable` makes rizin use paths relative to the executable binary path,
so that all resource files (e.g. SDB files) can be retrieved without
having an hard-coded prefix in the binary. By doing so, rizin
installation directory can be moved from location to location and still
work. This is useful when having a static rizin that you want to execute
on another system.

It makes sure that all PATHs defined in rz_userconf.h are just relative
to the prefix and that, in the code, the prefix is prepended to all
these paths.

**Test plan**

Try to compile rizin with `-Dportable=true --default-library=static -Dstatic_runtime=true` and then use `DESTDIR=/tmp/rizin-install` while running `ninja install`. You should be able to run rizin from /tmp/rizin-install and then rename the /tmp/rizin-install directory. Everything should work even on a clean system. In particular, you should not get any warning about missing calling convention when opening a binary, because the calling convention should be found in the `/<rename-dir-rizin>/` directory.

**Closing issues**

Closes #392

### CODE REVIEW

**Comment by XVilka** [comment]
Could you also switch the CI static build to this?

**Comment by ret2libc** [comment]
This also needs proper testing on a Windows machine. I'll do it later.

**Comment by XVilka** [comment]
One unit test on static build is broken now:
```
test_stdoutstderr ERR
[XX] Fail at line 207: hello world and stderr string should be on stdout: expected This is on err
Hello World
, got Hello World
This is on err
.

test_interactive OK

stderr:
This is on err
This is on err
```

**Comment by ret2libc** [comment]
> This also needs proper testing on a Windows machine. I'll do it later.

Tested on Windows machine and it works. With this change, rizin on windows will use hard-coded prefix by default, unless you use the `-Dportable=true` option. This is in sync with linux behaviour.

**Comment by ret2libc** [comment]
Actually, before merging I'd like to double check on a clean container that the rizin-static artifact actually works.

**Review by yossizap — APPROVED** [review]
LGMT. Tested on windows as well.

**Review by XVilka — APPROVED** [review]
Works just fine in Linux:
```
~/bin/rizin-static 
[i] ℤ bin/rizin -v                                                                                                                                                                                                                13:58:33 
rizin 0.2.0-git @ linux-x86-64
commit: 1bfda0de50d8307201a0826dd6b1266c27d30eb9, build: 2021-02-24__19:37:00
~/bin/rizin-static
[i] ℤ bin/rizin -H                                                                                                                                                                                                                13:58:29 
RZ_VERSION=0.2.0-git
RZ_PREFIX=/home/user/bin/rizin-static
RZ_MAGICPATH=/home/user/bin/rizin-static/share/rizin/0.2.0-git/magic
RZ_INCDIR=/home/user/bin/rizin-static/include/librz
RZ_LIBDIR=/home/user/bin/rizin-static/lib
RZ_LIBEXT=so
RZ_RCONFIGHOME=/home/user/.config/rizin
RZ_RDATAHOME=/home/user/.local/share/rizin
RZ_RCACHEHOME=/home/user/.cache/rizin
RZ_LIBR_PLUGINS=/home/user/bin/rizin-static/lib/rizin/0.2.0-git
RZ_USER_PLUGINS=/home/user/.local/share/rizin/plugins
RZ_USER_ZIGNS=/home/user/.local/share/rizin/zigns
```

Do you think it would be possible to import it to the 0.1.1?

**Comment by ret2libc** [comment]
> Works just fine in Linux:
> ```
> ~/bin/rizin-static 
> [i] ℤ bin/rizin -v                                                                                                                                                                                                                13:58:33 
> rizin 0.2.0-git @ linux-x86-64
> commit: 1bfda0de50d8307201a0826dd6b1266c27d30eb9, build: 2021-02-24__19:37:00
> ~/bin/rizin-static
> [i] ℤ bin/rizin -H                                                                                                                                                                                                                13:58:29 
> RZ_VERSION=0.2.0-git
> RZ_PREFIX=/home/user/bin/rizin-static
> RZ_MAGICPATH=/home/user/bin/rizin-static/share/rizin/0.2.0-git/magic
> RZ_INCDIR=/home/user/bin/rizin-static/include/librz
> RZ_LIBDIR=/home/user/bin/rizin-static/lib
> RZ_LIBEXT=so
> RZ_RCONFIGHOME=/home/user/.config/rizin
> RZ_RDATAHOME=/home/user/.local/share/rizin
> RZ_RCACHEHOME=/home/user/.cache/rizin
> RZ_LIBR_PLUGINS=/home/user/bin/rizin-static/lib/rizin/0.2.0-git
> RZ_USER_PLUGINS=/home/user/.local/share/rizin/plugins
> RZ_USER_ZIGNS=/home/user/.local/share/rizin/zigns
> ```
> 
> Do you think it would be possible to import it to the 0.1.1? 

I doubt, it's really a big change imo and should go in 0.2.0

**Comment by XVilka** [comment]
I also wonder, if it makes sense to show `static` or `portable` in the `rizin -v` output. What do you think?

**Comment by ret2libc** [comment]
> I also wonder, if it makes sense to show `static` or `portable` in the `rizin -v` output. What do you think?

Maybe we should just export RZ_IS_PORTABLE in `rizin -H`? In `-v` there would be too many build-time options that we should show otherwise... whether you have linked some lib or not, etc.

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
**DO NOT SQUASH**

**Pull request merged**
