### PR TITLE
Exclude external lib of analysis (clang CI)

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**
remove shlr/capstone and shlr/sdb of the analysis loop

PS: list all external lib that should be exclude

**Test plan**
...

**Closing issues**
...

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
Please also add `shlr/tree-sitter` here.

**Review by ret2libc — APPROVED** [review]

**Comment by ret2libc** [comment]
Oh, @XVilka is right. Yeah add tree-sitter as well.

**Comment by ghost** [comment]
--exclude doesn't work if the output format isn't html...
So i had a small 'hack' to solve this.

**Comment by ghost** [comment]
2021-01-15-110806_476x707_scrot

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
