### PR TITLE
Bump Capstone to newest next

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

I would wait for the weekend release before merging. But this way we can run the tests.

Regression PR: https://github.com/capstone-engine/capstone/pull/2575

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by Rot127** [comment]
Ignore the mismatches in ids for now please. Fix them when a tag was added.

**Review by XVilka — CHANGES_REQUESTED** [review]
Please rebase on top of the latest `dev` to fix the CI

**Review by XVilka — APPROVED** [review]
@Rot127 maybe merge this early? We can update the capstone commit one more time at a later stage if necessary.

**Comment by Rot127** [comment]
Sure. Why not.
I rebase a last time.

**Comment by wargio** [comment]
This still does not include mips stuff, right?

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
