### PR TITLE
Various fixes for windows

### PR DESCRIPTION
**Pull request by GustavoLCR**
# DO NOT SQUASH

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

* Fix file sharing permission with `rz_sys_open(O_TEMPORARY)`
* Implement `rz_sys_pipe()`
* Implement `rz_sys_clearenv()`
* Use the CRT function `_wputenv_s()` and `_wdupenv_s()` for setting/getting environment variables
* Fix `rz_sys_set_environ()`
* Fix some XP incompatibility
* Use wide version of APIs
* Remove unused/unnecessary function pointers

**Test plan**

Tests pass

**Closing issues**

None

### CODE REVIEW

**Comment by XVilka** [comment]
Looks like a small regression:
```

[XX] db/tools/rz_bin rz-bin -S, -SS, -rS and -rSS file elf
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '%RZ_BIN_PREFIX=prixfixe
!rz-bin -S ${RZ_FILE}
!rz-bin -SS ${RZ_FILE}
' bins/elf/analysis/x86-helloworld-gcc
-- stdout
--- expected
+++ actual
@@ --1,49 +-1,49 @@
 [Sections]
-paddr      size  vaddr      vsize align perm name               type       flags         
---------------------------------------------------------------------------------------------------
-0x00000000 0x0   ---------- 0x0   0x0   ---- prixfixe.                   NULL       
-0x00000134 0x13  0x08048134 0x13  0x0   -r-- prixfixe..interp            PROGBITS   alloc
-0x00000148 0x20  0x08048148 0x20  0x0   -r-- prixfixe..note.ABI-tag      NOTE       alloc
-0x00000168 0x24  0x08048168 0x24  0x0   -r-- prixfixe..note.gnu.build-id NOTE       alloc
-0x0000018c 0x20  0x0804818c 0x20  0x0   -r-- prixfixe..gnu.hash          GNU_HASH   alloc
-0x000001ac 0x50  0x080481ac 0x50  0x0   -r-- prixfixe..dynsym            DYNSYM     alloc
-0x000001fc 0x4a  0x080481fc 0x4a  0x0   -r-- prixfixe..dynstr            STRTAB     alloc
-0x00000246 0xa   0x08048246 0xa   0x0   -r-- prixfixe..gnu.version       VERSYM     alloc
-0x00000250 0x20  0x08048250 0x20  0x0   -r-- prixfixe..gnu.version_r     VERNEED    alloc
-0x00000270 0x8   0x08048270 0x8   0x0   -r-- prixfixe..rel.dyn           REL        alloc
-0x00000278 0x18  0x08048278 0x18  0x0   -r-- prixfixe..rel.plt           REL        alloc
-0x00000290 0x23  0x08048290 0x23  0x0   -r-x prixfixe..init              PROGBITS   alloc,execute
-0x000002c0 0x40  0x080482c0 0x40  0x0   -r-x prixfixe..plt               PROGBITS   alloc,execute
-0x00000300 0x194 0x08048300 0x194 0x0   -r-x prixfixe..text              PROGBITS   alloc,execute
-0x00000494 0x14  0x08048494 0x14  0x0   -r-x prixfixe..fini              PROGBITS   alloc,execute
-0x000004a8 0x15  0x080484a8 0x15  0x0   -r-- prixfixe..rodata            PROGBITS   alloc
-0x000004c0 0x2c  0x080484c0 0x2c  0x0   -r-- prixfixe..eh_frame_hdr      PROGBITS   alloc
-0x000004ec 0xb0  0x080484ec 0xb0  0x0   -r-- prixfixe..eh_frame          PROGBITS   alloc
-0x0000059c 0x4   0x0804959c 0x4   0x0   -rw- prixfixe..init_array        INIT_ARRAY write,alloc
-0x000005a0 0x4   0x080495a0 0x4   0x0   -rw- prixfixe..fini_array        FINI_ARRAY write,alloc
-0x000005a4 0x4   0x080495a4 0x4   0x0   -rw- prixfixe..jcr               PROGBITS   write,alloc
-0x000005a8 0xe8  0x080495a8 0xe8  0x0   -rw- prixfixe..dynamic           DYNAMIC    write,alloc
-0x00000690 0x4   0x08049690 0x4   0x0   -rw- prixfixe..got               PROGBITS   write,alloc
-0x00000694 0x18  0x08049694 0x18  0x0   -rw- prixfixe..got.plt           PROGBITS   write,alloc
-0x000006ac 0x8   0x080496ac 0x8   0x0   -rw- prixfixe..data              PROGBITS   write,alloc
-0x000006b4 0x0   0x080496b4 0x4   0x0   -rw- prixfixe..bss               NOBITS     write,alloc
-0x000006b4 0x11  ---------- 0x11  0x0   ---- prixfixe..comment           PROGBITS   merge,strings
-0x000006c5 0x106 ---------- 0x106 0x0   ---- prixfixe..shstrtab          STRTAB     
-0x00000c7c 0x450 ---------- 0x450 0x0   ---- prixfixe..symtab            SYMTAB     
-0x000010cc 0x257 ---------- 0x257 0x0   ---- prixfixe..strtab            STRTAB     
+paddr      size  vaddr      vsize align perm name               type       flags         
+-----------------------------------------------------------------------------------------
+0x00000000 0x0   ---------- 0x0   0x0   ----                    NULL       
+0x00000134 0x13  0x08048134 0x13  0x0   -r-- .interp            PROGBITS   alloc
+0x00000148 0x20  0x08048148 0x20  0x0   -r-- .note.ABI-tag      NOTE       alloc
+0x00000168 0x24  0x08048168 0x24  0x0   -r-- .note.gnu.build-id NOTE       alloc
+0x0000018c 0x20  0x0804818c 0x20  0x0   -r-- .gnu.hash          GNU_HASH   alloc
+0x000001ac 0x50  0x080481ac 0x50  0x0   -r-- .dynsym            DYNSYM     alloc
+0x000001fc 0x4a  0x080481fc 0x4a  0x0   -r-- .dynstr            STRTAB     alloc
+0x00000246 0xa   0x08048246 0xa   0x0   -r-- .gnu.version       VERSYM     alloc
+0x00000250 0x20  0x08048250 0x20  0x0   -r-- .gnu.version_r     VERNEED    alloc
+0x00000270 0x8   0x08048270 0x8   0x0   -r-- .rel.dyn           REL        alloc
+0x00000278 0x18  0x08048278 0x18  0x0   -r-- .rel.plt           REL        alloc
+0x00000290 0x23  0x08048290 0x23  0x0   -r-x .init              PROGBITS   alloc,execute
+0x000002c0 0x40  0x080482c0 0x40  0x0   -r-x .plt               PROGBITS   alloc,execute
+0x00000300 0x194 0x08048300 0x194 0x0   -r-x .text              PROGBITS   alloc,execute
+0x00000494 0x14  0x08048494 0x14  0x0   -r-x .fini              PROGBITS   alloc,execute
+0x000004a8 0x15  0x080484a8 0x15  0x0   -r-- .rodata            PROGBITS   alloc
+0x000004c0 0x2c  0x080484c0 0x2c  0x0   -r-- .eh_frame_hdr      PROGBITS   alloc
+0x000004ec 0xb0  0x080484ec 0xb0  0x0   -r-- .eh_frame          PROGBITS   alloc
+0x0000059c 0x4   0x0804959c 0x4   0x0   -rw- .init_array        INIT_ARRAY write,alloc
+0x000005a0 0x4   0x080495a0 0x4   0x0   -rw- .fini_array        FINI_ARRAY write,alloc
+0x000005a4 0x4   0x080495a4 0x4   0x0   -rw- .jcr               PROGBITS   write,alloc
+0x000005a8 0xe8  0x080495a8 0xe8  0x0   -rw- .dynamic           DYNAMIC    write,alloc
+0x00000690 0x4   0x08049690 0x4   0x0   -rw- .got               PROGBITS   write,alloc
+0x00000694 0x18  0x08049694 0x18  0x0   -rw- .got.plt           PROGBITS   write,alloc
+0x000006ac 0x8   0x080496ac 0x8   0x0   -rw- .data              PROGBITS   write,alloc
+0x000006b4 0x0   0x080496b4 0x4   0x0   -rw- .bss               NOBITS     write,alloc
+0x000006b4 0x11  ---------- 0x11  0x0   ---- .comment           PROGBITS   merge,strings
+0x000006c5 0x106 ---------- 0x106 0x0   ---- .shstrtab          STRTAB     
+0x00000c7c 0x450 ---------- 0x450 0x0   ---- .symtab            SYMTAB     
+0x000010cc 0x257 ---------- 0x257 0x0   ---- .strtab            STRTAB     
 [Segments]
-paddr      size  vaddr      vsize align  perm name         
---------------------------------------------------------------------
-0x00000034 0x100 0x08048034 0x100 0x4    -r-x prixfixe.PHDR
-0x00000134 0x13  0x08048134 0x13  0x1    -r-- prixfixe.INTERP
-0x00000000 0x59c 0x08048000 0x59c 0x1000 -r-x prixfixe.LOAD0
-0x0000059c 0x118 0x0804959c 0x11c 0x1000 -rw- prixfixe.LOAD1
-0x000005a8 0xe8  0x080495a8 0xe8  0x4    -rw- prixfixe.DYNAMIC
-0x00000148 0x44  0x08048148 0x44  0x4    -r-- prixfixe.NOTE
-0x000004c0 0x2c  0x080484c0 0x2c  0x4    -r-- prixfixe.GNU_EH_FRAME
-0x00000000 0x0   0x00000000 0x0   0x4    -rw- prixfixe.GNU_STACK
-0x00000000 0x34  0x08048000 0x34  0x0    -rw- prixfixe.ehdr
+paddr      size  vaddr      vsize align  perm name         
+-----------------------------------------------------------
+0x00000034 0x100 0x08048034 0x100 0x4    -r-x PHDR
+0x00000134 0x13  0x08048134 0x13  0x1    -r-- INTERP
+0x00000000 0x59c 0x08048000 0x59c 0x1000 -r-x LOAD0
+0x0000059c 0x118 0x0804959c 0x11c 0x1000 -rw- LOAD1
+0x000005a8 0xe8  0x080495a8 0xe8  0x4    -rw- DYNAMIC
+0x00000148 0x44  0x08048148 0x44  0x4    -r-- NOTE
+0x000004c0 0x2c  0x080484c0 0x2c  0x4    -r-- GNU_EH_FRAME
+0x00000000 0x0   0x00000000 0x0   0x4    -rw- GNU_STACK
+0x00000000 0x34  0x08048000 0x34  0x0    -rw- ehdr
```

**Review by XVilka — APPROVED** [review]
You mentioned the Windows XP fix - does it mean Rizin will work on it again (we focused on the Windows 7+ API few years ago, AFAIR)?

**Comment by XVilka** [comment]
Note, CI failure is unrelated to Rizin:
```
pkgconfiglite v0.28
pkgconfiglite package files install completed. Performing other installation steps.
Downloading pkgconfiglite 64 bit
  from 'http://downloads.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip'
Progress: 100% - Completed download of C:\Users\runneradmin\AppData\Local\Temp\chocolatey\pkgconfiglite\0.28\pkg-config-lite-0.28-1_bin-win32.zip (46.57 KB).
Download of pkg-config-lite-0.28-1_bin-win32.zip (46.57 KB) completed.
WARNING: Missing package checksums are not allowed (by default for HTTP/FTP, 
 HTTPS when feature 'allowEmptyChecksumsSecure' is disabled) for 
 safety and security reasons. Although we strongly advise against it, 
 if you need this functionality, please set the feature 
 'allowEmptyChecksums' ('choco feature enable -n 
 allowEmptyChecksums') 
 or pass in the option '--allow-empty-checksums'. You can also pass 
 checksums at runtime (recommended). See choco install -? for details.
The integrity of the file 'pkg-config-lite-0.28-1_bin-win32.zip' from 'http://downloads.sourceforge.net/project/pkgconfiglite/0.28-1/pkg-config-lite-0.28-1_bin-win32.zip' has not been verified by a checksum in the package scripts.
Do you wish to allow the install to continue (not recommended)?
[Y] Yes [N] No (default is "N")
  Confirmation (`-y`) is set.
  Respond within 30 seconds or the default selection will be chosen.
ERROR: Empty checksums are no longer allowed by default for non-secure sources. Please ask the maintainer to add checksums to this package. In the meantime if you need this package to work correctly, please enable the feature allowEmptyChecksums, provide the runtime switch '--allow-empty-checksums', or pass in checksums at runtime (recommended - see 'choco install -?' / 'choco upgrade -?' for details). It is strongly advised against allowing empty checksums for non-internal HTTP/FTP sources.
The install of pkgconfiglite was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\chocolateyInstall.ps1'.
 See log for details.
Chocolatey installed 1/2 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).
Failures
 - pkgconfiglite (exited -1) - Error while running 'C:\ProgramData\chocolatey\lib\pkgconfiglite\tools\chocolateyInstall.ps1'.
 See log for details.
```
https://github.com/rizinorg/rizin/runs/7453165167?check_suite_focus=true#step:4:54

**Review by ret2libc — COMMENTED** [review]
Why all the switches from TCHAR to WCHAR? As usual, I know almost 0 about Windows, but I read that TCHAR can be either WCHAR or char. It seems it would make sense to keep support for both, but I'm sure there's a reason :)

**Comment by GustavoLCR** [comment]
> You mentioned the Windows XP fix - does it mean Rizin will work on it again (we focused on the Windows 7+ API few years ago, AFAIR)?

@XVilka Not for now, we still depend on conditional variables and libzip depends on the bcrypt library

> Why all the switches from TCHAR to WCHAR? As usual, I know almost 0 about Windows, but I read that TCHAR can be either WCHAR or char. It seems it would make sense to keep support for both, but I'm sure there's a reason :)

@ret2libc Using TCHAR makes Unicode compatibility conditional, which can cause problems if, for example, we are using a path that can't be represented by the current character codepage.
We don't need that as internally we convert everything to utf8 anyways, so its better to use WCHAR and the W version of the apis to assure compatibility

**Review by XVilka — APPROVED** [review]

**Pull request merged**
