### PR TITLE
Remove p3 command

### PR DESCRIPTION
**Pull request by Maijin**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Remove p3 stereogram command. (doc/3D has been removed already)

### CODE REVIEW

**Review by thestr4ng3r — APPROVED** [review]

**Review by wargio — APPROVED** [review]
Never used it and seems useless.

**Review by ret2libc — APPROVED** [review]

**Comment by Maijin** [comment]
any idea why it's not green?

**Comment by wargio** [comment]
`profiling:/home/runner/work/rizin/rizin/build/librzsdb.a.p/shlr_sdb_src_json.c.gcda:Merge mismatch for function 0` is spamming.

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
Thanks!

**Pull request merged**
