### PR TITLE
[AArch64/ARM64] Update to Capstone `v6`/`auto-sync`

### PR DESCRIPTION
**Pull request by Rot127**
based on https://github.com/rizinorg/rizin/pull/3648

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Updates the AArch64/ARM64 module to Capstone's v6/auto-sync version.

Requires https://github.com/capstone-engine/capstone/pull/2026 to be merged.

**Test plan**

- Test build with different CS ver. < 6
- All green

**Closing issues**

...

### CODE REVIEW

**Comment by Rot127** [comment]
Because of the ARM64 -> AArch64 renaming the il and esil file has too many changes for using  `#if CS_VERSION < 6` everywhere (IMHO).

What would you prefer to do in this case?
- Having a pre-v6 CS file and select the correct one during build (somehow).
- Duplicate code and wrap the correct version in a big `#if #else` within the file.

**Comment by XVilka** [comment]
Rebase on top of the latest `dev`

**Comment by XVilka** [comment]
@Rot127 please rebase on top of the latest `dev` and to the latest commit in https://github.com/capstone-engine/capstone/pull/2026

**Comment by Rot127** [comment]
Superseded by #3963
(`capstone` must be in the branch name so the build with <v6 gets tested as well.)

**Pull request closed without merging**
