### PR TITLE
Convert `s` commands to newshell

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed). See https://github.com/rizinorg/book/pull/23
- [ ] Implement autocompletion

**Detailed description**

* Rename `sj`/`s*` and move them under `sH`. Remove `s=`
* Use `sd` for "seek delta", which moves relative to the current offset
* Enforce <cmd> <arg> syntax. So no more `s+16` but `s +16`. Command
  `sHr` is for redo history, `sHu` for undo history. If one wants to move
  relative to the current address, he needs to do `sd +10`/`sd -10`.
* Remove `ss` commands in favour of cmd.seek.silent. This was anyway
  used mainly for scripts, so no need to replicate all `s` commands
  under `ss`.

**Test plan**

Try all various s commands, visual mode undo/redo.

**Closing issues**

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Looks good. BTW visual mode code is horrid.

**Review by Maijin — APPROVED** [review]

**Comment by wargio** [comment]
This might really need to be squashed hard.

**Comment by ret2libc** [comment]
Damn, my bad.

**Review by Maijin — APPROVED** [review]
Did you see those cmd0 with so-1 in agraph.c?

**Review by XVilka — APPROVED** [review]
I suggest to merge this as is and lets test more manually. I bet not everything is caught with automated tests.

**Pull request merged**
