### PR TITLE
Add `agI` and `aoi` for printing RzIL statements

### PR DESCRIPTION
**Pull request by wargio**
# do not squash

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

`agI` outputs a graph of the IL statement at the current offset.

image

`aoi` outputs 1 or more IL statements at the current offset which can be pretty printed.

image

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Looks good, thanks!

**Comment by thestr4ng3r** [comment]
Generally looks good to me, but what about having `aoip <n>` instead of `aoi <p> pretty`? I expect the pretty-printing to be the command used most interactively so being able to type it fast will be beneficial.

**Comment by wargio** [comment]
it makes sense. yes, i can add this.

**Comment by wargio** [comment]
@XVilka @thestr4ng3r i have modified the code. now it adds the following
```
[0x00000000]> aoi?
Usage: aoi[p]   # Print the RzIL of next N instructions
| aoi [<n_instructions>]  # Print the RzIL of next N instructions
| aoip [<n_instructions>] # Pretty print the RzIL of next N instructions
```

# DO NOT SQUASH

**Review by XVilka — APPROVED** [review]

**Pull request merged**
