### PR TITLE
Add note regarding Python 3.6 compatibility

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr adds a note regarding the need for scripts to run under Python 3.6.

**Test plan**

The note makes sense.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
It's actually even Debian Wheezy but I was too slow to suggest an edit 🐌

**Comment by kazarmy** [comment]
According to https://www.debian.org/releases/, Wheezy is already obsolete.

**Comment by XVilka** [comment]
@kazarmy, I am willing to bet that someone somewhere on this planet still runs it. With the help of Muon and TinyCC (or cproc) we could even try to build Rizin for earlier versions.

**Comment by kazarmy** [comment]
Since P(someone is running Debian Wheezy) is probably 1 given what @XVilka knows, that's hardly a fair bet.

**Pull request merged**
