### PR TITLE
Spin Linux `dk 9` tests

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

For the Linux `dk 9` tests, this pr adds an infinite loop after the `dk 9` before the `dc`. They are added because of the suspicion that the tests were failing because the test binary had been terminated by other means, likely SIGSEGV.

**Test plan**

The Linux `dk 9` tests fail no more.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
@kazarmy tests are green looks like with this change

**Review by XVilka — APPROVED** [review]

**Comment by kazarmy** [comment]
didn't work though https://github.com/rizinorg/rizin/actions/runs/11054804707/job/30712486369#step:12:36

**Comment by XVilka** [comment]
Right, still happens:
```

[XX] 312 ms   db/archos/linux-x64/dbg dk 9
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -a x86 -d -qc 'dk 9
wx ebfe  # infinite loop
dc
' bins/elf/analysis/calls_x64
-- stderr
--- expected
+++ actual
@@ -1,1 +1,0 @@
-child received signal 9
```

**Comment by wargio** [comment]
i start feeling that debug tests will keep being unreliable till we refactor all the debug code

**Pull request merged**
