### PR TITLE
Refactor: Use HtSP for storing plugins.

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Refactor: Use `HtSP` for storing plugins.
This saves iterations when searching for a plugin of a given name. It also allows to save plugin configurations and data in hash table, all addressed by their name. Hence, usage is more streamlined.

**Test plan**

All green

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — COMMENTED** [review]
Nice idea, it is probably worth to put it into 0.8.0, along/before RzArch.

**Comment by Rot127** [comment]
For the failing tests. Should we sort them alphabetically. Or would you say it doesn't matter?

**Comment by XVilka** [comment]
> For the failing tests. Should we sort them alphabetically. Or would you say it doesn't matter?

Let's go with the alphabetical sorting.

**Comment by wargio** [comment]
> For the failing tests. Should we sort them alphabetically. Or would you say it doesn't matter?

does not matter, but for the sake of the tests, it should be sorted.

**Review by XVilka — CHANGES_REQUESTED** [review]
1. Please resend from the internal branch to trigger more CI jobs
2. Please fix these Windows tests:
```
[XX]   2 secs C:\projects\rizin\test\db\cmd\cmd_list Print the debug plugins
ANSICON=1 RZ_NOPLUGINS=1 C:\projects\rizin\rizin-vs2022_64-v0.8.0\bin\rizin.exe -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -qc Ld~!windbg,native =
-- stdout
--- expected
+++ actual
@@ -6,4 +6,4 @@
 6  ---  null     MIT
 7  ---  qnx      LGPL3
 8  ---  rap      LGPL3
-9  ---  winkd    LGPL3
+10  ---  winkd    LGPL3
[XX]   1 secs C:\projects\rizin\test\db\cmd\cmd_list Set the debug backend
ANSICON=1 RZ_NOPLUGINS=1 C:\projects\rizin\rizin-vs2022_64-v0.8.0\bin\rizin.exe -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -qc 'Ld null
Ld~!windbg,native
' =
-- stdout
--- expected
+++ actual
@@ -6,4 +6,4 @@
 6  dbg  null     MIT
 7  ---  qnx      LGPL3
 8  ---  rap      LGPL3
-9  ---  winkd    LGPL3
+10  ---  winkd    LGPL3
```

**Comment by Rot127** [comment]
Delete after merge: https://github.com/rizinorg/rizin/tree/plugin-management

**Comment by Rot127** [comment]
Succeeded by https://github.com/rizinorg/rizin/pull/4687

**Pull request closed without merging**
