### PR TITLE
Fix memory leak in rz_skiplist_insert()

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by thestr4ng3r** [comment]
Wouldn't it perhaps make more sense to free the `data` that is currently in the list and replace it with the new one?

**Comment by ret2libc** [comment]
A description of the PR with the mem leak it is trying to solve would help to understand if the fix is ok or not.

**Review by ret2libc — COMMENTED** [review]
Maybe the function should just return NULL if the element already exists? Otherwise it replaces data with another data that is essentially the same because the compare function returns 0.

**Comment by p371jah** [comment]
> Maybe the function should just return NULL if the element already exists? Otherwise it replaces data with another data that is essentially the same because the compare function returns 0.

So how to distinguish memory allocation error and duplication?

**Comment by ret2libc** [comment]
> > Maybe the function should just return NULL if the element already exists? Otherwise it replaces data with another data that is essentially the same because the compare function returns 0.
> 
> So how to distinguish memory allocation error and duplication?

If you have a function that only does insert any duplication is an error, in some sense :D Do we need to differentiate the two?

**Comment by XVilka** [comment]
@pelijah @ret2libc @thestr4ng3r  what was the decision on this one?

**Pull request closed without merging**
