### PR TITLE
Test static build

### PR DESCRIPTION
**Pull request by ret2libc**
TEST

### CODE REVIEW

**Comment by ret2libc** [comment]
```
[XX] db/esil/math div by zero 3 / 0
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ae 0,3,/
ae*
' =
-- stdout
--- expected
+++ actual
@@ -1,3 +1,3 @@
+ESIL TRAP type 3 code 0x00000000 divbyzero
 trap: 3
 trap-code: 0
-ESIL TRAP type 3 code 0x00000000 divbyzero



[XX] db/esil/math div 0 / 3
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'ae 3,0,/
ae*
' =
-- stdout
--- expected
+++ actual
@@ -1,3 +1,3 @@
+0x0
 trap: 0
 trap-code: 0
-0x0
```

**Comment by ret2libc** [comment]
@wargio it seems that this was changed in your recent PR. Could you check?

**Comment by wargio** [comment]
is because it is using directly printf. let me remove this directly and throw this at RZ_LOG_ERROR.

**Comment by XVilka** [comment]
Totally green.

**Pull request closed without merging**
