### PR TITLE
rizin-shell-parser: fix build with newest tree-sitter (again)

### PR DESCRIPTION
**Pull request by ajakk**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

```
    PR #4365 originally fixed this build failure with newer tree-sitter
    versions, but the relevant change for this was partially inadvertently
    reverted in #4165.
```
See #4365 for full rationale.
...

**Test plan**

Build passes with newest tree-sitter.
...

**Closing issues**

...

### CODE REVIEW

**Comment by ajakk** [comment]
I'd try upgrading tree-sitter but that's a bit beyond my capabilities here, sorry!

**Review by XVilka — APPROVED** [review]
cc @kazarmy

**Review by kazarmy — APPROVED** [review]
#4365?

Oh it's a generated file ... perhaps best if it was patched automatically post-hoc

**Review by ret2libc — CHANGES_REQUESTED** [review]
Marking this red. The file is auto-generated.

**Comment by XVilka** [comment]
@ajakk @arrowd, we published a new 0.7.2 release, which should also fix this problem in the release. As for `dev`, we will just regenerate parser using newer tree-sitter version.

https://github.com/rizinorg/rizin/releases/tag/v0.7.2

**Comment by kazarmy** [comment]
Superseded by #4338.

**Pull request closed without merging**
