### PR TITLE
rz_pvector_foreach: Check for zero vector length to prevent UB

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr cherry-picks the fix for the following error from #1910:

cbin-UB
(https://github.com/rizinorg/rizin/runs/4101766412?check_suite_focus=true#step:16:314)

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
Why is `it` NULL ? Is it because the pvector is empty?

**Comment by kazarmy** [comment]
Might be an `RzPVector` straight from an `rz_pvector_new()` but didn't check. Does it matter?

**Comment by kazarmy** [comment]
btw, the pr checks whether `it` is null, not whether `*it` is null

**Comment by kazarmy** [comment]
> Might be an RzPVector straight from an rz_pvector_new() but didn't check. Does it matter?

The point I was trying to make here is that

```c
RzPVector *a_vector = rz_pvector_new(NULL);
void **itr;
rz_pvector_foreach (a_vector, itr) {
        // ...
}
```

i.e. iterating over an empty `RzPVector` ... that shouldn't invoke UB, so it shouldn't be an issue as to whether there is a problem with the vector that triggered the UBSan runtime error -- the patch has to happen anyway.

**Comment by kazarmy** [comment]
Ok I'm going to follow https://patchwork.kernel.org/project/git/patch/20200125053834.GB744673@coredump.intra.peff.net/ and check whether the vector length is 0. Need to confirm whether this works first though.

**Comment by pelijah** [comment]
I don't understand. In case of `v.len = 0` a loop body won't be executed since you get `for (it = (vec)->v.a; it != (vec)->v.a; it++)`. Why this extra check is needed?

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
