### PR TITLE
Enable Travis CI for ARM, PPC, SYSZ

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Now we can enable Travis back. Removed all unnecessary stuff.

### CODE REVIEW

**Comment by XVilka** [comment]
cc @thestr4ng3r:
```
[XX] db/formats/spc700 SPC700: Open/iI
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc iI~machine[1] bins/spc700/bin.spc
-- stdout
@@ -1 +1,7 @@
 SPC700
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
-- stderr
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
WARNING: No calling convention defined for this file, analysis may be inaccurate.
```

**Review by thestr4ng3r — APPROVED** [review]

**Comment by XVilka** [comment]
It should skip debug tests for non-x86 platforms but for some reason it doesn't (it was working in radare2):
```
Skipping db/archos/linux-x64 because it does not match the current platform.
```

**Comment by XVilka** [comment]
Strange - it seems to run AMD64 still even for ARM64 worker:
```
0.17s0.01s0.00s0.01s
system_info
Build system information
Build language: generic
Build dist: bionic
Build id: 207207202
Job id: 455897741
Runtime kernel version: 5.3.0-1029-gcp
travis-build version: cd707aa7
Build image provisioning date and time
Tue Jun 30 13:35:43 UTC 2020
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
Systemd Version
systemd 237
Cookbooks Version
3f92a99 https://github.com/travis-ci/travis-cookbooks/tree/3f92a99
git version
git version 2.27.0
bash version
GNU bash, version 4.4.20(1)-release (x86_64-pc-linux-gnu)
gcc version
gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
docker version
Client:
 Version:           18.06.0-ce
 API version:       1.38
 Go version:        go1.10.3
 Git commit:        0ffa825
 Built:             Wed Jul 18 19:09:54 2018
 OS/Arch:           linux/amd64
 Experimental:      false
Server:
 Engine:
  Version:          18.06.0-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.3
  Git commit:       0ffa825
  Built:            Wed Jul 18 19:07:56 2018
  OS/Arch:          linux/amd64
  Experimental:     false
```

**Comment by XVilka** [comment]
For ARMv8
```
[XX] db/cmd/project analysis
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e cfg.newshell=1
af+ 0x100 windowpane
afb+ windowpane 0x100 0x30
afl
Ps .tmp_analysis.rzdb
?e --
o--
afl
?e --
Poo .tmp_analysis.rzdb
rm .tmp_analysis.rzdb
afl
' -
-- stdout
@@ -1,4 +1,3 @@
 0x00000100    1 48           windowpane
 --
 --
-0x00000100    1 48           windowpane
-- stderr
Warning: The current file is not loaded as a regular file. This is not supported in projects yet and it will be necessary to manually re-load to use the project.
All core files, io, analysis and flags info purged.
Failed to load project: invalid content encountered
  basic blocks parsing failed
```

And two additional for PPC:
```
[XX] db/tools/rz_gg rz-gg debruijn sequence 1
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -r -P 2; ?e' -
-- stdout
@@ -1 +1 @@
-AA
+
-- stderr
rz_egg_assemble: invalid assembly

[XX] db/tools/rz_gg rz-gg debruijn sequence 2
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -P 2 -r; ?e' -
-- stdout
@@ -1 +1 @@
-AA
+
-- stderr
rz_egg_assemble: invalid assembly
```

**Comment by XVilka** [comment]
Same broken tests with ASAN: https://github.com/rizinorg/rizin/runs/1522678015#step:15:72

**Comment by XVilka** [comment]
@thestr4ng3r please note these warnings on ARMv8 (https://travis-ci.com/github/rizinorg/rizin/jobs/457128884#L1267):
```
test_analysis_classes_save WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)

test_analysis_save WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)
WARNING: rz_event_send: assertion 'ev && !ev->incall' failed (line 108)

test_dwarf_function_parsing_cpp WARNING: rz_bin_dwarf_free_loc: assertion 'loc_table' failed (line 2559)
```

**Comment by wargio** [comment]
i guess it is an endianness issue.

**Comment by XVilka** [comment]
New failure for ARMv8:
```
[XX] db/cmd/cmd_pa att pa
\=RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'pa add $33, %rbx @a:x86.as:64 @e:asm.syntax=att' --
-- stdout
@@ -1 +1,2 @@
 4883c321
+WARNING: rz_reg_profile_to_cc: assertion 'a0' failed (line 415)
-- stderr
Warning: Cannot derive CC from reg profile.
Warning: Missing calling conventions for 'null'. Deriving it from the regprofile.
```

It is the same as in ASAN build: https://github.com/rizinorg/rizin/runs/1560790126#step:17:32

**Comment by thestr4ng3r** [comment]
#176 fixes `db/cmd/project` for aarch64

**Pull request merged**
