### PR TITLE
Split parts of Visual mode (`Vv` and `Vb` mostly) into pieces

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This is mostly code movement PR with few minimal minor refactorings along the way to keep it compilable and working.
Also removed some of the global state, mostly for current format.

**Test plan**

- CI is green
- `Vv` modes work as before
- `Vb` modes work as before

Please avoid commenting about the code here, since further cleanup will be done in separate PRs. Lets focus on the semantic split and naming here.

Review can be done per-commit, they are self-contained.

Partially addresses https://github.com/rizinorg/rizin/issues/1874

### CODE REVIEW

**Comment by wargio** [comment]
is this a draft?

**Comment by XVilka** [comment]
@wargio no, it's ready to be reviewed

**Comment by wargio** [comment]
```
In file included from ../librz/core/tui/tabs.c:10:
../librz/core/tui/modes.inc:23:20: error: ‘printfmtColumns’ defined but not used [-Werror=unused-variable]
   23 | static const char *printfmtColumns[NPF] = {
      |                    ^~~~~~~~~~~~~~~
```

**Comment by XVilka** [comment]
@wargio will address this later. Please review also the rest of it.

**Review by wargio — APPROVED** [review]
LGTM

**Review by wargio — APPROVED** [review]

**Pull request merged**
