### PR TITLE
Fix gcc12-asan arcompact-dis -Wformat-overflow= warnings

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes gcc12-asan warnings from `arcompact-dis.c` of the following form (https://github.com/rizinorg/rizin/actions/runs/3228253540/jobs/5284108934#step:13:1946):

arcompact-dis-sprintf

This is a cherry-pick from #3066.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
I think, it makes more sense just updating this disassembler from mainstream, where they fixed it already: https://github.com/rizinorg/rizin/issues/814

**Comment by kazarmy** [comment]
Correct me if I'm wrong, but the mainstream for this specific `arcompact-dis.c` file is apparently https://github.com/foss-for-synopsys-dwc-arc-processors/binutils/blob/arc-2.23-dev/opcodes/arcompact-dis.c, where it hasn't been updated in years.

**Review by XVilka — APPROVED** [review]
I think, it was mainstreamed since, see `arc*.c` files in https://github.com/bminor/binutils-gdb/blob/master/opcodes/

**Comment by kazarmy** [comment]
The API is different (rizin's [arcompact-dis.h](https://github.com/rizinorg/rizin/blob/b81d9225fc411c976502fd1c110c2feac0b17c9b/librz/asm/arch/arc/gnu/arcompact-dis.h#L31) vs binutils-gdb's [arc-dis.h](https://github.com/bminor/binutils-gdb/blob/1d4e62f498b1340569fd58c401f98c287cb5d071/opcodes/arc-dis.h#L167-L170)) so the update _might_ require significant work, definitely not in this pr.

**Pull request merged**
