### PR TITLE
Disable `asm.bytes` by default ##cons

### LINKED ISSUE #40: disable asm.bytes by default

### PR DESCRIPTION
**Pull request by officialcjunior**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

Issue #40 asks to get `asm.bytes` disabled by default. I have turned the corresponding `SETBPREF` to `false` hoping to solve the issue.

**Test plan**
See if the implementation is right, and request changes if needed.

**Closing issues**

Closes #40

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
It will be required to update the tests then.
Note, there are two different ways to do that - either to fix the test output, or just to add `e asm.bytes=true` into the test body. This way the amount of changes required is less.
Moreover, I recommend to add a couple tests to test the `e asm.bytes=false` behavior specifically.

See https://github.com/rizinorg/rizin/pull/155/checks?check_run_id=1528524856

**Comment by officialcjunior** [comment]
I don't have enough data left to get the rizin-testbins at the moment. I'll check the CI and fix them all, one by one, over a period of time.

**Comment by Maijin** [comment]
Would have been easier and cleaner to use the auto-fix ;)

**Comment by officialcjunior** [comment]
I need some help on the final one.

To fix https://github.com/rizinorg/rizin/pull/155/checks?check_run_id=1545926116#step:15:240, can I tweak `get-func.py` ?

That Python script is not used anywhere else.

**Comment by XVilka** [comment]
Sure you can but I should note that the output of that test looks better now:
```
/ 16: entry0 ();
-|           0x08049020      55             push ebp                    ; [10] -r-x section size 16 named .text
+|           0x08049020      push ebp                                   ; [10] -r-x section size 16 named .text
 |           0x08049021      mov ebp, esp
 |           0x08049023      sub esp, 8
 |           0x08049026      sub esp, 0xc
-|           0x08049029      push 0x2a                   ; '*' ; 42
-\           0x0804902b      call sym.imp._Exit          ; void _Exit(int status)
+|           0x08049029      push 0x2a                                  ; '*' ; 42
+\           0x0804902b      call sym.imp._Exit                         ; void _Exit(int status)
```

**Comment by wargio** [comment]
i agree. better the new output.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Ideally, would be awesome to have a couple tests for `e asm.bytes=false` as well, if we don't have them yet.

**Comment by wargio** [comment]
Great job @officialcjunior

**Pull request merged**
