### PR TITLE
Add command descriptor property to automatically sort subcommands

### LINKED ISSUE #701: core plugins should be registered *after* the basic commands are registered
### Work environment

```
rizin 0.2.0-git @ linux-x86-64
commit: c02f79753e40d9089b8708fb33a4b5f0ab8590f6, build: 2021-02-23__15:16:15
```

### Expected behavior
Core plugins should be registered *after* the basic commands are added.

### Actual behavior
Core plugins have precedence over basic commands, so for example `java` is registered before anything else.

### Steps to reproduce the behavior
Core plugins are registered in `rz_cmd_new` immediately after creating the root command descriptor, which means that a core plugin could register commands that are supposed to be "core" ones (e.g. `w`, `p`, etc.).

See cmd_api.c:
```c
RZ_API RzCmd *rz_cmd_new(bool has_cons, bool add_core_plugins) {
	...
	cmd->root_cmd_desc = create_cmd_desc(cmd, NULL, RZ_CMD_DESC_TYPE_GROUP, "", &root_help, true);
	if (add_core_plugins) {
		rz_core_plugin_init(cmd);
	}
	rz_cmd_macro_init(&cmd->macro);
	rz_cmd_alias_init(cmd);
	return cmd;
}
```

### PR DESCRIPTION
**Pull request by ret2libc**
**DO NOT SQUASH**

 **Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR allows to automatically sort alphabetically the subcommands of a group. This is for now enabled only for the root group, but it might be useful for others as well. The `sort_commands` boolean is false by default, so the commands will appear in the order provided in the YAML files, by default.

For root group this is probably useful as core plugins might want to register new commands there and you want to see them "in the right place" and not at the beginning or at the end of the list.

To make sure the initialization of all commands is not too slow, I have added a `batch_start`/`batch_end` API to RzCmd, so that the sorting is done only when the batch ends and not for each insertion.

Moreover, Core Plugins were moved out of RzCmd into RzCore, as they are actually "Core  plugins" and not "command plugins", at least in theory. By doing so, I fixed the issue that core plugins commands (e.g. java) were registered before the basic commands.

**Test plan**

...

**Closing issues**

Closes #701

### CODE REVIEW

**Comment by ret2libc** [comment]
@wargio it also removes the annoying space after pressing <tab> on env variables commands.

**Comment by XVilka** [comment]
```
The output from the failed tests:

14/76 autocmplt            FAIL            0.38s   exit status 1
--- command ---
16:16:12 /home/runner/work/rizin/rizin/build/test/unit/test_autocmplt
--- stdout ---
test_autocmplt_cmdid OK
test_autocmplt_newcommand ERR
[XX] Fail at line 140: one is xd: expected xd, got p.
```

**Comment by ret2libc** [comment]
Should be fixed. @wargio have a look please

**Review by XVilka — APPROVED** [review]
A bit of cleanup also, nice. 👍

**Comment by wargio** [comment]
Awesome work!!! @ret2libc <3

**Pull request merged**
