### PR TITLE
Fix external AppVeyor tests that are XX

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/rizinbook) with the relevant information (if needed)

**Detailed description**

The pr fixes the XX AppVeyor tests by rewriting them using internal commands and marking the external version as broken. Also moved the broken `rz-bin` tests into `tools/rz_bin`.

@ret2libc I'd be happy to fix #110 so that it works with this pr. AppVeyor should be green asap though, since it is a pain to check the AppVeyor logs to see whether there is additional redness.

**Test plan**

All builds are green, including AppVeyor.

**Closing issues**

...

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
I wonder why AppVeyor is not triggered.

**Comment by ret2libc** [comment]
Because the regexp `/.*-windows/` does not work, as everything is "eaten" by the `.`. Anyway, @kazarmy thanks. I agree those tests should be fixed asap. The subprocess API PR required a bit more time than what initially thought, but it should be ready now apart from updating acr and a very small thing. Once that's done, I should be able to properly solve #110 .

**Review by ret2libc — APPROVED** [review]
Please rename your PR `windows-fix-external-xx` so that appveyor is triggered.

**Comment by kazarmy** [comment]
Well if you look at https://ci.appveyor.com/project/rizinorg/rizin/history, there's only 1 build which is for #183 (the `rizinorg` version) so I think we've misread the AppVeyor documentation somehow.

**Comment by kazarmy** [comment]
> Because the regexp `/.*-windows/` does not work, as everything is "eaten" by the `.`.

It did work for #161 ... it's greedy, but not that greedy and simple regexps like that should not trigger implementation bugs.

**Pull request merged**
