### PR TITLE
Change permissions of some tests to 0644 from 0755

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr changes the permissions of `db/asm/arm_16` and `db/analysis/thumb` to 0644 since they don't need to be executable.

**Test plan**

The new permissions are appropriate.

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
is this the only one that has wrong perms ?

**Comment by wargio** [comment]
i have just checked and also `./db/analysis/thumb` has wrong perms, could you change also this one?
i used `find \! -perm 644 -type f -o \! -perm 755 -type d`

**Comment by kazarmy** [comment]
> i have just checked and also ./db/analysis/thumb has wrong perms, could you change also this one?

Sure! bf86fa7a1b593b15e88709fcf5b18baf94122d9d

**Comment by kazarmy** [comment]
> i used `find \! -perm 644 -type f -o \! -perm 755 -type d`

`ls -laR | grep -C3 rwx` works too but the above works better

**Review by wargio — APPROVED** [review]

**Pull request merged**
