### PR TITLE
Move capstone, libuv, libzip, lz4, xxhash, yxml, zlib to meson subprojects

### PR DESCRIPTION
**Pull request by ret2libc**
# DO NOT SQUASH

**Your checklist for this pull request**
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)
- [x] Test with `dist-` branch: see https://github.com/rizinorg/rizin/pull/589
- [x] Test with `travis-` branch: see https://github.com/rizinorg/rizin/runs/1879527597

**Detailed description**

A lot of code was copy-pasted in the repository and it was not always clear what was the version that we took from upstream, what the changes (if any), what is our code and what not. This tries to make clear what code we take from external repositories and it removes them from the repo.

Now meson lists the following subprojects by default:
```
  Subprojects                                                                                  
              capstone-bundled: YES                                                            
                        libzip: YES                                                                                                                                                           
                           lz4: YES                                                            
                           sdb: YES
                   tree-sitter: YES
                        xxhash: YES
                          yxml: YES
                          zlib: YES
```

optionally, also libuv is downloaded and built if the system does not provide it. Moreover, libzip builds against openssl, lzma and bz2 if available on the system, so that zip files compressed with one of those algorithms (or encrypted) can be opened as well. Probably for the encryption we need some code on Rizin side, but anyway.

yxml and xxhash, since they are small, are not downloaded from upstream but they are just copied-pasted in a subprojects folder. However, there is clear indication in the meson.build file what is the version that we use.

**Test plan**

...

**Closing issues**

Related to the https://github.com/rizinorg/rizin/issues/209

### CODE REVIEW

**Comment by XVilka** [comment]
Failed on OpenBSD:
```
FAILED: subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_crypto_openssl.c.o 
clang -Isubprojects/libzip-1.7.3/liblibzip.a.p -Isubprojects/libzip-1.7.3 -I../subprojects/libzip-1.7.3 -I../subprojects/libzip-1.7.3/lib -Isubprojects/zlib-1.2.11 -I../subprojects/zlib-1.2.11 -Xclang -fcolor-diagnostics -pipe -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -g -Werror=sizeof-pointer-memaccess -fPIC -MD -MQ subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_crypto_openssl.c.o -MF subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_crypto_openssl.c.o.d -o subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_crypto_openssl.c.o -c ../subprojects/libzip-1.7.3/lib/zip_crypto_openssl.c
../subprojects/libzip-1.7.3/lib/zip_crypto_openssl.c:76:25: error: use of undeclared identifier 'INT_MAX'
    if (secret_length > INT_MAX) {
                        ^
1 error generated.
```

**Comment by XVilka** [comment]
Also `libuv` compilation on Windows seems broken here - it can't find `poll.h` include.

**Comment by XVilka** [comment]
Still linking error on Windows

**Review by XVilka — APPROVED** [review]

**Comment by ret2libc** [comment]
** DO NOT MERGE yet ** I need to do additional tests and for some reasons appveyor did not run.

**Comment by ret2libc** [comment]
```
[791/1582] Compiling C object subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_name_locate.c.obj
FAILED: subprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_name_locate.c.obj 
"clang-cl" "-Isubprojects\libzip-1.7.3\liblibzip.a.p" "-Isubprojects\libzip-1.7.3" "-I..\subprojects\libzip-1.7.3" "-I..\subprojects\libzip-1.7.3\lib" "-Isubprojects\zlib-1.2.11" "-I..\subprojects\zlib-1.2.11" "/MD" "/nologo" "/showIncludes" "/W2" "/O2" "/Ob2" "-Werror=sizeof-pointer-memaccess" "/Fdsubprojects\libzip-1.7.3\liblibzip.a.p\lib_zip_name_locate.c.pdb" /Fosubprojects/libzip-1.7.3/liblibzip.a.p/lib_zip_name_locate.c.obj "/c" ../subprojects/libzip-1.7.3/lib/zip_name_locate.c
In file included from ../subprojects/libzip-1.7.3/lib/zip_name_locate.c:40:
In file included from ..\subprojects\libzip-1.7.3\lib/zipint.h:48:
In file included from ..\subprojects\libzip-1.7.3\lib/zip.h:61:
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\stdio.h(1914,10): error: Macro definition of snprintf conflicts with Standard Library function declaration
        #error Macro definition of snprintf conflicts with Standard Library function declaration
         ^
```
Ok, I should know how to fix this, then I think it should be alright.

**Comment by ret2libc** [comment]
- [x] Make sure to list the yxml/xxhash commits/versions in the meson.build file

**Comment by XVilka** [comment]
There still one Windows problem for the libzip left

**Comment by ret2libc** [comment]
**DO NOT SQUASH** please.

**Review by wargio — APPROVED** [review]

**Comment by wargio** [comment]
how much slimmer has become?

**Comment by ret2libc** [comment]
> how much slimmer has become?

+2,658 −34,394

But well that's just code 3rd party code we don't have anymore in our repository. It's still downloaded and compiled anyway.

**Review by yossizap — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Pull request merged**
