### PR TITLE
Fix aarch64 syscalls

### PR DESCRIPTION
**Pull request by tinez**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [x] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Syscalls on aarch64 are broken, by running:
```
rizin -a arm -b 64 -k linux -q -c asl
```
you can see that the list is way too short and some of the syscall numbers are incorrect.
This PR adapts 2 commits from radare2 to address that. The first one removes duplicate (incorrect) entries from the sdb database. The other one adapts the syscall preprocessor to produce data that is valid from `rz_syscall_item_new_from_string` PoV.

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Many broken tests

**Comment by tinez** [comment]
Yup, I will address that and push an update in a few hours/tomorrow.

**Review by XVilka — APPROVED** [review]

**Comment by XVilka** [comment]
Thanks!

**Comment by tinez** [comment]
Thanks for the reviews and kudos to original authors of the commits! This was merely a backport :)

**Pull request merged**
