### PR TITLE
Remove Whitespace Plugins for now

### PR DESCRIPTION
**Pull request by thestr4ng3r**
**DO NOT SQUASH!!!**

 

**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

We've decided to remove the whitespace plugins completely for now because their results are wrong, so it's useless in the current state. This should not be squashed though so the intermediate state after the desc removal commit is the best state of ws to date, on top of which the plugin can be revived later if desired.

Previous description:
Having a "current" io desc is wrong. This also fixes the initialization of the `RzAsmOp`.

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
There is not even a simple test for this function, is there?

**Comment by thestr4ng3r** [comment]
Haha nope, there doesn't seem to be a single test for the entire plugin.

**Comment by ret2libc** [comment]
I have no idea what it does, it's not tested so...  I don't really care about this. Add a test, kill it,... do as you like :)

**Comment by XVilka** [comment]
It's a [Whitespace](https://en.wikipedia.org/wiki/Whitespace_(programming_language)) analysis plugin.

image

**Review by XVilka — CHANGES_REQUESTED** [review]
I think we should either have a test for this plugin or remove it completely.

**Comment by XVilka** [comment]
You can add this as a test, it's a [Truth-machine](https://esolangs.org/wiki/Truth-machine) implementation in Whitespace:
```
[Space][Space][Space][LF]
[Space][LF][Space]
[Tab][LF][Tab][Tab]
[Tab][Tab][Tab]
[LF][Tab][Space][Space][LF]
[LF][Space][Space][Tab][LF]
[Space][Space][Space][Tab][LF]
[Tab][LF][Space][Tab]
[LF][Space][LF][Tab][LF]
[LF][Space][Space][Space][LF]
[Space][Space][Space][LF]
[Tab][LF][Space][Tab]
[LF][LF][LF]
```
It has enough language constructs to represent non-trivial control flow.

Btw, since Malbolge plugin isn't tested too, it makes sense to add the Truth-machine implementation as a test too:
```
(aONMLKJIHGFEDCBA@?>=<;:98765FD21dd!-,O*)y'&v5#"!DC|Qzf,*vutsrqpF!Clk|ih
gfed9(T&6KoOHZYXWVUTSRQPONM]KJIHGFEDCBA@?>=<;:9876"'~g|edybav_zyxwvotsrq
pSnPlOjibKfedcba`_XA??ZYRW:UTSLQ3ONMLK.IHGFE>CBA@?"=<;:38765432s0/.n,+*)
j!&%f{"!~}|_zyxZvYnsrqpRnmlkjML:f_^GF!
```

**Comment by jvoisin** [comment]
Is it really useful to have this kind of "feature"?

**Comment by XVilka** [comment]
We could indeed remove it or move to extras. Nevertheless, it's better to have a test even in extras ;)

**Comment by thestr4ng3r** [comment]
I think we should make it tested decently in core and then move outside.

**Comment by XVilka** [comment]
So please add a test then, and lets merge it 👍

**Review by XVilka — APPROVED** [review]

**Pull request merged**
