### PR TITLE
Update blake3 to use cpu extensions

### PR DESCRIPTION
**Pull request by wargio**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Optimize blake 3 to take advantage of CPU extensions

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
Resolved

**Comment by wargio** [comment]
i need to understand how to detect the support for avx simd extensions

**Review by XVilka — APPROVED** [review]
LGTM, but lets see what @ret2libc thinks about these Meson changes first, as our buildsystem expert.

**Review by ret2libc — COMMENTED** [review]
I think you can use https://mesonbuild.com/Simd-module.html .

**Comment by wargio** [comment]
The only reason why i did not is because is considered unstable

**Pull request merged**
