### PR TITLE
get_main_offset_linux_64_pie, lea: Apply `maindelta` to vaddr of `entry`

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

~~This pr follows up on #2320 by making `get_main_offset_linux_64_pie()` return a physical address on `lea`.~~

This pr reworks the `lea` algo in `get_main_offset_linux_64_pie()` so that `maindelta` is applied to the virtual address of `entry`. This is because `maindelta` should only be applied in the virtual address space.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — COMMENTED** [review]
Is `entry` a virtual address?

**Comment by kazarmy** [comment]
No it's physical because it's from `rz_bin_elf_get_entry_offset()` and that function converts `e_entry` from the ELF header into a physical address.

**Comment by ret2libc** [comment]
> No it's physical because it's from `rz_bin_elf_get_entry_offset()` and that function converts `e_entry` from the ELF header into a physical address.

If `entry` is physical, then:

```C
ut64 vmain = (ut64)(entry + bo + maindelta) + 7;
ut64 ventry = Elf_(rz_bin_elf_p2v_new)(bin, entry);
if (vmain >> 16 == ventry >> 16) {
	return Elf_(rz_bin_elf_v2p_new)(bin, vmain);
}
```

how is `vmain` virtual? `vmain = entry + bo + maindelta + 7`, where `entry` is physical. `bo` is a small offset. `maindelta` is a st32, so potentially a small value i guess.

**Comment by kazarmy** [comment]
> ... how is `vmain` virtual?

Hmm, good question.

I've rewritten the `lea` algo (7ade88aaec3bcf00e326863242372319cd168fed) so that `maindelta` is added to the virtual address of `entry`. The reasoning for this change is that `maindelta` is certainly valid in the virtual address space, but not necessarily so in the physical address space.

**Comment by kazarmy** [comment]
Updated https://github.com/rizinorg/rizin/pull/2324#issue-853078315.

**Review by ret2libc — COMMENTED** [review]
Why are you doing `ventry = p2v(entry); <op>; return v2p(vmain)`? Is it different than just doing the `<op>` directly on `entry`?

**Comment by kazarmy** [comment]
Based on the following example in [`test/bins/elf/analysis/fedora_35_x86_64bit_ls`](https://github.com/rizinorg/rizin-testbins/blob/424e9325cc7e9f71dd77f25610399f0093f228f2/elf/analysis/fedora_35_x86_64bit_ls):

```
$ rizin bins/elf/analysis/fedora_35_x86_64bit_ls
 -- Toggle between disasm and graph with the space key
[0x00006b10]> e asm.bytes=1
[0x00006b10]> e asm.sub.rel=0
[0x00006b10]> pd 1 @ entry0+0x18
            0x00006b28      488d3d51e2ff.  lea   rdi, [rip - 0x1daf]   ; main
                                                                       ; 0x4d80
```

> Why are you doing `ventry = p2v(entry); <op>; return v2p(vmain)`? Is it different than just doing the `<op>` directly on `entry`?

I can think of 2 reasons why:

1. The `lea` instruction is executed in the virtual address space and the target `main` address (`0x4d80`) is a virtual address, so it makes more sense for the Rizin code to reflect this as close as possible.
2. The `lea` instruction assumes that `main` is basically `0x1daf` bytes before it. This must be true in the virtual address space (otherwise execution is not going to the start of `main`) but can be false in the physical address space e.g. it is possible that `entry0` and `main` could be in different `LOAD` segments that are physically very far from each other but very close virtually (this appears unlikely but could happen).

And thus yes it is different theoretically (though maybe not practically).

**Comment by ret2libc** [comment]
You definitely convinced me @kazarmy ;) that's right!

**Review by ret2libc — APPROVED** [review]

**Pull request merged**
