### PR TITLE
Fix memleak in rz_config_set_i()

### PR DESCRIPTION
**Pull request by p371jah**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — COMMENTED** [review]
Please also check if it applies to `rz_config_set_b()` too.

**Comment by p371jah** [comment]
No `rz_config_set_b()` doesn't leak.

**Comment by p371jah** [comment]
Actually adding `free(node->value)` after line 365 would be enough.

**Comment by p371jah** [comment]
@XVilka BTW what was wrong with previous implementation of `rz_config_set_i()`? IMO it worked almost fine: no leaks, no extra `strdup`/`free` calls.

**Pull request closed without merging**
