### PR TITLE
Allow users to decide how their tables look

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Currently, there is no way for the user to configure how their table will be printed/shown. It would be nice to allow the user to decide the printing style and whether to print headers or not.

Need help in figuring out how to use the config within the `rz_table_new` function. Maybe I could use a `RzCoreBind`. Would like to hear some suggestions.

**Test plan**

Add integration tests.

**Closing issues**

None.

### CODE REVIEW

**Comment by DMaroo** [comment]
Rizin already has such a feature using the `:` option (`aflt:fancy`). Sorry for the noise.

**Comment by ret2libc** [comment]
Yes, it has that. When I was talking about a way to set it for all tables I meant a var that would select a table mode by default without having to specify `:fancy`, for example.

**Comment by DMaroo** [comment]
Oh, I see. Anyways, I don't think it is a priority. I'll finish the memleaks PR first.

**Comment by ret2libc** [comment]
> Oh, I see. Anyways, I don't think it is a priority. I'll finish the memleaks PR first.

Absolutely not a priority. Just throwing ideas but there are many more important/fun things ;)

**Pull request closed without merging**
