### PR TITLE
Update libc6 and `dbg.maps.count.after.map` test

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

There have been transient failures of the following test (e.g. [here](https://github.com/rizinorg/rizin/runs/5514619544?check_suite_focus=true#step:16:735)):

dbg_maps-error

The new value shown above is apparently due to the recent update of libc6 to 2.31-0ubuntu9.7, and thus this pr fixes the transient failures by updating libc6 always in the CI (since fixing libc6 to a specific version [appears to be more trouble than it's worth](https://askubuntu.com/questions/428772/how-to-install-specific-version-of-some-package#comment1342272_428778)).

Old description: ~~This pr updates the expected output of the `dbg.maps.count.after.map` test. The output of the offending `dm` looks ok afaik but the output cannot be easily incorporated into the test because the map addresses can change on every execution. This change _might_ have something to do with the [recent glibc update](https://changelogs.ubuntu.com/changelogs/pool/main/g/glibc/glibc_2.31-0ubuntu9.7/changelog).~~

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by wargio — APPROVED** [review]
i'm not sure to understand why this number have increased but ok for me

**Comment by kazarmy** [comment]
Hmm the value actually dropped back from 18 to 17 so I'm closing this for now.

**Comment by kazarmy** [comment]
> i'm not sure to understand why this number have increased but ok for me

The difference with https://github.com/rizinorg/rizin/runs/5520110902?check_suite_focus=true#step:16:715 is apparently these lines:

```
0xf7d4f000 - 0xf7d68000 - usr   100K s r-- /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
0xf7d68000 - 0xf7ec0000 - usr   1.3M s r-x /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
0xf7ec0000 - 0xf7f34000 - usr   464K s r-- /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
0xf7f34000 - 0xf7f35000 - usr     4K s --- /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
0xf7f35000 - 0xf7f37000 - usr     8K s r-- /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
0xf7f37000 - 0xf7f38000 - usr     4K s rw- /usr/lib32/libc-2.31.so /usr/lib32/libc-2.31.so
```

Not sure where these values are coming from, and why there is a map with no permissions.

**Comment by kazarmy** [comment]
https://github.com/rizinorg/rizin/pull/2403#issue-1166206680 updated.

**Review by wargio — APPROVED** [review]

**Pull request merged**
