### PR TITLE
Fix #298: Tighten utf16le auto-detection rules

### LINKED ISSUE #298: False UTF16 positive in strings detection
### Work environment

| Questions                                            | Answers
|------------------------------------------------------|--------------------
| OS/arch/bits (mandatory)                             | Fedora 33 x86_64
| File format of the file you reverse (mandatory)      | ELF
| Architecture/bits of the file (mandatory)            | x86_64
| rizin -v full output, **not truncated** (mandatory)  | rrizin 0.1.0-git 26133 @ linux-x86-64 git.0.1.0-git
commit: cf1c6e43bf934689eae2dd1fa7322b0cd6dd3225 build: 2021-01-04__18:56:33

### Expected behavior

It should detect the string as an ASCII

### Actual behavior

Falsely detects as an UTF16LE

### Steps to reproduce the behavior 
```
$ rizin 004.libcap.so.2.22.x86_64  
[0x00002e6e]> izz~2e6e
175 0x00002e6e 0x00002e6e 264 530  .rodata            utf16le ui┽╳╳s猥,┫╳╳s┭╳╳s慣彰档睯n慣彰慤彣癯牥楲敤挀灡摟捡牟慥彤敳牡档挀灡晟睯敮r慣彰獦瑥摩挀灡歟汩l慣彰敳杴摩挀灡獟瑥極d慣彰敳灴慣p慣彰楬畮彸浩畭慴汢e慣彰敮彴楢摮獟牥楶散挀灡湟瑥扟潲摡慣瑳挀灡湟瑥慟浤湩挀灡湟瑥牟睡挀灡楟捰江捯k慣彰灩彣睯敮r慣彰祳彳潭畤敬挀灡獟獹牟睡潩挀灡獟獹损牨潯t慣彰祳彳瑰慲散挀灡獟獹灟捡瑣挀灡獟獹慟浤湩挀灡獟獹扟潯t慣彰祳彳楮散挀灡獟獹牟獥畯捲e慣彰祳彳楴敭挀灡獟獹瑟祴损湯楦g慣彰歭潮d慣彰敬獡e慣彰畡楤彴牷瑩e慣彰畡楤彴潣瑮潲l慣彰敳晴慣p慣彰慭彣癯牥楲敤挀灡浟捡慟浤湩挀灡獟獹潬g blocks=Basic Latin,Box Drawing,CJK Unified Ideographs,Private Use Area
[0x00002e6e]> 
```

### Additional Logs, screenshots, source-code,  configuration dump, ...

```
[0x00002e6e]> px 600
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x00002e6e  7500 6900 3d25 7325 7325 7300 2573 2c00  u.i.=%s%s%s.%s,.
0x00002e7e  2b25 7325 7325 7300 2d25 7325 7325 7300  +%s%s%s.-%s%s%s.
0x00002e8e  6361 705f 6368 6f77 6e00 6361 705f 6461  cap_chown.cap_da
0x00002e9e  635f 6f76 6572 7269 6465 0063 6170 5f64  c_override.cap_d
0x00002eae  6163 5f72 6561 645f 7365 6172 6368 0063  ac_read_search.c
0x00002ebe  6170 5f66 6f77 6e65 7200 6361 705f 6673  ap_fowner.cap_fs
0x00002ece  6574 6964 0063 6170 5f6b 696c 6c00 6361  etid.cap_kill.ca
0x00002ede  705f 7365 7467 6964 0063 6170 5f73 6574  p_setgid.cap_set
0x00002eee  7569 6400 6361 705f 7365 7470 6361 7000  uid.cap_setpcap.
0x00002efe  6361 705f 6c69 6e75 785f 696d 6d75 7461  cap_linux_immuta
0x00002f0e  626c 6500 6361 705f 6e65 745f 6269 6e64  ble.cap_net_bind
0x00002f1e  5f73 6572 7669 6365 0063 6170 5f6e 6574  _service.cap_net
0x00002f2e  5f62 726f 6164 6361 7374 0063 6170 5f6e  _broadcast.cap_n
0x00002f3e  6574 5f61 646d 696e 0063 6170 5f6e 6574  et_admin.cap_net
0x00002f4e  5f72 6177 0063 6170 5f69 7063 5f6c 6f63  _raw.cap_ipc_loc
0x00002f5e  6b00 6361 705f 6970 635f 6f77 6e65 7200  k.cap_ipc_owner.
0x00002f6e  6361 705f 7379 735f 6d6f 6475 6c65 0063  cap_sys_module.c
0x00002f7e  6170 5f73 7973 5f72 6177 696f 0063 6170  ap_sys_rawio.cap
0x00002f8e  5f73 7973 5f63 6872 6f6f 7400 6361 705f  _sys_chroot.cap_
0x00002f9e  7379 735f 7074 7261 6365 0063 6170 5f73  sys_ptrace.cap_s
0x00002fae  7973 5f70 6163 6374 0063 6170 5f73 7973  ys_pacct.cap_sys
0x00002fbe  5f61 646d 696e 0063 6170 5f73 7973 5f62  _admin.cap_sys_b
0x00002fce  6f6f 7400 6361 705f 7379 735f 6e69 6365  oot.cap_sys_nice
0x00002fde  0063 6170 5f73 7973 5f72 6573 6f75 7263  .cap_sys_resourc
0x00002fee  6500 6361 705f 7379 735f 7469 6d65 0063  e.cap_sys_time.c
0x00002ffe  6170 5f73 7973 5f74 7479 5f63 6f6e 6669  ap_sys_tty_confi
0x0000300e  6700 6361 705f 6d6b 6e6f 6400 6361 705f  g.cap_mknod.cap_
0x0000301e  6c65 6173 6500 6361 705f 6175 6469 745f  lease.cap_audit_
0x0000302e  7772 6974 6500 6361 705f 6175 6469 745f  write.cap_audit_
0x0000303e  636f 6e74 726f 6c00 6361 705f 7365 7466  control.cap_setf
0x0000304e  6361 7000 6361 705f 6d61 635f 6f76 6572  cap.cap_mac_over
0x0000305e  7269 6465 0063 6170 5f6d 6163 5f61 646d  ride.cap_mac_adm
0x0000306e  696e 0063 6170 5f73 7973 6c6f 6700 17f3  in.cap_syslog...
0x0000307e  ffff 89f3 ffff c4f3 ffff 89f3 ffff 89f3  ................
0x0000308e  ffff 89f3 ffff 89f3 ffff 89f3 ffff 89f3  ................
0x0000309e  ffff 89f3 ffff 89f3 ffff 89f3 ffff 89f3  ................
0x000030ae  ffff 89f3 ffff 89f3 ffff 89f3 ffff 89f3  ................
0x000030be  ffff 89f3 ffff a2f2                      ........
[0x00002e6e]> 
```
[004.libcap.so.2.22.x86_64.zip](https://github.com/rizinorg/rizin/files/5764320/004.libcap.so.2.22.x86_64.zip)

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [X] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr attempts to fix #298 by tightening the rules for utf16le auto-detection.

**Test plan**

All builds are green.

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/298

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
Makes perfect sense to me since 3 bytes is obviously not enough to recognize UTF-16,

**Comment by XVilka** [comment]
There are a few broken tests though:
```
[XX] db/formats/mdmp : 32bit - strings count
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc iz~? bins/mdmp/hello.dmp
-- stdout
@@ -1 +1 @@
-10281
+10277

[XX] db/formats/elf/elf-relro ELF: arm64 relocs crashing
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!rz-bin -qzz bins/elf/librsjni_androix.so~?' -
-- stdout
```
https://builds.sr.ht/~xvilka/job/387041

```
[XX] db/formats/mdmp : 64bit - strings count
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc iz~? bins/mdmp/hello64.dmp
-- stdout
@@ -1 +1 @@
-22898
+22901


-- stderr
[WARN] Invalid or unsupported enumeration encountered 21
[WARN] Invalid or unsupported enumeration encountered 22
[INFO] Parsing data sections for large dumps can take time, please be patient (but if strings ain't your thing try with -z)!



[XX] db/formats/mdmp : 32bit - strings count
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc iz~? bins/mdmp/hello.dmp
-- stdout
@@ -1 +1 @@
-10281
+10277


-- stderr
[WARN] Invalid or unsupported enumeration encountered 21
[WARN] Invalid or unsupported enumeration encountered 22
Error parsing resource directory
[INFO] Parsing data sections for large dumps can take time, please be patient (but if strings ain't your thing try with -z)!

[XX] db/formats/elf/elf-relro ELF: arm64 relocs crashing
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!!rz-bin -qzz bins/elf/librsjni_androix.so~?' -
-- stdout
@@ -1 +1 @@
-549
+548
```
https://github.com/rizinorg/rizin/pull/308/checks?check_run_id=1649437247#step:17:290

**Review by XVilka — APPROVED** [review]
Looks green now. Lets wait for AppVeyor and then merge.

**Comment by XVilka** [comment]
Ignore the `jni.h` error since it's due to the merge of latest `dev` and somehow not all CI takes new `rizin-binaries`.

**Review by wargio — APPROVED** [review]

**Review by Maijin — APPROVED** [review]

**Pull request merged**
