### PR TITLE
Port `db` commands to newshell [WIP]

### PR DESCRIPTION
**Pull request by DMaroo**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Porting `db` and related commands to newshell.

**Test plan**

CI should be green.

**Closing issues**

None.

### CODE REVIEW

**Comment by DMaroo** [comment]
Currently, the build fails because the `cmd_debug.yaml` configuration is invalid. Any way to make the configuration valid, and also preserve the current state of commands.

**Comment by XVilka** [comment]
```
If a command has the same name as its parent, it can only be the first child. See parent of Command cmd_debug_db
```

**Comment by DMaroo** [comment]
> ```
> If a command has the same name as its parent, it can only be the first child. See parent of Command cmd_debug_db
> ```

Yes. But I want to have two commands named `db`, one which lists the breakpoints, and other which adds a breakpoint. I do not want to merge them into a single command with optional parameter. Neither do I want to make any one of them a subcommand of another, since that will mean that the subcommand won't show up when using `db?`.

**Comment by ret2libc** [comment]
> > ```
> > If a command has the same name as its parent, it can only be the first child. See parent of Command cmd_debug_db
> > ```
> 
> Yes. But I want to have two commands named `db`, one which lists the breakpoints, and other which adds a breakpoint. I do not want to merge them into a single command with optional parameter. Neither do I want to make any one of them a subcommand of another, since that will mean that the subcommand won't show up when using `db?`.

This is not possible for now. I would first need to resolve https://github.com/rizinorg/rizin/issues/1413 before this is possible. Sorry. The solution we have for now is to just merge the two things with optional parameters.

**Comment by DMaroo** [comment]
I have ported the `db` commands. Now I'll have to fix some integration tests (I hope they fail, rather than just pass silently).

I have also made some subtle changes to the actions done by some of the commands. This might take a bit long to review, so please take your time and review the PR carefully. Thank you.

**Comment by DMaroo** [comment]
I'll probably add a few more integration tests to test the new command handlers. Other than that, there is nothing to do according to me. Please let me know if anything's missing.

**Comment by XVilka** [comment]
@DMaroo could you please close this PR and send a new one from under the rizinorg account called `dist-` to trigger AppVeyor and BSD builds to check if nothing was missed in the `db` code, especially for Windows-specific commands?

**Pull request closed without merging**
