### PR TITLE
Update Android NDK to the latest default platform

### LINKED ISSUE #2991: Fix Android CI builds
```
meson.build:1:0: ERROR: Unknown compiler(s): [['/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang']]
The following exception(s) were encountered:
Running `/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang --version` gave "[Errno 2] No such file or directory: '/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android28-clang'"

A full log can be found at /home/runner/work/rizin/rizin/build/meson-logs/meson-log.txt
Error: Process completed with exit code 1.
```

See `.github/meson-android-*` files here: https://github.com/rizinorg/rizin/tree/dev/.github

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Looks like GitHub quietly updated the provided SDK/NDK.

**Test plan**

CI is green

**Closing issues**

Closes https://github.com/rizinorg/rizin/issues/2991

### CODE REVIEW

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
Looks like NDK was completely removed from GHA: `ls: cannot access '/usr/local/lib/android/sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin': No such file or directory`

**Comment by XVilka** [comment]
@ret2libc Meson doesn't resolve environment variables in the ini file, looks like?
Files are there but Meson can't find them:
```
total 534360
-rwxrwxrwx 1 root root       193 Aug 28 22:26 aarch64-linux-android21-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android21-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android22-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android22-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:26 aarch64-linux-android23-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:26 aarch64-linux-android23-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android24-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android24-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:26 aarch64-linux-android26-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android26-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android27-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android27-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android28-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:26 aarch64-linux-android28-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:26 aarch64-linux-android29-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:26 aarch64-linux-android29-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android30-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android30-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android31-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:26 aarch64-linux-android31-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android32-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android32-clang++
-rwxrwxrwx 1 root root       193 Aug 28 22:27 aarch64-linux-android33-clang
-rwxrwxrwx 1 root root       197 Aug 28 22:27 aarch64-linux-android33-clang++
```
```

meson.build:1:0: ERROR: Unknown compiler(s): [['${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang']]
The following exception(s) were encountered:
Running `'${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang' --version` gave "[Errno 2] No such file or directory: '${ANDROID_NDK}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang'"
```

**Comment by ret2libc** [comment]
I don't think it does

**Comment by XVilka** [comment]
Yes, it doesn't - apparently, there is an issue that wasn't fixed for years: https://github.com/mesonbuild/meson/issues/309

**Pull request merged**
