### PR TITLE
Add asm and analysis plugin for kvx architecture ##arch

### PR DESCRIPTION
**Pull request by jmaselbas**
**checklist**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

KVX is VLIW architecture, kind of like a DSP, it can execute more than
one "instruction" per cycle. Each cycle a bundle of instruction is
executed which is comprised of up to 6 instructions. The general rules
for bundle are: only one BCU instruction (which comes first); only one
LSU instruction; and up to 4 ALU instructions (depending on the type).

In assembly the end of a bundle is marked by a `;;` in an empty line,
here in r2 (to make things more compact and readable) the end of bundle
is appended after the last instruction, but beware that this is not
valid kvx assembly.

### CODE REVIEW

**Review by wargio — COMMENTED** [review]
I have a small problem with this code: contains some GPL code. we are trying to avoid having GPL code in the repository.
I think this should be placed in rizin-extras and not in the main repo.
@XVilka @thestr4ng3r @ret2libc what do you think?

**Comment by wargio** [comment]
just to be clear, i saw that you used the values from the GPL repo to implement the decoder. i'm not 100% sure if this can be considered not a GPL code, since you only have extracted the masks/consts value

**Comment by jmaselbas** [comment]
> just to be clear, i saw that you used the values from the GPL repo to implement the decoder. i'm not 100% sure if this can be considered not a GPL code, since you only have extracted the masks/consts value

Yes... the binutils `kv3-opc.c` is GPL-2.0-or-later,  `kvx-dis.c` have some part derived from binutils `kv3-opc.c` (which is GPL-3.0-or-later), `kvx-reg.c` is written by me.
The license might need to be GPL instead of LGPL.

**Comment by XVilka** [comment]
I also think we should put it in extras both due to the license and architecture being quite rare/exotic. Also, when you add a new architecture - please add tests for it.

**Comment by XVilka** [comment]
Is it this processor? https://www.kalrayinc.com/products/processors-many-core

**Comment by jmaselbas** [comment]
> Is it this processor? https://www.kalrayinc.com/products/processors-many-core

yes it is

**Comment by jmaselbas** [comment]
> I also think we should put it in extras both due to the license and architecture being quite rare/exotic. Also, when you add a new architecture - please add tests for it.

Where the tests goes ? Do you any example ? I've added a simply hello world program into radare testbin do you need the same thing?

**Comment by wargio** [comment]
yes, you can add a bin in the bin repo

**Comment by XVilka** [comment]
Could you please send the PR to https://github.com/rizinorg/rizin-extras instead?

**Comment by XVilka** [comment]
@jmaselbas could you please send a PR to https://github.com/rizinorg/rizin-extras instead? A good example how it would look like is https://github.com/rizinorg/rizin-extras/tree/master/jaguar-gpu

**Comment by XVilka** [comment]
Closed in favor of putting it into [**rizin-extras**](https://github.com/rizinorg/rizin-extras/): [**kvx**](https://github.com/rizinorg/rizin-extras/tree/master/kvx).

**Pull request closed without merging**
