### PR TITLE
Support for compressed DWARF `.zdebug_*` sections

### PR DESCRIPTION
**Pull request by b1llow**
# SQUASH ME

**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- http://www.linker-aliens.org/blogs/ali/entry/elf_section_compression/

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
```
running tests for project 'rizin'
.................................................................................................................E..E
finished 117 tests, 0 expected fail, 2 fail, 0 skipped
[fail ]   1.35s, integration:dwarf_integration: child exited abnormally
[fail ]   1.70s, integration:project_migrate: child exited abnormally
stderr: 'WARNING: Invalid section header (check array failed).
WARNING: Invalid section header (check array failed).
WARNING: Invalid section header (check array failed).
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
ERROR: TODO: .debug_line_str
WARNING: Invalid section header (check array failed).
VERBOSE: bin_file_strings: using 2 threads
VERBOSE: bin_file_strings: using 2 threads
error parsing "wmemcmp" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "sbrk" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "memchr" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "connect" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "findmem" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "xmalloc" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "strncat" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "memcmp" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "_Getmbcurmax" func return type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field
 
error parsing "__udivdi3" func arg type "uint64_t": Primitive type "uint64_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "uint64_t"
Cannot parse type_descriptor's type field

error parsing "memcpy" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "mmap" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "wcsncmp" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "calloc" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "memset" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "realloc" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "strxfrm" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field

error parsing "read" func arg type "size_t": Primitive type "size_t" already exists
Error forming RzType and RzBaseType pair out of primitive type
Wrongly formed "(type_descriptor)": "(type_descriptor type: (primitive_type))"
"(type_descriptor)": "size_t"
Cannot parse type_descriptor's type field
```

**Comment by b1llow** [comment]
@XVilka done

**Review by XVilka — CHANGES_REQUESTED** [review]
Few tests failing on ASAN build:
```
[XX] db/cmd/cmd_i ix same-addr samples
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'ix. @ 0x00091004
echo --
ix.j @ 0x00091004
' bins/elf/libstdc++.so.6
-- stdout
--- expected
+++ actual
@@ -1,6 +1,118 @@
-0x00091004	/build/gcc/src/gcc/libstdc++-v3/libsupc++/new	57
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
+WARNING: rz_type_as_string: assertion 'typedb && type' failed (line 810)
```
Full log at https://github.com/rizinorg/rizin/actions/runs/6051863453/job/16424207725?pr=3819

**Comment by XVilka** [comment]
See also these:
```
[XX] db/formats/demangling_bin C++ demangle exported GLIBCXX symbols
RZ_NOPLUGINS=1 /home/travis/build/rizinorg/rizin/install/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc iE~0x0008ce50 bins/elf/libstdc++.so.6
-- stdout
--- expected
+++ actual

@@ -2,3 +2,115 @@
...
ERROR: DWARF function _IO_FILE* std::__exchange<_IO_FILE*, decltype(nullptr)>(_IO_FILE*&, decltype(nullptr)&&) variable __new_val failed

ERROR: Failed to insert RzType [(null)] into type_by_offset

ERROR: Failed to insert RzType [(null)] into type_by_offset

ERROR: DWARF function wchar_t* std::__exchange<wchar_t*, decltype(nullptr)>(wchar_t*&, decltype(nullptr)&&) variable __new_val failed

ERROR: Failed to insert RzType [(null)] into type_by_offset

ERROR: DWARF function char const* std::__exchange<char const*, decltype(nullptr)>(char const*&, decltype(nullptr)&&) variable __new_val failed

ERROR: Failed to insert RzType [(null)] into type_by_offset

ERROR: DWARF function char* std::__exchange<char*, decltype(nullptr)>(char*&, decltype(nullptr)&&) variable __new_val failed

ERROR: Failed to insert RzType [(null)] into type_by_offset
```

**Review by XVilka — APPROVED** [review]

**Pull request merged**
