### PR TITLE
Bundle rz-ghidra in base docker image

### PR DESCRIPTION
**Pull request by fangxlmr**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This PR modifies Dockerfile to install `rz-ghidra` system widely in base image by default.

Decompiler plugin (i.e. RzGhidra) is so basic that it's reasonable to have it installed in base docker image.

**Test plan**

All tests pass

**Closing issues**

#1011

### CODE REVIEW

**Review by XVilka — COMMENTED** [review]
Maybe it makes sense to remove `rz-pm` database after?

**Comment by fangxlmr** [comment]
True. What should I delete? db for rzghidra: `$HOME/.local/share/rizin/rz-pm/git/rz-ghidra`, or the whole `rz-pm` database: `$HOME/.local/share/rizin/rz-pm`?

**Comment by ret2libc** [comment]
Could you create a new PR with `container` in the branch name used to create the PR? It will trigger the CI job that will push the docker image on docker hub, so we can test before merging.

**Comment by fangxlmr** [comment]
Ah, a bit tricky way to do this but it does make some sense for testing base image before actually merging. I didn't notice [this part](https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L10) in ci.yml until you remind me (please tell me I understood the ci workflow correctly).

Right, I'll make a new PR later on.

**Comment by ret2libc** [comment]
> Ah, a bit tricky way to do this but it does make some sense for testing base image before actually merging. I didn't notice [this part](https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L10) in ci.yml until you remind me (please tell me I understood the ci workflow correctly).

It is that and https://github.com/rizinorg/rizin/blob/dev/.github/workflows/ci.yml#L825 .

**Comment by fangxlmr** [comment]
Made a new PR in #1029. Closing this one.

**Pull request closed without merging**
