### PR TITLE
`rz_io_write_at`: Return silently if len <= 0.

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [x] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Return silently if `len <= 0` and add docs for function.

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
Why this? Where was the _assert_ being triggered?

**Comment by XVilka** [comment]
Why would we ever want to write negative amount of bytes? Shouldn't it be solved at the root of the problem?

**Comment by Rot127** [comment]
\*sign\* I was a little stupid. I thought for whatever reason that those `rz_return_val_if_fail` get removed by a release build. Ignore it please.

**Comment by XVilka** [comment]
@Rot127 in fact, that `int len` could be converted into `ut64 len`, since negative length doesn't make sense, and we should be able to write chunks bigger than 4Gb size. Then your addition of the documentation could be a good PR too.

**Pull request closed without merging**
