### PR TITLE
Finish removing www related content

### PR DESCRIPTION
**Pull request by xarkes**
Replacement of https://github.com/rizinorg/rizin/pull/186 because AppVeyor build was not triggered.

### CODE REVIEW

**Comment by xarkes** [comment]
Well it seems AppVeyor is still not triggered. Cc @XVilka

**Review by XVilka — APPROVED** [review]
I think it's fine.

**Review by ITAYC0HEN — APPROVED** [review]

**Comment by kazarmy** [comment]
I think `rizinorg`'s AppVeyor only triggers if the pr branch is on the `rizinorg` repo. For this pr and #186, the branch is on the `xarkes` repo.

**Comment by ret2libc** [comment]
> I think `rizinorg`'s AppVeyor only triggers if the pr branch is on the `rizinorg` repo. For this pr and #186, the branch is on the `xarkes` repo.

Yes, I believe there is something to configure in @XVilka 's AppVeyor account, as appveyor is his.

**Review by wargio — APPROVED** [review]

**Pull request merged**
