### PR TITLE
Update DEVELOPERS.md

### PR DESCRIPTION
**Pull request by createyourpersonalaccount**
Swap clang-format-16 with the sys/clang-format.py script.

 

**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by kazarmy — CHANGES_REQUESTED** [review]
Reason for the swap?

**Comment by createyourpersonalaccount** [comment]
> Reason for the swap?

I am not sure which method is preferred. I thought the script is preferred. Do you the documentation should mention the script or the `git-clang-format` command?

**Comment by kazarmy** [comment]
It should mention both I think, since the script by default checks the whole repo which can take a considerable amount of time.

**Review by kazarmy — APPROVED** [review]
Lgtm, just waiting for another approval

**Review by XVilka — APPROVED** [review]

**Pull request merged**
