### PR TITLE
java: fix `java_class_parse`

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [ ] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

```
rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e scr.prompt=false ; aaa' bins/java/fba022731cfdd80bc65a899afefead1e
-- stderr
ERROR: java bin: invalid constant pool tag: 23 at 0x2ab
ERROR: java bin: could not parse the constant pool value at offset 2ab
Backtrace 10 stack frames.
0   librz_util.0.8.dylib                0x0000000103291824 rz_sys_backtrace + 44
1   librz_util.0.8.dylib                0x0000000103227380 rz_assert_log + 88
2   librz_bin.0.8.dylib                 0x000000010428504c java_class_parse + 2128
3   librz_bin.0.8.dylib                 0x00000001042847bc rz_bin_java_class_new + 152
4   librz_bin.0.8.dylib                 0x00000001042070e0 load_buffer + 48
5   librz_bin.0.8.dylib                 0x00000001041d5710 rz_bin_object_new + 448
6   librz_bin.0.8.dylib                 0x00000001041c7aa4 rz_bin_file_new_from_buffer + 372
7   librz_bin.0.8.dylib                 0x00000001041cced0 rz_bin_open_buf + 692
8   librz_bin.0.8.dylib                 0x00000001041cc904 rz_bin_open_io + 884
9   librz_core.0.8.dylib                0x0000000105ed5534 core_file_do_load_for_io_plugin + 204

-- exit status: -1
```

**Test plan**

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
where that file is coming from?

**Comment by b1llow** [comment]
> where that file is coming from?

https://github.com/rizinorg/rizin-testbins

Although I noticed later that it was mainly because I used the environment variable `RZ_DEBUG_ASSERT=1`.

**Comment by wargio** [comment]
so it should be ok? looks like a fuzzed bin that one.

**Comment by b1llow** [comment]
> so it should be ok? looks like a fuzzed bin that one.

I feel that this change is useful, because there are actually some checks missing that don't return correctly in parse of illegitimate java classes.

**Review by wargio — APPROVED** [review]

**Pull request merged**
