### PR TITLE
Implement history filtering for dietline

### LINKED ISSUE #407: Selective history filtering
Consider the following case:
```
[i] ℤ rizin malloc://1024                                                                                                                                                                                                         18:27:40 
 -- Step through your seek history with the commands 'u' (undo) and 'U' (redo)
[0x00000000]> wa 9090
Cannot assemble '9090' at line 3
[0x00000000]> wx 9090
[0x00000000]> s 2
[0x00000002]> pi 1
add byte [rax], al
[0x00000002]> 
```
If in Rizin you type `s` and press `UP ARROW` it will show the `pi 1`.
If you do the same in Vim/NeoVim it will show the `s 2`.

I suggest to follow the similar behaviour in Rizin, to improve the history navigation experience.

### PR DESCRIPTION
**Pull request by GustavoLCR**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Test plan**

Manually test it

**Closing issues**

Closes #407

### CODE REVIEW

**Comment by ret2libc** [comment]
Hey, this is great! I tried it a bit. Found some problems you can see below:
https://asciinema.org/a/LQWb27wSjcfpQWjzgMrpUgnNB

**Comment by GustavoLCR** [comment]
> Hey, this is great! I tried it a bit. Found some problems you can see below:
> https://asciinema.org/a/LQWb27wSjcfpQWjzgMrpUgnNB

@ret2libc That's the same behavior bash/zsh have. Should I change it so that the history goes back when a line edit occurs?

**Comment by ret2libc** [comment]
> > Hey, this is great! I tried it a bit. Found some problems you can see below:
> > https://asciinema.org/a/LQWb27wSjcfpQWjzgMrpUgnNB
> 
> @ret2libc That's the same behavior bash/zsh have. Should I change it so that the history goes back when a line edit occurs?

Oh really? I will check it out, but if that's how bash works i guess it's fine then. It just seems a bit strange at first sight

**Review by ret2libc — APPROVED** [review]
Thanks!

**Review by XVilka — APPROVED** [review]

**Pull request merged**
