### PR TITLE
Cherry-picks for v0.6.1 release

### PR DESCRIPTION
**Pull request by thestr4ng3r**
# DO NOT SQUASH

### CODE REVIEW

**Comment by wargio** [comment]
we need also to integrate a bugfix on libdemangle: #3753

**Comment by pelijah** [comment]
#3741 too

**Comment by p371jah** [comment]
#3741 too

**Comment by thestr4ng3r** [comment]
> subprojects/blake3/meson.build:129:4: ERROR: Tried to use 'add_project_arguments' after a build target has been declared.

This also needs to be fixed on dev

**Comment by XVilka** [comment]
Also needs this one to be fixed: https://github.com/rizinorg/rizin/issues/3737

**Comment by thestr4ng3r** [comment]
Maybe worth fixing too if enough time:
* ~~https://build.macports.org/builders/ports-10.7_x86_64-builder/builds/154842/steps/install-port/logs/stdio (might be already fixed by the latest blake3 changes)~~ Fix: https://github.com/rizinorg/rizin/pull/3764
* ~~https://build.macports.org/builders/ports-10.6_x86_64-builder/builds/165561/steps/install-port/logs/stdio~~ Too complex for a patch release. Workaround is to build with `-Ddebugger=false`.

**Comment by XVilka** [comment]
These two should be picked too:
- https://github.com/rizinorg/rizin/commit/e26ae5f63c0ba94bac789c8293e916965b1ef32c
- https://github.com/rizinorg/rizin/pull/3757

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Comment by XVilka** [comment]
@wargio jsdec changes also affected `EXTRA_PREFIX` CI job

**Comment by XVilka** [comment]
@wargio I think, `jsdec` like other projects also should switch to `dev`/`stable` branching scheme, would prevent such failures

**Comment by wargio** [comment]
if you want i can switch master -> dev now and drop the last commit

**Comment by XVilka** [comment]
Sounds good to me. But probably also worth moving to `stable` instead of `master` then.

**Comment by XVilka** [comment]
Just in Rizin `stable` branch of course (this PR)

**Comment by wargio** [comment]
This also should be cherry-picked https://github.com/rizinorg/rizin/pull/3773

**Pull request merged**
