### PR TITLE
Fixed 'ctrl+arrow' and 'alt+arrow key' in rizin shell

### PR DESCRIPTION
**Pull request by borzacchiello**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

The PR simply fixes `ctrl+arrow key` (and `alt+arrow key`) bindings in rizin shell. In particular:

`ctrl-left`: move the cursor backward by one word
`ctrl-right`: move the cursor forward by one word
`ctrl-up`: move the cursor to the beginning of the line
`ctrl-down`: move the cursor to the end of the line

**Test plan**

**Closing issues**

...

### CODE REVIEW

**Comment by ret2libc** [comment]
Which system did you test? Linux or Windows?

**Review by XVilka — APPROVED** [review]
I confirm it fixed the problem (don't forget to set `e scr.prompt.vi=false`) on Fedora Linux, Konsole terminal.

**Comment by borzacchiello** [comment]
> Which system did you test? Linux or Windows?

Linux only

**Review by ret2libc — APPROVED** [review]

**Comment by wargio** [comment]
I LOVE YOU. i hated not being able to do that and i was going to do this one day

**Review by wargio — APPROVED** [review]

**Comment by ret2libc** [comment]
Merged with admin power, because otherwise there's a lot of stuff that always prevents the auto-merge and it needs to rebuild everything for no real reason...

**Pull request merged**
