### PR TITLE
Fix dwarf5 load

### PR DESCRIPTION
**Pull request by b1llow**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

- fix dwarf5 DW_FORM_strx and '.debug_str_offsets' section load
	Not sure why str_offsets becomes non-standard section names on macos, but added compatibility for such case.

- add 'cb_dwo_path' and fix dwo load

**Test plan**

...

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
How did you spot it? Is there any test? Maybe better to add it to prevent future regressions?

**Comment by b1llow** [comment]
> How did you spot it? Is there any test? Maybe better to add it to prevent future regressions?

When I compile a simple snippet of code locally and try to open it with rizin I find that it doesn't open properly.

```c
char *global_data = "1000";

int main() {
    printf("In main, global_data: %s\n", global_data);
    return 0;
}
```

**Comment by b1llow** [comment]
https://github.com/rizinorg/rizin-testbins/pull/161

Added some tests, should pass CI after the PR merge in `rizin-testbins` repository

> > How did you spot it? Is there any test? Maybe better to add it to prevent future regressions?
> 
> When I compile a simple snippet of code locally and try to open it with rizin I find that it doesn't open properly.
> 
> ```c
> char *global_data = "1000";
> 
> int main() {
>     printf("In main, global_data: %s\n", global_data);
>     return 0;
> }
> ```

**Comment by b1llow** [comment]
The dwo generated by `-gsplitdwarf` doesn't seem to be used very much. It's more a case of copying all the `.debug_*` sections into a binary file (`*.debug`).

**Comment by XVilka** [comment]
```
Mismatched function annotation for rz_bin_dwarf_line_from_file at <rizin/librz/include/rz_bin_dwarf.h:1535:31> : RZ_BORROW (was RZ_NULLABLE at <rizin/librz/bin/dwarf/line.c:728:31>
Mismatched function annotation for rz_bin_dwarf_line_from_file at <rizin/librz/include/rz_bin_dwarf.h:1535:31> : RZ_NULLABLE (was RZ_BORROW at <rizin/librz/bin/dwarf/line.c:728:31>
```

**Review by XVilka — APPROVED** [review]

**Pull request merged**
