### PR TITLE
Enable Travis CI PPC tests

### LINKED ISSUE #1431: PPC broken test: db/analysis/sysz aoj 4140f008
See https://github.com/rizinorg/rizin/pull/1250 and https://github.com/rizinorg/rizin/pull/1250#issuecomment-876493375 in particular.

### LINKED ISSUE #1432: PPC broken test: db/tools/rz_gg rz-gg debruijn sequence
See #1250 and https://github.com/rizinorg/rizin/pull/1250#issuecomment-869583762 in particular.

AFAIR the problem is in main/rz-gg.c that tries to disassemble things even if only the patterns should be printed.

### LINKED ISSUE #1433: PPC broken test: db/cmd/types tpv
See https://github.com/rizinorg/rizin/pull/1250#issuecomment-869583762 .

### PR DESCRIPTION
**Pull request by XVilka**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Looks like Travis PPC tests were passing for some time except a few broken. Lets see what will fail, would be nice to fix them for 0.3.0

**Test plan**

CI is green

Closes https://github.com/rizinorg/rizin/issues/1433

### CODE REVIEW

**Comment by XVilka** [comment]
Still 4 broken tests:
```
[XX] db/tools/rz_gg rz-gg debruijn sequence 1
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -r -P 2; ?e' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-AA
+
-- stderr
rz_egg_assemble: invalid assembly

[XX] db/tools/rz_gg rz-gg debruijn sequence 2
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc '!rz-gg -P 2 -r; ?e' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-AA
+
-- stderr
rz_egg_assemble: invalid assembly

[XX] db/analysis/sysz aoj 4140f008
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.arch=sysz
e asm.bits=64
wx 4140f008
aoj~{}
' =
-- stdout
--- expected
+++ actual
@@ -2,7 +2,7 @@
   {
     "opcode": "la %r4, 8(%r15)",
     "disasm": "la %r4, 8(%r15)",
-    "pseudo": "la %r4,8(%r15) ",
+    "pseudo": "%r4 = %r15 + 8",
     "description": "Load Address",
     "mnemonic": "la",
     "mask": "ffffffff",

[XX] db/cmd/types tpv
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'td "struct s16ui { uint16_t a_u; int16_t b_i; uint16_t c_u; int16_t d_i;}"
td "struct s16iu { int16_t a_i; uint16_t b_u; int16_t c_i; uint16_t d_u;}"
td "struct s32ui { uint32_t e_u; int16_t f_i;}"
td "struct s32iu { int32_t e_i; uint16_t f_u;}"
e asm.bits=16
e cfg.bigendian=true
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
e cfg.bigendian=false
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
e asm.bits=32
e cfg.bigendian=true
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
e cfg.bigendian=false
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
e asm.bits=64
e cfg.bigendian=true
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
e cfg.bigendian=false
tpv s16ui 0xcafebabecafebabe
tpv s16iu 0xcafebabecafebabe
tpv s32ui 0xcafebabecafebabe
tpv s32iu 0xcafebabecafebabe
' =
-- stdout
--- expected
+++ actual
@@ -1,27 +1,27 @@
+ a_u : 0x00000000 = 0xcafe
+ b_i : 0x00000002 = 0xbabe
+ c_u : 0x00000004 = 0xcafe
+ d_i : 0x00000006 = 0xbabe
+ a_i : 0x00000000 = 0xcafe
+ b_u : 0x00000002 = 0xbabe
+ c_i : 0x00000004 = 0xcafe
+ d_u : 0x00000006 = 0xbabe
+ e_u : 0x00000000 = 3405691582
+ f_i : 0x00000004 = 0xcafe
+ e_i : 0x00000000 = 3405691582
+ f_u : 0x00000004 = 0xcafe
  a_u : 0x00000000 = 0xbabe
- b_i : 0x00000002 = 0x0000
- c_u : 0x00000004 = 0x0000
- d_i : 0x00000006 = 0x0000
+ b_i : 0x00000002 = 0xcafe
+ c_u : 0x00000004 = 0xbabe
+ d_i : 0x00000006 = 0xcafe
  a_i : 0x00000000 = 0xbabe
- b_u : 0x00000002 = 0x0000
- c_i : 0x00000004 = 0x0000
- d_u : 0x00000006 = 0x0000
- e_u : 0x00000000 = 3133014016
- f_i : 0x00000004 = 0x0000
- e_i : 0x00000000 = 3133014016
- f_u : 0x00000004 = 0x0000
- a_u : 0x00000000 = 0xbabe
- b_i : 0x00000002 = 0x0000
- c_u : 0x00000004 = 0x0000
- d_i : 0x00000006 = 0x0000
- a_i : 0x00000000 = 0xbabe
- b_u : 0x00000002 = 0x0000
- c_i : 0x00000004 = 0x0000
- d_u : 0x00000006 = 0x0000
- e_u : 0x00000000 = 47806
- f_i : 0x00000004 = 0x0000
- e_i : 0x00000000 = 47806
- f_u : 0x00000004 = 0x0000
+ b_u : 0x00000002 = 0xcafe
+ c_i : 0x00000004 = 0xbabe
+ d_u : 0x00000006 = 0xcafe
+ e_u : 0x00000000 = 3405691582
+ f_i : 0x00000004 = 0xbabe
+ e_i : 0x00000000 = 3405691582
+ f_u : 0x00000004 = 0xbabe
  a_u : 0x00000000 = 0xcafe
  b_i : 0x00000002 = 0xbabe
  c_u : 0x00000004 = 0x0000
```

**Comment by ret2libc** [comment]
Fun fact:
```
[XX] db/analysis/sysz aoj 4140f008
RZ_NOPLUGINS=1 rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'e asm.arch=sysz
e asm.bits=64
wx 4140f008
aoj~{}
' =
-- stdout
--- expected
+++ actual
@@ -2,7 +2,7 @@
   {
     "opcode": "la %r4, 8(%r15)",
     "disasm": "la %r4, 8(%r15)",
-    "pseudo": "la %r4,8(%r15) ",
+    "pseudo": "%r4 = %r15 + 8",
     "description": "Load Address",
     "mnemonic": "la",
     "mask": "ffffffff",
```
is better than what we have right now :D that's the real pseudo code.

Update:
On ppc64le machine:
```
Breakpoint 1, rz_parse_parse (p=0x10069160, data=0x7fffffffd9f0 "la %r4, 8(%r15)", str=0x100e41f0 "") at ../librz/parse/parse.c:104
104             rz_return_val_if_fail(p && data && str, false);
Missing separate debuginfos, use: dnf debuginfo-install glibc-2.33-18.fc34.ppc64le
(gdb) next
105             return (p && data && *data && p->cur && p->cur->parse)
(gdb) step
parse (p=0x10069160, data=0x7fffffffd9f0 "la %r4, 8(%r15)", str=0x100e41f0 "") at ../librz/parse/p/parse_ppc_pseudo.c:1619
1619            int i, len = strlen(data);
```
On x86 machine:
```
parse (p=0x4428f0, data=0x7fffffffbe60 "la %r4, 8(%r15)", str=0x512590 "") at ../librz/parse/p/parse_x86_pseudo.c:172
172             size_t len = strlen(data);
```
That means that on x86 it is calling x86 parsing for some reasons.

Update 2:
`rz_parse_use` is called with sysz.pseudo but given there is no such RzParsePlugin, `p->cur` is not changed and it remains set to the previous one, which depends on the architecture. I think `p->cur` should be set to NULL if it can't find the right plugin.

**Comment by wargio** [comment]
that pseudo is wrong

**Review by wargio — APPROVED** [review]
I knew it was an endianness probelm handled somewhere... thanks for this patch <3

**Comment by wargio** [comment]
the bug is still there.. :/

**Pull request merged**
