### PR TITLE
Add "initial view" test for Visual mode

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [X] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr adds a test for Visual mode, depicting the initial view after `V`.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Comment by XVilka** [comment]
Could you please add the same test but for Windows also?

**Comment by kazarmy** [comment]
Okay e4a1bfec67f9ce1818f3bdadd1ded7e6109eabeb

**Review by ret2libc — APPROVED** [review]
Awesome, our first visual test? :D
BTW, is there any difference between the two tests? Can we move it under a common dir that is always executed or are there arch-specific things?

**Comment by kazarmy** [comment]
> Awesome, our first visual test? :D

There were some tests under [db/cmd/cmd_visual](https://github.com/rizinorg/rizin/blob/7ce7fa6acc1042119902dfebd5bbf7bd60831284/test/db/cmd/cmd_visual) but they tested side effects after the `V` command, rather than the output of `V` itself.

> BTW, is there any difference between the two tests? Can we move it under a common dir that is always executed or are there arch-specific things?

The difference is an extraneous `^M` on the last line of the Linux `V` test output (it can be seen using `git diff --no-index`). It appears to be a bug but some spelunking through the source code is needed to fix it.

**Pull request merged**
