### PR TITLE
Fix gcc12-asan mpc -Wformat-overflow= warnings

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes gcc12-asan warnings from `mpc.c` of the following form (https://github.com/rizinorg/rizin/actions/runs/3212556636/jobs/5251532585#step:13:1051):

mpc-format-overflow

This is a cherry-pick from #3066.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by XVilka — APPROVED** [review]
LGTM but please also send a PR to the mainstream: https://github.com/orangeduck/mpc

**Comment by kazarmy** [comment]
Ok. It does appear that mpc's policy regarding `malloc()` is to simply ignore that it can return NULL, but we'll see how it goes.

**Comment by kazarmy** [comment]
https://github.com/orangeduck/mpc/pull/148

**Comment by XVilka** [comment]
Thanks!

**Pull request merged**
