### PR TITLE
Fix warnings of shifting negative value

### PR DESCRIPTION
**Pull request by Heersin**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

Fix warnings of this [pr#917](https://github.com/rizinorg/rizin/pull/917)

### CODE REVIEW

**Comment by XVilka** [comment]
It fixed that warning but there is one more:
````
[730/1595] Compiling C object librz/asm/librz_asm.so.0.3.0-git.p/p_asm_luac.c.o[K
[1m../librz/asm/p/asm_luac.c:42:13: [0m[0;1;35mwarning: [0m[1mvariable 'instruction' is used uninitialized whenever 'if' condition is false [-Wsometimes-uninitialized][0m
        } else if (strcmp(a->cpu, "5.4") == 0) {
[0;1;32m                   ^~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m../librz/asm/p/asm_luac.c:48:22: [0m[0;1;30mnote: [0muninitialized use occurs here[0m
        lua_set_instruction(instruction, buffer);
[0;1;32m                            ^~~~~~~~~~~
[0m[1m../librz/asm/p/asm_luac.c:42:9: [0m[0;1;30mnote: [0mremove the 'if' if its condition is always true[0m
        } else if (strcmp(a->cpu, "5.4") == 0) {
[0;1;32m               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[0m[1m../librz/asm/p/asm_luac.c:30:18: [0m[0;1;30mnote: [0minitialize the variable 'instruction' to silence this warning[0m
        ut32 instruction;
[0;1;32m                        ^
[0m[0;32m                         = 0
[0m1 warning generated.
```

**Review by XVilka — APPROVED** [review]

**Review by XVilka — APPROVED** [review]
Perfect, thanks!

**Comment by XVilka** [comment]
@Heersin The is one OOB Read issue reported by Coverity in `librz/asm/arch/luac/v54/assembly_54.c`, see:
```
  6static LuaInstruction encode_instruction(ut8 opcode, const char *arg_start, ut16 flag, ut8 arg_num) {
  7        LuaInstruction instruction = 0;
  8        int args[4];
  9        char buffer[64]; // buffer for digits
   1. assignment: Assigning: cur_cnt = 0.
 10        int cur_cnt = 0;
 11        int delta_offset;
 12
   2. Condition arg_num > 16UL /* sizeof (args) */, taking false branch.
 13        if (arg_num > sizeof(args)) {
 14                return -1;
 15        }
 16
   3. Condition i < arg_num, taking true branch.
   8. Condition i < arg_num, taking false branch.
 17        for (int i = 0; i < arg_num; ++i) {
 18                delta_offset = lua_load_next_arg_start(arg_start, buffer);
   4. Condition delta_offset == 0, taking false branch.
 19                if (delta_offset == 0) {
 20                        return -1;
 21                }
   5. Condition lua_is_valid_num_value_string(buffer), taking true branch.
 22                if (lua_is_valid_num_value_string(buffer)) {
 23                        args[i] = lua_convert_str_to_num(buffer);
 24                        arg_start += delta_offset;
   6. Falling through to end of if statement.
 25                } else {
 26                        return -1;
 27                }
   7. Jumping back to the beginning of the loop.
 28        }
 29
 30        LUA_SET_OPCODE(instruction, opcode);
   9. Condition flag & 1, taking true branch.
   10. Condition (flag & 1) ? 1 : 0, taking true branch.
 31        if (has_param_flag(flag, PARAM_A)) {
   11. incr: Incrementing cur_cnt. The value of cur_cnt is now 1.
 32                SETARG_A(instruction, args[cur_cnt++]);
 33        }
   12. Condition flag & 2, taking true branch.
   13. Condition (flag & 2) ? 1 : 0, taking true branch.
 34        if (has_param_flag(flag, PARAM_B)) {
   14. incr: Incrementing cur_cnt. The value of cur_cnt is now 2.
 35                SETARG_B(instruction, args[cur_cnt++]);
 36        }
   15. Condition flag & 0x100, taking true branch.
   16. Condition (flag & 0x100) ? 1 : 0, taking true branch.
 37        if (has_param_flag(flag, PARAM_sB)) {
   17. incr: Incrementing cur_cnt. The value of cur_cnt is now 3.
 38                SETARG_sB(instruction, args[cur_cnt++]);
 39        }
   18. Condition flag & 4, taking true branch.
   19. Condition (flag & 4) ? 1 : 0, taking true branch.
 40        if (has_param_flag(flag, PARAM_C)) {
   20. incr: Incrementing cur_cnt. The value of cur_cnt is now 4.
 41                SETARG_C(instruction, args[cur_cnt++]);
 42        }
   21. Condition flag & 0x80, taking true branch.
   22. Condition (flag & 0x80) ? 1 : 0, taking true branch.
 43        if (has_param_flag(flag, PARAM_sC)) {
   CID 319265 (#9 of 9): Out-of-bounds read (OVERRUN)23. overrun-local: Overrunning array args of 4 4-byte elements at element index 4 (byte offset 19) using index cur_cnt++ (which evaluates to 4).
 44                SETARG_sC(instruction, args[cur_cnt++]);
 45        }
 46        if (has_param_flag(flag, PARAM_Ax)) {
   CID 319265 (#6 of 9): Out-of-bounds read (OVERRUN) [select issue]
 47                SETARG_Ax(instruction, args[cur_cnt++]);
 48        }
 49        if (has_param_flag(flag, PARAM_sBx)) {
   CID 319265 (#7 of 9): Out-of-bounds read (OVERRUN) [select issue]
 50                SETARG_sBx(instruction, args[cur_cnt++]);
 51        }
 52        if (has_param_flag(flag, PARAM_Bx)) {
   CID 319265 (#3 of 9): Out-of-bounds read (OVERRUN) [select issue]
 53                SETARG_Bx(instruction, args[cur_cnt++]);
 54        }
 55        if (has_param_flag(flag, PARAM_sJ)) {
   CID 319265 (#4 of 9): Out-of-bounds read (OVERRUN) [select issue]
 56                SETARG_sJ(instruction, args[cur_cnt++]);
 57        }
 58        if (has_param_flag(flag, PARAM_k)) {
   CID 319265 (#2 of 9): Out-of-bounds read (OVERRUN) [select issue]
 59                SETARG_k(instruction, args[cur_cnt++]);
 60        }
 61        assert(cur_cnt == arg_num);
 62
 63        return instruction;
 64}
 ```

**Comment by Heersin** [comment]
@XVilka Seems like Coverity would simply take every true branches if there is no explicit constraint to condition variable. OOB happens only when developer set more PARAM flags than `arg_num`, so I put an assertion to prevent it.
I add some checks inside the branches in #1037

**Pull request merged**
