### PR TITLE
io: return error when reading/writing to unmapped memory

### LINKED ISSUE #2871: Insert in visual mode doesn't give correct feedback.
### Work environment

 - debian x86_64
 - Today's main dev `48bed798240e`

### Expected behavior

Modifications made in visual mode should be updated in visual mode display  and `px` should show the modifications.

### Actual behavior

Bytes not updated in visual mode or `px` output, **but** if you exit rizin and go back in, the file has in fact been updated!

### Steps to reproduce the behavior

```
$ touch /tmp/a
$ rizin -w /tmp/a
V # to enter visual mode
i # to enter insert mode
01020304 # insert some bytes
# display not updated!
qq # to go back to rizin shell
px # bytes not updated!
CTRL+D # exit rizin
$ rizin -w /tmp/a
px # bytes are in fact updated!
```

### PR DESCRIPTION
**Pull request by ret2libc**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

See commits.

**Test plan**

See steps in #2871 .

**Closing issues**

Closes #2871

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
It probaby needs changes in more places due to the changed skyline behavior:
```
[XX] db/cmd/cmd_pf2 pf *z (64bit addr)
RZ_NOPLUGINS=1 /usr/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e io.cache=true
e asm.bits=64
wz root @ 0x0000000100000faf
pf z @ 0x0000000100000faf
e cfg.bigendian=false
16wx cc @ 0x200 @e:cfg.wseek=true
wv8 0x0000000100000faf @ 0x204
pf *z @ 0x204
e cfg.bigendian=true
16wx cc @ 0x200 @e:cfg.wseek=true
wv8 0x0000000100000faf @ 0x204
pf *z @ 0x204
' =
-- stdout
--- expected
+++ actual
@@ -1,3 +1,3 @@
-0x100000faf = "root"
-(*0x100000faf)0x00000204 = "root"
-(*0x100000faf)0x00000204 = "root"
+-1
+(*0x100000faf)-1
+(*0x100000faf)-1
```

The unrelated to IO changes are LGTM.

**Comment by wargio** [comment]
```
[XX] db/analysis/ppc ppc-update-suffix-esil
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc '40ds
ar r3
ar r4
10ds
ar r3
ar r4
' bins/elf/a6ppc.out
-- stdout
--- expected
+++ actual
@@ -1,4 +1,4 @@
-r3 = 0x0000ffbf
+r3 = 0x00010007
 r4 = 0x10010107
-r3 = 0x0000ffc1
+r3 = 0x00010007
 r4 = 0x1001010a

[XX] db/esil/x86_64 test_sf
RZ_NOPLUGINS=1 /home/runner/bin/rizin -escr.utf8=0 -escr.color=0 -escr.interactive=0 -eflirt.sigdb.load.system=false -eflirt.sigdb.load.home=false -N -Qc 'e asm.arch=x86;e asm.bits=64;s 0;aei;ar rip=0;wa test eax, eax;ar eax=-1;aes
ar 1~sf
' =
-- stdout
--- expected
+++ actual
@@ -1,1 +1,1 @@
-sf = 0x1
+sf = 0x0

-- stderr
ERROR: assembler: x86.nz: test: invalid operands
ERROR: assembler: x86.nz: test: invalid operands
ERROR: assembler: x86.nz: test: invalid operands
ERROR: Cannot assemble 'test' at line 7
```

**Review by XVilka — APPROVED** [review]
Looks good now.

**Comment by ret2libc** [comment]
Yes but wait please, I put it in draft mode because I want to review a bit.

**Review by XVilka — APPROVED** [review]

**Review by wargio — APPROVED** [review]

**Pull request merged**
