### PR TITLE
rz_cons_print_fps: Fix double->int conversion warning

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr fixes the following warning (https://ci.appveyor.com/project/rizinorg/rizin/builds/43145343/job/cjfgh2cej416cbpo?fullLog=true#L1063):

cons_fps_warning

**Test plan**

All builds are green. The warning is no longer there. `scr.fps` works as intended.

**Closing issues**

...

### CODE REVIEW

**Comment by wargio** [comment]
tbh, this function could be even deleted. @XVilka @thestr4ng3r @ret2libc

**Comment by ret2libc** [comment]
I don't even know what it does...

**Comment by wargio** [comment]
prints the fps of the drawed ui. it was mostly used for stuff we have removed, like the donut

**Comment by XVilka** [comment]
Remove it.

**Comment by kazarmy** [comment]
Oh alright

**Pull request closed without merging**
