### PR TITLE
Bump PCRE2 to 10.43 release.

### LINKED ISSUE #4208: Switch to PCRE2 release in subproject once 10.43 is out
Currently, the subproject uses git, but they are planning the release soon, so we should switch to using it instead.

See:
- `subprojects/pcre2.wrap`
- `subprojects/pcre2-native.wrap`

https://github.com/PCRE2Project/pcre2/releases

### PR DESCRIPTION
**Pull request by Rot127**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

...

**Test plan**

All green

**Closing issues**

closes https://github.com/rizinorg/rizin/issues/4208

### CODE REVIEW

**Review by XVilka — CHANGES_REQUESTED** [review]
You forgot to update Meson file for `pcre2_cross_native`

**Comment by XVilka** [comment]
Please also rebase on top of the latest `dev`

**Review by XVilka — APPROVED** [review]

**Review by XVilka — CHANGES_REQUESTED** [review]
Android builds fail with this error:
```
pcre2_cross_native| C compiler for the host machine: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang (clang 14.0.7 "Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)")
pcre2_cross_native| C linker for the host machine: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android33-clang ld.lld 14.0.7
pcre2_cross_native| C compiler for the build machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
pcre2_cross_native| C linker for the build machine: cc ld.bfd 2.38
subprojects/pcre2_cross_native-10.43/meson.build:11:19: ERROR: File src/pcre2_chartables.c.dist does not exist.
A full log can be found at /home/runner/work/rizin/rizin/build/meson-logs/meson-log.txt
Error: Process completed with exit code 1.
```
https://github.com/rizinorg/rizin/actions/runs/7940320899/job/21682513065?pr=4255#step:4:81

**Comment by XVilka** [comment]
@Rot127 also, version in the `subproject/packagefiles/pcre2/meson.build` and `subproject/packagefiles/pcre2_cross_native/meson.build` should be updated to the '10.43'

**Review by XVilka — APPROVED** [review]
I fixed those problems for you. Will merge once CI is green.

**Comment by Rot127** [comment]
@XVilka Thanks!

**Comment by XVilka** [comment]
Strange, it didn't help, error is still here:
```
Executing subproject pcre2_cross_native 

pcre2_cross_native| Project name: pcre2_cross_native
pcre2_cross_native| Project version: 10.43
pcre2_cross_native| C compiler for the host machine: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android33-clang (clang 14.0.7 "Android (9352603, based on r450784d1) clang version 14.0.7 (https://android.googlesource.com/toolchain/llvm-project 4c603efb0cca074e9238af8b4106c30add4418f6)")
pcre2_cross_native| C linker for the host machine: /usr/local/lib/android/sdk/ndk/25.2.9519653/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android33-clang ld.lld 14.0.7
pcre2_cross_native| C compiler for the build machine: cc (gcc 11.4.0 "cc (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0")
pcre2_cross_native| C linker for the build machine: cc ld.bfd 2.38

subprojects/pcre2_cross_native-10.43/meson.build:11:19: ERROR: File src/pcre2_chartables.c.dist does not exist.

A full log can be found at /home/runner/work/rizin/rizin/build/meson-logs/meson-log.txt
Error: Process completed with exit code 1.
```

**Pull request merged**
