### PR TITLE
Use `ar` in some rzil bf tests instead of `aezv`

### PR DESCRIPTION
**Pull request by kazarmy**
**Your checklist for this pull request**
- [X] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [ ] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've documented or updated the documentation of every function and struct this PR changes. If not so I've explained why.
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

This pr replaces some usage of `aezv` in the rzil `bf` tests with `ar` as it is the primary source for emulation register values.

**Test plan**

All builds are green.

**Closing issues**

...

### CODE REVIEW

**Review by ret2libc — APPROVED** [review]

**Review by wargio — APPROVED** [review]
now that we have that layer, makes sense to switch when writing tests

**Comment by kazarmy** [comment]
> now that we have that layer, makes sense to switch when writing tests

not entirely sure what you mean by that ... btw, the reason for this pr is due to the explanation given [here](https://github.com/rizinorg/rizin/pull/2275#pullrequestreview-870271410)

**Comment by kazarmy** [comment]
with this pr yes i've basically traded the consistency of `aezv` and `ar` for less coding

**Comment by kazarmy** [comment]
with this pr yes i've basically traded the consistency of `aezv` with `ar`, for less coding

**Comment by kazarmy** [comment]
with this pr yes i've basically traded the consistency of `aezv` with `ar`, for less coding

**Pull request merged**
