### PR TITLE
Refactor DT_HASH and DT_GNU_HASH in librz/bin/format/elf_hash.c

### PR DESCRIPTION
**Pull request by ghost**
**Your checklist for this pull request**
- [x] I've read the [guidelines for contributing](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md) to this repository
- [x] I made sure to follow the project's [coding style](https://github.com/rizinorg/rizin/blob/master/DEVELOPERS.md#code-style)
- [ ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ ] I've updated the documentation and the [rizin book](https://github.com/rizinorg/book) with the relevant information (if needed)

**Detailed description**

I moved hash related stuff in a separated file.

Feedback:

In the future, it is possible to add `dt_gnu_hash` and `dt_hash` to `ELFOBJ` and parse more information, such as buckets and chains (it will save multiple read operation).

If you want, `dt_gnu_hash` can be named `gnu_hash_table`(`RzBinElfGnuHashTable`) and `dt_hash` can be named `elf_hash_table`(`RzBinElfHashTable`). 

...

**Test plan**
...

**Closing issues**

...

### CODE REVIEW

**Review by thestr4ng3r — APPROVED** [review]
> If you want, dt_gnu_hash can be named gnu_hash_table(RzBinElfGnuHashTable) and dt_hash can be named elf_hash_table(RzBinElfHashTable).

Both are fine. What is important to me though is that it stays easy to google what exactly the respective struct is parsed from. So e.g. if it is called gnu_hash_table, there should be some comment mentioning `DT_GNU_HASH`.

**Comment by ret2libc** [comment]
Does it fixes the problem on the hello world bin? Can you try randomly with some bins in test and on your system?

**Comment by ghost** [comment]
> Does it fixes the problem on the hello world bin? Can you try randomly with some bins in test and on your system?

It shouldn't modify any behavior.

**Comment by ghost** [comment]
> > If you want, dt_gnu_hash can be named gnu_hash_table(RzBinElfGnuHashTable) and dt_hash can be named elf_hash_table(RzBinElfHashTable).
> 
> Both are fine. What is important to me though is that it stays easy to google what exactly the respective struct is parsed from. So e.g. if it is called gnu_hash_table, there should be some comment mentioning `DT_GNU_HASH`.

I renamed both struct as commented.

**Pull request merged**
